// Generated by tools/gen_fonts.swift; do not edit by hand.
// Bulk glyph and string data lives in fonts.bin (embedded into the app
// image via EMBED_FILES); everything here is offsets into that blob.
#include "fonts.h"

#ifndef FONTS_BLOB_HOST
extern const uint8_t fonts_blob[] __asm__("_binary_fonts_bin_start");
#else
extern const uint8_t fonts_blob[];  // host harness provides the blob
#endif

// Pointer-into-blob shorthands: FB is a string, FB16 a uint16 table.
#define FB(off)   ((const char *)(fonts_blob + (off)))
#define FB16(off) ((const uint16_t *)(const void *)(fonts_blob + (off)))
// hy: 57 glyphs (Noto Sans Armenian)
const display_glyph_font_t font_hy = {
    .codepoints = FB16(0),
    .glyphs_rle = fonts_blob + 114,
    .glyphs_off = FB16(2570),
    .glyphs_2x_rle = fonts_blob + 2686,
    .glyphs_2x_off = FB16(4948),
    .count = 57,
    .glyph_width = 10,
};
// ja: 114 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_ja = {
    .codepoints = FB16(5064),
    .glyphs_rle = fonts_blob + 5292,
    .glyphs_off = FB16(14850),
    .glyphs_2x_rle = fonts_blob + 15080,
    .glyphs_2x_off = FB16(17024),
    .count = 114,
    .glyph_width = 16,
};
// ka: 29 glyphs (Helvetica)
const display_glyph_font_t font_ka = {
    .codepoints = FB16(17254),
    .glyphs_rle = fonts_blob + 17312,
    .glyphs_off = FB16(18946),
    .glyphs_2x_rle = fonts_blob + 19006,
    .glyphs_2x_off = FB16(21758),
    .count = 29,
    .glyph_width = 10,
};
// ko: 105 glyphs (Apple SD Gothic Neo)
const display_glyph_font_t font_ko = {
    .codepoints = FB16(21818),
    .glyphs_rle = fonts_blob + 22028,
    .glyphs_off = FB16(29818),
    .glyphs_2x_rle = fonts_blob + 30030,
    .glyphs_2x_off = FB16(31528),
    .count = 105,
    .glyph_width = 16,
};
// yue: 108 glyphs (PingFang HK)
const display_glyph_font_t font_yue = {
    .codepoints = FB16(31740),
    .glyphs_rle = fonts_blob + 31956,
    .glyphs_off = FB16(41258),
    .glyphs_2x_rle = fonts_blob + 41476,
    .glyphs_2x_off = FB16(42904),
    .count = 108,
    .glyph_width = 16,
};
// zh: 114 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_zh = {
    .codepoints = FB16(43122),
    .glyphs_rle = fonts_blob + 43350,
    .glyphs_off = FB16(53678),
    .glyphs_2x_rle = fonts_blob + 53908,
    .glyphs_2x_off = FB16(55568),
    .count = 114,
    .glyph_width = 16,
};
// zh_hant: 115 glyphs (PingFang TC)
const display_glyph_font_t font_zh_hant = {
    .codepoints = FB16(55798),
    .glyphs_rle = fonts_blob + 56028,
    .glyphs_off = FB16(65946),
    .glyphs_2x_rle = fonts_blob + 66178,
    .glyphs_2x_off = FB16(67784),
    .count = 115,
    .glyph_width = 16,
};
// base: ASCII plus 277 supplementary glyphs (Menlo)
const uint8_t *const font_base_ascii_rle = fonts_blob + 68016;
const uint16_t *const font_base_ascii_off = FB16(71284);
const uint8_t *const font_base_ascii_2x_rle = fonts_blob + 71476;
const uint16_t *const font_base_ascii_2x_off = FB16(77236);
const uint16_t *const font_base_ext_cp = FB16(77428);
const uint8_t *const font_base_ext_rle = fonts_blob + 77982;
const uint16_t *const font_base_ext_off = FB16(89582);
const uint8_t *const font_base_ext_2x_rle = fonts_blob + 90138;
const uint16_t *const font_base_ext_2x_off = FB16(103158);
const uint16_t font_base_ext_count = 277;
// ar: 179 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ar 65799dc5e1bd6c46
const display_glyph_font_t font_ar = {
    .codepoints = FB16(103714),
    .glyphs_rle = fonts_blob + 104251,
    .glyphs_off = FB16(110982),
    .glyphs_2x_rle = fonts_blob + 111342,
    .glyphs_2x_off = FB16(115698),
    .widths = fonts_blob + 104072,
    .count = 179,
    .glyph_width = 16,
};
const char *const lang_ar_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(116058), [STR_WIFI] = FB(116083), [STR_FAIL] = FB(116089),
    [STR_TIMEZONE] = FB(116099), [STR_BRIGHTNESS] = FB(116142), [STR_LED_BLINK] = FB(116161),
    [STR_ROTATE] = FB(116186), [STR_ABOUT] = FB(116214), [STR_LANGUAGE] = FB(116224),
    [STR_DONE] = FB(116240), [STR_BACK] = FB(116247), [STR_CANCEL] = FB(116260),
    [STR_DEL] = FB(116276), [STR_RUNNING] = FB(116286), [STR_ON] = FB(116299),
    [STR_OFF] = FB(116312), [STR_NTS_NO] = FB(116325), [STR_NTS_ATTEMPT] = FB(116329),
    [STR_NTS_REQUIRE] = FB(116348), [STR_WAITING_NTP] = FB(116364),
    [STR_FMT_SYNCED] = FB(116407), [STR_FMT_SYNCING] = FB(116434),
    [STR_FMT_WAITING] = FB(116461), [STR_WIFI_SETUP] = FB(116490), [STR_SCANNING] = FB(116524),
    [STR_SCAN_FAILED] = FB(116546), [STR_TAP_RETRY] = FB(116574),
    [STR_SELECT_NETWORK] = FB(116629), [STR_NO_NETWORKS] = FB(116663),
    [STR_NETWORK_LABEL] = FB(116700), [STR_ENTER_PASSWORD] = FB(116722),
    [STR_CONNECTING] = FB(116768), [STR_CONNECTING_TO] = FB(116781),
    [STR_CONNECTED] = FB(116809), [STR_CONNECTION_FAILED] = FB(116825),
    [STR_KB_SPACE] = FB(116856), [STR_KB_GO] = FB(116872), [STR_VERSION] = FB(116875),
    [STR_STATUS] = FB(116897), [STR_READ] = FB(116919), [STR_UPDATE] = FB(116932),
    [STR_RESTARTING] = FB(116948), [STR_OTA_UPDATE] = FB(116982), [STR_NTP_SERVER] = FB(117010),
    [STR_SERVER_LABEL] = FB(117035), [STR_NTP_SETTINGS] = FB(117057),
    [STR_NTP_PRESETS] = FB(117091), [STR_PRESETS] = FB(117119), [STR_BENCHMARK] = FB(117135),
    [STR_STOPPING] = FB(117154), [STR_NTP_STATS] = FB(117170), [STR_UNSYNCED] = FB(117204),
    [STR_NONE] = FB(117235), [STR_SELECT_REGION] = FB(117251), [STR_AGE_LABEL] = FB(117285),
    [STR_SYNCS_LABEL] = FB(117313), [STR_FMT_PEERS_NOSYNC] = FB(117344),
    [STR_FMT_PEERS_AGO] = FB(117418), [STR_DST] = FB(117482), [STR_NO_DST] = FB(117513),
};
const char *const weekdays_ar_shaped[7] = {
    FB(117553), FB(117566), FB(117582), FB(117604), FB(117626), FB(117645), FB(117664),
};
const char *const months_ar_shaped[12] = {
    FB(117680), FB(117690), FB(117700), FB(117710), FB(117720), FB(117730), FB(117740),
    FB(117750), FB(117760), FB(117770), FB(117780), FB(117790),
};
const char lang_name_ar_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\xA0" "\xEE" "\x80" "\xA1" "\xEE" "\x80" "\xB8" "\xEE" "\x80" "\xAB" "\xEE" "\x80" "\xAC");

// fa: 211 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash fa dbfe059c4f36839d
const display_glyph_font_t font_fa = {
    .codepoints = FB16(117800),
    .glyphs_rle = fonts_blob + 118433,
    .glyphs_off = FB16(126534),
    .glyphs_2x_rle = fonts_blob + 126958,
    .glyphs_2x_off = FB16(132492),
    .widths = fonts_blob + 118222,
    .count = 211,
    .glyph_width = 16,
};
const char *const lang_fa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(132916), [STR_WIFI] = FB(132938), [STR_FAIL] = FB(132944),
    [STR_TIMEZONE] = FB(132954), [STR_BRIGHTNESS] = FB(132988), [STR_LED_BLINK] = FB(133010),
    [STR_ROTATE] = FB(133035), [STR_ABOUT] = FB(133060), [STR_LANGUAGE] = FB(133079),
    [STR_DONE] = FB(133092), [STR_BACK] = FB(133108), [STR_CANCEL] = FB(133127),
    [STR_DEL] = FB(133137), [STR_RUNNING] = FB(133147), [STR_ON] = FB(133181),
    [STR_OFF] = FB(133194), [STR_NTS_NO] = FB(133210), [STR_NTS_ATTEMPT] = FB(133220),
    [STR_NTS_REQUIRE] = FB(133230), [STR_WAITING_NTP] = FB(133246),
    [STR_FMT_SYNCED] = FB(133295), [STR_FMT_SYNCING] = FB(133319),
    [STR_FMT_WAITING] = FB(133352), [STR_WIFI_SETUP] = FB(133381), [STR_SCANNING] = FB(133415),
    [STR_SCAN_FAILED] = FB(133440), [STR_TAP_RETRY] = FB(133477),
    [STR_SELECT_NETWORK] = FB(133541), [STR_NO_NETWORKS] = FB(133575),
    [STR_NETWORK_LABEL] = FB(133618), [STR_ENTER_PASSWORD] = FB(133634),
    [STR_CONNECTING] = FB(133695), [STR_CONNECTING_TO] = FB(133732),
    [STR_CONNECTED] = FB(133757), [STR_CONNECTION_FAILED] = FB(133782),
    [STR_KB_SPACE] = FB(133819), [STR_KB_GO] = FB(133835), [STR_VERSION] = FB(133838),
    [STR_STATUS] = FB(133854), [STR_READ] = FB(133873), [STR_UPDATE] = FB(133895),
    [STR_RESTARTING] = FB(133923), [STR_OTA_UPDATE] = FB(133963), [STR_NTP_SERVER] = FB(134003),
    [STR_SERVER_LABEL] = FB(134028), [STR_NTP_SETTINGS] = FB(134044),
    [STR_NTP_PRESETS] = FB(134078), [STR_PRESETS] = FB(134112), [STR_BENCHMARK] = FB(134137),
    [STR_STOPPING] = FB(134153), [STR_NTP_STATS] = FB(134166), [STR_UNSYNCED] = FB(134191),
    [STR_NONE] = FB(134213), [STR_SELECT_REGION] = FB(134223), [STR_AGE_LABEL] = FB(134260),
    [STR_SYNCS_LABEL] = FB(134282), [STR_FMT_PEERS_NOSYNC] = FB(134310),
    [STR_FMT_PEERS_AGO] = FB(134390), [STR_DST] = FB(134450), [STR_NO_DST] = FB(134490),
};
const char *const weekdays_fa_shaped[7] = {
    FB(134545), FB(134564), FB(134583), FB(134599), FB(134624), FB(134646), FB(134659),
};
const char *const months_fa_shaped[12] = {
    FB(134672), FB(134694), FB(134719), FB(134735), FB(134745), FB(134761), FB(134780),
    FB(134790), FB(134803), FB(134813), FB(134820), FB(134833),
};
const char lang_name_fa_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x83" "\x88" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\x81" "\xEE" "\x81" "\xB2");

// he: 98 shaped cluster glyphs (Arial Hebrew)
// shaped-source-hash he 04d99dae314644b5
const display_glyph_font_t font_he = {
    .codepoints = FB16(134850),
    .glyphs_rle = fonts_blob + 135144,
    .glyphs_off = FB16(138840),
    .glyphs_2x_rle = fonts_blob + 139038,
    .glyphs_2x_off = FB16(141942),
    .widths = fonts_blob + 135046,
    .count = 98,
    .glyph_width = 16,
};
const char *const lang_he_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(142140), [STR_WIFI] = FB(142159), [STR_FAIL] = FB(142165),
    [STR_TIMEZONE] = FB(142178), [STR_BRIGHTNESS] = FB(142203), [STR_LED_BLINK] = FB(142222),
    [STR_ROTATE] = FB(142250), [STR_ABOUT] = FB(142278), [STR_LANGUAGE] = FB(142294),
    [STR_DONE] = FB(142304), [STR_BACK] = FB(142317), [STR_CANCEL] = FB(142330),
    [STR_DEL] = FB(142346), [STR_RUNNING] = FB(142356), [STR_ON] = FB(142369),
    [STR_OFF] = FB(142382), [STR_NTS_NO] = FB(142395), [STR_NTS_ATTEMPT] = FB(142402),
    [STR_NTS_REQUIRE] = FB(142412), [STR_WAITING_NTP] = FB(142425),
    [STR_FMT_SYNCED] = FB(142468), [STR_FMT_SYNCING] = FB(142498),
    [STR_FMT_WAITING] = FB(142528), [STR_WIFI_SETUP] = FB(142554), [STR_SCANNING] = FB(142588),
    [STR_SCAN_FAILED] = FB(142610), [STR_TAP_RETRY] = FB(142647),
    [STR_SELECT_NETWORK] = FB(142696), [STR_NO_NETWORKS] = FB(142718),
    [STR_NETWORK_LABEL] = FB(142761), [STR_ENTER_PASSWORD] = FB(142774),
    [STR_CONNECTING] = FB(142802), [STR_CONNECTING_TO] = FB(142818),
    [STR_CONNECTED] = FB(142843), [STR_CONNECTION_FAILED] = FB(142862),
    [STR_KB_SPACE] = FB(142896), [STR_KB_GO] = FB(142909), [STR_VERSION] = FB(142912),
    [STR_STATUS] = FB(142928), [STR_READ] = FB(142941), [STR_UPDATE] = FB(142957),
    [STR_RESTARTING] = FB(142970), [STR_OTA_UPDATE] = FB(143001), [STR_NTP_SERVER] = FB(143029),
    [STR_SERVER_LABEL] = FB(143051), [STR_NTP_SETTINGS] = FB(143064),
    [STR_NTP_PRESETS] = FB(143095), [STR_PRESETS] = FB(143129), [STR_BENCHMARK] = FB(143154),
    [STR_STOPPING] = FB(143170), [STR_NTP_STATS] = FB(143183), [STR_UNSYNCED] = FB(143223),
    [STR_NONE] = FB(143254), [STR_SELECT_REGION] = FB(143264), [STR_AGE_LABEL] = FB(143289),
    [STR_SYNCS_LABEL] = FB(143311), [STR_FMT_PEERS_NOSYNC] = FB(143342),
    [STR_FMT_PEERS_AGO] = FB(143425), [STR_DST] = FB(143495), [STR_NO_DST] = FB(143520),
};
const char *const weekdays_he_shaped[7] = {
    FB(143557), FB(143576), FB(143595), FB(143614), FB(143633), FB(143652), FB(143671),
};
const char *const months_he_shaped[12] = {
    FB(143681), FB(143691), FB(143701), FB(143711), FB(143721), FB(143731), FB(143741),
    FB(143751), FB(143761), FB(143771), FB(143781), FB(143791),
};
const char lang_name_he_shaped[] = ("\xEE" "\x80" "\x80" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x82" "\xEE" "\x80" "\x98" "\xEE" "\x80" "\xA6");

// hi: 186 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash hi fb71ec9a96a8553e
const display_glyph_font_t font_hi = {
    .codepoints = FB16(143802),
    .glyphs_rle = fonts_blob + 144360,
    .glyphs_off = FB16(152722),
    .glyphs_2x_rle = fonts_blob + 153096,
    .glyphs_2x_off = FB16(157448),
    .widths = fonts_blob + 144174,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_hi_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(157822), [STR_WIFI] = FB(157835), [STR_FAIL] = FB(157841),
    [STR_TIMEZONE] = FB(157854), [STR_BRIGHTNESS] = FB(157870), [STR_LED_BLINK] = FB(157880),
    [STR_ROTATE] = FB(157905), [STR_ABOUT] = FB(157930), [STR_LANGUAGE] = FB(157952),
    [STR_DONE] = FB(157965), [STR_BACK] = FB(157984), [STR_CANCEL] = FB(157997),
    [STR_DEL] = FB(158004), [STR_RUNNING] = FB(158020), [STR_ON] = FB(158039),
    [STR_OFF] = FB(158049), [STR_NTS_NO] = FB(158053), [STR_NTS_ATTEMPT] = FB(158063),
    [STR_NTS_REQUIRE] = FB(158076), [STR_WAITING_NTP] = FB(158089),
    [STR_FMT_SYNCED] = FB(158135), [STR_FMT_SYNCING] = FB(158156),
    [STR_FMT_WAITING] = FB(158198), [STR_WIFI_SETUP] = FB(158224), [STR_SCANNING] = FB(158252),
    [STR_SCAN_FAILED] = FB(158283), [STR_TAP_RETRY] = FB(158308),
    [STR_SELECT_NETWORK] = FB(158351), [STR_NO_NETWORKS] = FB(158370),
    [STR_NETWORK_LABEL] = FB(158407), [STR_ENTER_PASSWORD] = FB(158423),
    [STR_CONNECTING] = FB(158451), [STR_CONNECTING_TO] = FB(158473),
    [STR_CONNECTED] = FB(158498), [STR_CONNECTION_FAILED] = FB(158517),
    [STR_KB_SPACE] = FB(158545), [STR_KB_GO] = FB(158552), [STR_VERSION] = FB(158555),
    [STR_STATUS] = FB(158571), [STR_READ] = FB(158587), [STR_UPDATE] = FB(158600),
    [STR_RESTARTING] = FB(158610), [STR_OTA_UPDATE] = FB(158626), [STR_NTP_SERVER] = FB(158648),
    [STR_SERVER_LABEL] = FB(158667), [STR_NTP_SETTINGS] = FB(158677),
    [STR_NTP_PRESETS] = FB(158702), [STR_PRESETS] = FB(158733), [STR_BENCHMARK] = FB(158752),
    [STR_STOPPING] = FB(158768), [STR_NTP_STATS] = FB(158787), [STR_UNSYNCED] = FB(158812),
    [STR_NONE] = FB(158837), [STR_SELECT_REGION] = FB(158859), [STR_AGE_LABEL] = FB(158869),
    [STR_SYNCS_LABEL] = FB(158885), [STR_FMT_PEERS_NOSYNC] = FB(158910),
    [STR_FMT_PEERS_AGO] = FB(158978), [STR_DST] = FB(159032), [STR_NO_DST] = FB(159054),
};
const char *const weekdays_hi_shaped[7] = {
    FB(159088), FB(159098), FB(159108), FB(159115), FB(159119), FB(159123), FB(159130),
};
const char *const months_hi_shaped[12] = {
    FB(159140), FB(159150), FB(159160), FB(159170), FB(159177), FB(159184), FB(159188),
    FB(159198), FB(159208), FB(159221), FB(159234), FB(159244),
};
const char lang_name_hi_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\xA5" "\xEE" "\x82" "\xB9" "\xEE" "\x80" "\xA1");

// bn: 169 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash bn cf309888208f71a7
const display_glyph_font_t font_bn = {
    .codepoints = FB16(159258),
    .glyphs_rle = fonts_blob + 159765,
    .glyphs_off = FB16(166948),
    .glyphs_2x_rle = fonts_blob + 167288,
    .glyphs_2x_off = FB16(172132),
    .widths = fonts_blob + 159596,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_bn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(172472), [STR_WIFI] = FB(172488), [STR_FAIL] = FB(172494),
    [STR_TIMEZONE] = FB(172504), [STR_BRIGHTNESS] = FB(172526), [STR_LED_BLINK] = FB(172542),
    [STR_ROTATE] = FB(172564), [STR_ABOUT] = FB(172595), [STR_LANGUAGE] = FB(172611),
    [STR_DONE] = FB(172624), [STR_BACK] = FB(172634), [STR_CANCEL] = FB(172650),
    [STR_DEL] = FB(172666), [STR_RUNNING] = FB(172676), [STR_ON] = FB(172689),
    [STR_OFF] = FB(172699), [STR_NTS_NO] = FB(172706), [STR_NTS_ATTEMPT] = FB(172713),
    [STR_NTS_REQUIRE] = FB(172726), [STR_WAITING_NTP] = FB(172742),
    [STR_FMT_SYNCED] = FB(172782), [STR_FMT_SYNCING] = FB(172803),
    [STR_FMT_WAITING] = FB(172836), [STR_WIFI_SETUP] = FB(172862), [STR_SCANNING] = FB(172896),
    [STR_SCAN_FAILED] = FB(172918), [STR_TAP_RETRY] = FB(172943),
    [STR_SELECT_NETWORK] = FB(172998), [STR_NO_NETWORKS] = FB(173041),
    [STR_NETWORK_LABEL] = FB(173078), [STR_ENTER_PASSWORD] = FB(173106),
    [STR_CONNECTING] = FB(173143), [STR_CONNECTING_TO] = FB(173174),
    [STR_CONNECTED] = FB(173208), [STR_CONNECTION_FAILED] = FB(173227),
    [STR_KB_SPACE] = FB(173258), [STR_KB_GO] = FB(173268), [STR_VERSION] = FB(173271),
    [STR_STATUS] = FB(173290), [STR_READ] = FB(173306), [STR_UPDATE] = FB(173319),
    [STR_RESTARTING] = FB(173335), [STR_OTA_UPDATE] = FB(173360), [STR_NTP_SERVER] = FB(173388),
    [STR_SERVER_LABEL] = FB(173419), [STR_NTP_SETTINGS] = FB(173441),
    [STR_NTP_PRESETS] = FB(173469), [STR_PRESETS] = FB(173503), [STR_BENCHMARK] = FB(173525),
    [STR_STOPPING] = FB(173541), [STR_NTP_STATS] = FB(173557), [STR_UNSYNCED] = FB(173597),
    [STR_NONE] = FB(173622), [STR_SELECT_REGION] = FB(173647), [STR_AGE_LABEL] = FB(173675),
    [STR_SYNCS_LABEL] = FB(173697), [STR_FMT_PEERS_NOSYNC] = FB(173722),
    [STR_FMT_PEERS_AGO] = FB(173802), [STR_DST] = FB(173868), [STR_NO_DST] = FB(173890),
};
const char *const weekdays_bn_shaped[7] = {
    FB(173924), FB(173934), FB(173947), FB(173957), FB(173967), FB(173977), FB(173984),
};
const char *const months_bn_shaped[12] = {
    FB(173994), FB(174004), FB(174014), FB(174027), FB(174037), FB(174044), FB(174051),
    FB(174061), FB(174068), FB(174078), FB(174091), FB(174101),
};
const char lang_name_bn_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\x98" "\xEE" "\x81" "\xA5" "\xEE" "\x80" "\x8C" "\xEE" "\x80" "\x98");

// th: 162 shaped cluster glyphs (Thonburi)
// shaped-source-hash th 0031e23b06de2ba5
const display_glyph_font_t font_th = {
    .codepoints = FB16(174114),
    .glyphs_rle = fonts_blob + 174600,
    .glyphs_off = FB16(180382),
    .glyphs_2x_rle = fonts_blob + 180708,
    .glyphs_2x_off = FB16(182858),
    .widths = fonts_blob + 174438,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_th_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(183184), [STR_WIFI] = FB(183206), [STR_FAIL] = FB(183212),
    [STR_TIMEZONE] = FB(183231), [STR_BRIGHTNESS] = FB(183253), [STR_LED_BLINK] = FB(183278),
    [STR_ROTATE] = FB(183306), [STR_ABOUT] = FB(183328), [STR_LANGUAGE] = FB(183347),
    [STR_DONE] = FB(183360), [STR_BACK] = FB(183373), [STR_CANCEL] = FB(183383),
    [STR_DEL] = FB(183399), [STR_RUNNING] = FB(183406), [STR_ON] = FB(183428),
    [STR_OFF] = FB(183438), [STR_NTS_NO] = FB(183445), [STR_NTS_ATTEMPT] = FB(183452),
    [STR_NTS_REQUIRE] = FB(183462), [STR_WAITING_NTP] = FB(183475),
    [STR_FMT_SYNCED] = FB(183503), [STR_FMT_SYNCING] = FB(183530),
    [STR_FMT_WAITING] = FB(183557), [STR_WIFI_SETUP] = FB(183574), [STR_SCANNING] = FB(183605),
    [STR_SCAN_FAILED] = FB(183636), [STR_TAP_RETRY] = FB(183667),
    [STR_SELECT_NETWORK] = FB(183704), [STR_NO_NETWORKS] = FB(183738),
    [STR_NETWORK_LABEL] = FB(183772), [STR_ENTER_PASSWORD] = FB(183797),
    [STR_CONNECTING] = FB(183822), [STR_CONNECTING_TO] = FB(183850),
    [STR_CONNECTED] = FB(183875), [STR_CONNECTION_FAILED] = FB(183906),
    [STR_KB_SPACE] = FB(183943), [STR_KB_GO] = FB(183965), [STR_VERSION] = FB(183968),
    [STR_STATUS] = FB(183990), [STR_READ] = FB(184009), [STR_UPDATE] = FB(184022),
    [STR_RESTARTING] = FB(184038), [STR_OTA_UPDATE] = FB(184066), [STR_NTP_SERVER] = FB(184094),
    [STR_SERVER_LABEL] = FB(184131), [STR_NTP_SETTINGS] = FB(184159),
    [STR_NTP_PRESETS] = FB(184184), [STR_PRESETS] = FB(184215), [STR_BENCHMARK] = FB(184234),
    [STR_STOPPING] = FB(184250), [STR_NTP_STATS] = FB(184269), [STR_UNSYNCED] = FB(184291),
    [STR_NONE] = FB(184307), [STR_SELECT_REGION] = FB(184317), [STR_AGE_LABEL] = FB(184345),
    [STR_SYNCS_LABEL] = FB(184367), [STR_FMT_PEERS_NOSYNC] = FB(184389),
    [STR_FMT_PEERS_AGO] = FB(184454), [STR_DST] = FB(184517), [STR_NO_DST] = FB(184548),
};
const char *const weekdays_th_shaped[7] = {
    FB(184588), FB(184598), FB(184605), FB(184612), FB(184619), FB(184629), FB(184636),
};
const char *const months_th_shaped[12] = {
    FB(184643), FB(184656), FB(184669), FB(184682), FB(184698), FB(184711), FB(184724),
    FB(184737), FB(184750), FB(184763), FB(184776), FB(184789),
};
const char lang_name_th_shaped[] = ("\xEE" "\x80" "\xB9" "\xEE" "\x82" "\xA1" "\xEE" "\x82" "\x9E");

// ur: 195 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ur e35c9ea86d6afe82
const display_glyph_font_t font_ur = {
    .codepoints = FB16(184802),
    .glyphs_rle = fonts_blob + 185387,
    .glyphs_off = FB16(192388),
    .glyphs_2x_rle = fonts_blob + 192780,
    .glyphs_2x_off = FB16(196954),
    .widths = fonts_blob + 185192,
    .count = 195,
    .glyph_width = 16,
};
const char *const lang_ur_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(197346), [STR_WIFI] = FB(197368), [STR_FAIL] = FB(197374),
    [STR_TIMEZONE] = FB(197390), [STR_BRIGHTNESS] = FB(197415), [STR_LED_BLINK] = FB(197425),
    [STR_ROTATE] = FB(197450), [STR_ABOUT] = FB(197484), [STR_LANGUAGE] = FB(197500),
    [STR_DONE] = FB(197513), [STR_BACK] = FB(197532), [STR_CANCEL] = FB(197545),
    [STR_DEL] = FB(197561), [STR_RUNNING] = FB(197580), [STR_ON] = FB(197608),
    [STR_OFF] = FB(197615), [STR_NTS_NO] = FB(197622), [STR_NTS_ATTEMPT] = FB(197635),
    [STR_NTS_REQUIRE] = FB(197648), [STR_WAITING_NTP] = FB(197661),
    [STR_FMT_SYNCED] = FB(197710), [STR_FMT_SYNCING] = FB(197740),
    [STR_FMT_WAITING] = FB(197773), [STR_WIFI_SETUP] = FB(197802), [STR_SCANNING] = FB(197839),
    [STR_SCAN_FAILED] = FB(197873), [STR_TAP_RETRY] = FB(197901),
    [STR_SELECT_NETWORK] = FB(197989), [STR_NO_NETWORKS] = FB(198026),
    [STR_NETWORK_LABEL] = FB(198078), [STR_ENTER_PASSWORD] = FB(198103),
    [STR_CONNECTING] = FB(198152), [STR_CONNECTING_TO] = FB(198198),
    [STR_CONNECTED] = FB(198247), [STR_CONNECTION_FAILED] = FB(198266),
    [STR_KB_SPACE] = FB(198300), [STR_KB_GO] = FB(198325), [STR_VERSION] = FB(198328),
    [STR_STATUS] = FB(198344), [STR_READ] = FB(198360), [STR_UPDATE] = FB(198376),
    [STR_RESTARTING] = FB(198395), [STR_OTA_UPDATE] = FB(198429), [STR_NTP_SERVER] = FB(198460),
    [STR_SERVER_LABEL] = FB(198485), [STR_NTP_SETTINGS] = FB(198501),
    [STR_NTP_PRESETS] = FB(198535), [STR_PRESETS] = FB(198569), [STR_BENCHMARK] = FB(198591),
    [STR_STOPPING] = FB(198604), [STR_NTP_STATS] = FB(198632), [STR_UNSYNCED] = FB(198681),
    [STR_NONE] = FB(198715), [STR_SELECT_REGION] = FB(198740), [STR_AGE_LABEL] = FB(198765),
    [STR_SYNCS_LABEL] = FB(198787), [STR_FMT_PEERS_NOSYNC] = FB(198809),
    [STR_FMT_PEERS_AGO] = FB(198895), [STR_DST] = FB(198958), [STR_NO_DST] = FB(198989),
};
const char *const weekdays_ur_shaped[7] = {
    FB(199035), FB(199051), FB(199061), FB(199074), FB(199084), FB(199103), FB(199116),
};
const char *const months_ur_shaped[12] = {
    FB(199129), FB(199145), FB(199161), FB(199174), FB(199190), FB(199200), FB(199210),
    FB(199226), FB(199239), FB(199255), FB(199274), FB(199290),
};
const char lang_name_ur_shaped[] = ("\xEE" "\x80" "\x8B" "\xEE" "\x83" "\x82" "\xEE" "\x81" "\x84" "\xEE" "\x81" "\x88");

// mr: 179 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash mr 0004a1284112fffe
const display_glyph_font_t font_mr = {
    .codepoints = FB16(199306),
    .glyphs_rle = fonts_blob + 199843,
    .glyphs_off = FB16(207980),
    .glyphs_2x_rle = fonts_blob + 208340,
    .glyphs_2x_off = FB16(213032),
    .widths = fonts_blob + 199664,
    .count = 179,
    .glyph_width = 16,
};
const char *const lang_mr_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(213392), [STR_WIFI] = FB(213405), [STR_FAIL] = FB(213411),
    [STR_TIMEZONE] = FB(213427), [STR_BRIGHTNESS] = FB(213437), [STR_LED_BLINK] = FB(213447),
    [STR_ROTATE] = FB(213472), [STR_ABOUT] = FB(213500), [STR_LANGUAGE] = FB(213519),
    [STR_DONE] = FB(213532), [STR_BACK] = FB(213542), [STR_CANCEL] = FB(213552),
    [STR_DEL] = FB(213559), [STR_RUNNING] = FB(213572), [STR_ON] = FB(213585),
    [STR_OFF] = FB(213595), [STR_NTS_NO] = FB(213599), [STR_NTS_ATTEMPT] = FB(213612),
    [STR_NTS_REQUIRE] = FB(213622), [STR_WAITING_NTP] = FB(213635),
    [STR_FMT_SYNCED] = FB(213681), [STR_FMT_SYNCING] = FB(213702),
    [STR_FMT_WAITING] = FB(213744), [STR_WIFI_SETUP] = FB(213770), [STR_SCANNING] = FB(213798),
    [STR_SCAN_FAILED] = FB(213829), [STR_TAP_RETRY] = FB(213857),
    [STR_SELECT_NETWORK] = FB(213915), [STR_NO_NETWORKS] = FB(213946),
    [STR_NETWORK_LABEL] = FB(213974), [STR_ENTER_PASSWORD] = FB(213990),
    [STR_CONNECTING] = FB(214018), [STR_CONNECTING_TO] = FB(214040),
    [STR_CONNECTED] = FB(214065), [STR_CONNECTION_FAILED] = FB(214078),
    [STR_KB_SPACE] = FB(214109), [STR_KB_GO] = FB(214116), [STR_VERSION] = FB(214119),
    [STR_STATUS] = FB(214132), [STR_READ] = FB(214148), [STR_UPDATE] = FB(214161),
    [STR_RESTARTING] = FB(214171), [STR_OTA_UPDATE] = FB(214184), [STR_NTP_SERVER] = FB(214206),
    [STR_SERVER_LABEL] = FB(214228), [STR_NTP_SETTINGS] = FB(214241),
    [STR_NTP_PRESETS] = FB(214266), [STR_PRESETS] = FB(214297), [STR_BENCHMARK] = FB(214316),
    [STR_STOPPING] = FB(214332), [STR_NTP_STATS] = FB(214351), [STR_UNSYNCED] = FB(214382),
    [STR_NONE] = FB(214410), [STR_SELECT_REGION] = FB(214438), [STR_AGE_LABEL] = FB(214466),
    [STR_SYNCS_LABEL] = FB(214485), [STR_FMT_PEERS_NOSYNC] = FB(214510),
    [STR_FMT_PEERS_AGO] = FB(214584), [STR_DST] = FB(214641), [STR_NO_DST] = FB(214663),
};
const char *const weekdays_mr_shaped[7] = {
    FB(214700), FB(214710), FB(214720), FB(214727), FB(214731), FB(214735), FB(214742),
};
const char *const months_mr_shaped[12] = {
    FB(214752), FB(214762), FB(214772), FB(214782), FB(214792), FB(214796), FB(214800),
    FB(214807), FB(214814), FB(214821), FB(214831), FB(214841),
};
const char lang_name_mr_shaped[] = ("\xEE" "\x80" "\x9D" "\xEE" "\x80" "\x97" "\xEE" "\x80" "\x9E" "\xEE" "\x82" "\xB2" "\xEE" "\x80" "\xB4");

// ta: 162 shaped cluster glyphs (Tamil Sangam MN)
// shaped-source-hash ta f878b563e71942ef
const display_glyph_font_t font_ta = {
    .codepoints = FB16(214852),
    .glyphs_rle = fonts_blob + 215338,
    .glyphs_off = FB16(222808),
    .glyphs_2x_rle = fonts_blob + 223134,
    .glyphs_2x_off = FB16(228426),
    .widths = fonts_blob + 215176,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_ta_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(228752), [STR_WIFI] = FB(228774), [STR_FAIL] = FB(228780),
    [STR_TIMEZONE] = FB(228796), [STR_BRIGHTNESS] = FB(228824), [STR_LED_BLINK] = FB(228837),
    [STR_ROTATE] = FB(228862), [STR_ABOUT] = FB(228887), [STR_LANGUAGE] = FB(228897),
    [STR_DONE] = FB(228910), [STR_BACK] = FB(228926), [STR_CANCEL] = FB(228933),
    [STR_DEL] = FB(228943), [STR_RUNNING] = FB(228953), [STR_ON] = FB(228975),
    [STR_OFF] = FB(228988), [STR_NTS_NO] = FB(228998), [STR_NTS_ATTEMPT] = FB(229011),
    [STR_NTS_REQUIRE] = FB(229024), [STR_WAITING_NTP] = FB(229043),
    [STR_FMT_SYNCED] = FB(229086), [STR_FMT_SYNCING] = FB(229113),
    [STR_FMT_WAITING] = FB(229146), [STR_WIFI_SETUP] = FB(229178), [STR_SCANNING] = FB(229212),
    [STR_SCAN_FAILED] = FB(229240), [STR_TAP_RETRY] = FB(229271),
    [STR_SELECT_NETWORK] = FB(229314), [STR_NO_NETWORKS] = FB(229354),
    [STR_NETWORK_LABEL] = FB(229394), [STR_ENTER_PASSWORD] = FB(229422),
    [STR_CONNECTING] = FB(229468), [STR_CONNECTING_TO] = FB(229490),
    [STR_CONNECTED] = FB(229515), [STR_CONNECTION_FAILED] = FB(229537),
    [STR_KB_SPACE] = FB(229571), [STR_KB_GO] = FB(229590), [STR_VERSION] = FB(229593),
    [STR_STATUS] = FB(229609), [STR_READ] = FB(229622), [STR_UPDATE] = FB(229641),
    [STR_RESTARTING] = FB(229654), [STR_OTA_UPDATE] = FB(229682), [STR_NTP_SERVER] = FB(229713),
    [STR_SERVER_LABEL] = FB(229747), [STR_NTP_SETTINGS] = FB(229772),
    [STR_NTP_PRESETS] = FB(229806), [STR_PRESETS] = FB(229843), [STR_BENCHMARK] = FB(229868),
    [STR_STOPPING] = FB(229887), [STR_NTP_STATS] = FB(229909), [STR_UNSYNCED] = FB(229943),
    [STR_NONE] = FB(229968), [STR_SELECT_REGION] = FB(229987), [STR_AGE_LABEL] = FB(230012),
    [STR_SYNCS_LABEL] = FB(230034), [STR_FMT_PEERS_NOSYNC] = FB(230056),
    [STR_FMT_PEERS_AGO] = FB(230130), [STR_DST] = FB(230187), [STR_NO_DST] = FB(230218),
};
const char *const weekdays_ta_shaped[7] = {
    FB(230264), FB(230277), FB(230287), FB(230300), FB(230310), FB(230323), FB(230336),
};
const char *const months_ta_shaped[12] = {
    FB(230343), FB(230353), FB(230363), FB(230376), FB(230386), FB(230393), FB(230400),
    FB(230410), FB(230420), FB(230433), FB(230443), FB(230453),
};
const char lang_name_ta_shaped[] = ("\xEE" "\x81" "\x9C" "\xEE" "\x80" "\x9B" "\xEE" "\x82" "\xA1");

// te: 217 shaped cluster glyphs (Kohinoor Telugu)
// shaped-source-hash te e2a06a76c473ea8b
const display_glyph_font_t font_te = {
    .codepoints = FB16(230464),
    .glyphs_rle = fonts_blob + 231115,
    .glyphs_off = FB16(240418),
    .glyphs_2x_rle = fonts_blob + 240854,
    .glyphs_2x_off = FB16(246452),
    .widths = fonts_blob + 230898,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_te_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(246888), [STR_WIFI] = FB(246907), [STR_FAIL] = FB(246913),
    [STR_TIMEZONE] = FB(246926), [STR_BRIGHTNESS] = FB(246954), [STR_LED_BLINK] = FB(246970),
    [STR_ROTATE] = FB(246992), [STR_ABOUT] = FB(247014), [STR_LANGUAGE] = FB(247027),
    [STR_DONE] = FB(247034), [STR_BACK] = FB(247044), [STR_CANCEL] = FB(247057),
    [STR_DEL] = FB(247067), [STR_RUNNING] = FB(247083), [STR_ON] = FB(247102),
    [STR_OFF] = FB(247109), [STR_NTS_NO] = FB(247116), [STR_NTS_ATTEMPT] = FB(247123),
    [STR_NTS_REQUIRE] = FB(247142), [STR_WAITING_NTP] = FB(247161),
    [STR_FMT_SYNCED] = FB(247201), [STR_FMT_SYNCING] = FB(247219),
    [STR_FMT_WAITING] = FB(247255), [STR_WIFI_SETUP] = FB(247272), [STR_SCANNING] = FB(247300),
    [STR_SCAN_FAILED] = FB(247328), [STR_TAP_RETRY] = FB(247353),
    [STR_SELECT_NETWORK] = FB(247405), [STR_NO_NETWORKS] = FB(247439),
    [STR_NETWORK_LABEL] = FB(247461), [STR_ENTER_PASSWORD] = FB(247477),
    [STR_CONNECTING] = FB(247502), [STR_CONNECTING_TO] = FB(247533),
    [STR_CONNECTED] = FB(247567), [STR_CONNECTION_FAILED] = FB(247598),
    [STR_KB_SPACE] = FB(247629), [STR_KB_GO] = FB(247636), [STR_VERSION] = FB(247639),
    [STR_STATUS] = FB(247655), [STR_READ] = FB(247668), [STR_UPDATE] = FB(247687),
    [STR_RESTARTING] = FB(247703), [STR_OTA_UPDATE] = FB(247731), [STR_NTP_SERVER] = FB(247759),
    [STR_SERVER_LABEL] = FB(247784), [STR_NTP_SETTINGS] = FB(247800),
    [STR_NTP_PRESETS] = FB(247831), [STR_PRESETS] = FB(247859), [STR_BENCHMARK] = FB(247875),
    [STR_STOPPING] = FB(247888), [STR_NTP_STATS] = FB(247904), [STR_UNSYNCED] = FB(247932),
    [STR_NONE] = FB(247951), [STR_SELECT_REGION] = FB(247967), [STR_AGE_LABEL] = FB(248004),
    [STR_SYNCS_LABEL] = FB(248026), [STR_FMT_PEERS_NOSYNC] = FB(248048),
    [STR_FMT_PEERS_AGO] = FB(248116), [STR_DST] = FB(248179), [STR_NO_DST] = FB(248204),
};
const char *const weekdays_te_shaped[7] = {
    FB(248238), FB(248245), FB(248252), FB(248265), FB(248272), FB(248279), FB(248289),
};
const char *const months_te_shaped[12] = {
    FB(248296), FB(248303), FB(248313), FB(248323), FB(248333), FB(248337), FB(248344),
    FB(248351), FB(248358), FB(248371), FB(248381), FB(248391),
};
const char lang_name_te_shaped[] = ("\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98" "\xEE" "\x80" "\x9F");

// pa: 166 shaped cluster glyphs (Gurmukhi Sangam MN)
// shaped-source-hash pa 2d3a9b02f345682a
const display_glyph_font_t font_pa = {
    .codepoints = FB16(248402),
    .glyphs_rle = fonts_blob + 248900,
    .glyphs_off = FB16(257342),
    .glyphs_2x_rle = fonts_blob + 257676,
    .glyphs_2x_off = FB16(262114),
    .widths = fonts_blob + 248734,
    .count = 166,
    .glyph_width = 16,
};
const char *const lang_pa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(262448), [STR_WIFI] = FB(262458), [STR_FAIL] = FB(262464),
    [STR_TIMEZONE] = FB(262477), [STR_BRIGHTNESS] = FB(262496), [STR_LED_BLINK] = FB(262506),
    [STR_ROTATE] = FB(262528), [STR_ABOUT] = FB(262550), [STR_LANGUAGE] = FB(262560),
    [STR_DONE] = FB(262573), [STR_BACK] = FB(262586), [STR_CANCEL] = FB(262593),
    [STR_DEL] = FB(262597), [STR_RUNNING] = FB(262613), [STR_ON] = FB(262632),
    [STR_OFF] = FB(262642), [STR_NTS_NO] = FB(262646), [STR_NTS_ATTEMPT] = FB(262656),
    [STR_NTS_REQUIRE] = FB(262666), [STR_WAITING_NTP] = FB(262682),
    [STR_FMT_SYNCED] = FB(262713), [STR_FMT_SYNCING] = FB(262728),
    [STR_FMT_WAITING] = FB(262761), [STR_WIFI_SETUP] = FB(262784), [STR_SCANNING] = FB(262809),
    [STR_SCAN_FAILED] = FB(262837), [STR_TAP_RETRY] = FB(262856),
    [STR_SELECT_NETWORK] = FB(262905), [STR_NO_NETWORKS] = FB(262927),
    [STR_NETWORK_LABEL] = FB(262964), [STR_ENTER_PASSWORD] = FB(262983),
    [STR_CONNECTING] = FB(263011), [STR_CONNECTING_TO] = FB(263030),
    [STR_CONNECTED] = FB(263052), [STR_CONNECTION_FAILED] = FB(263071),
    [STR_KB_SPACE] = FB(263099), [STR_KB_GO] = FB(263106), [STR_VERSION] = FB(263109),
    [STR_STATUS] = FB(263125), [STR_READ] = FB(263144), [STR_UPDATE] = FB(263160),
    [STR_RESTARTING] = FB(263167), [STR_OTA_UPDATE] = FB(263177), [STR_NTP_SERVER] = FB(263196),
    [STR_SERVER_LABEL] = FB(263221), [STR_NTP_SETTINGS] = FB(263237),
    [STR_NTP_PRESETS] = FB(263256), [STR_PRESETS] = FB(263278), [STR_BENCHMARK] = FB(263291),
    [STR_STOPPING] = FB(263301), [STR_NTP_STATS] = FB(263320), [STR_UNSYNCED] = FB(263339),
    [STR_NONE] = FB(263358), [STR_SELECT_REGION] = FB(263374), [STR_AGE_LABEL] = FB(263387),
    [STR_SYNCS_LABEL] = FB(263409), [STR_FMT_PEERS_NOSYNC] = FB(263428),
    [STR_FMT_PEERS_AGO] = FB(263496), [STR_DST] = FB(263562), [STR_NO_DST] = FB(263587),
};
const char *const weekdays_pa_shaped[7] = {
    FB(263624), FB(263631), FB(263635), FB(263642), FB(263646), FB(263656), FB(263663),
};
const char *const months_pa_shaped[12] = {
    FB(263673), FB(263680), FB(263687), FB(263700), FB(263707), FB(263714), FB(263718),
    FB(263725), FB(263732), FB(263739), FB(263749), FB(263756),
};
const char lang_name_pa_shaped[] = ("\xEE" "\x82" "\xA3" "\xEE" "\x80" "\x94" "\xEE" "\x82" "\xA4" "\xEE" "\x82" "\xA5");

// gu: 186 shaped cluster glyphs (Kohinoor Gujarati)
// shaped-source-hash gu fbd4bb74daaf15bf
const display_glyph_font_t font_gu = {
    .codepoints = FB16(263764),
    .glyphs_rle = fonts_blob + 264322,
    .glyphs_off = FB16(272668),
    .glyphs_2x_rle = fonts_blob + 273042,
    .glyphs_2x_off = FB16(278026),
    .widths = fonts_blob + 264136,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_gu_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(278400), [STR_WIFI] = FB(278416), [STR_FAIL] = FB(278422),
    [STR_TIMEZONE] = FB(278435), [STR_BRIGHTNESS] = FB(278454), [STR_LED_BLINK] = FB(278458),
    [STR_ROTATE] = FB(278489), [STR_ABOUT] = FB(278514), [STR_LANGUAGE] = FB(278524),
    [STR_DONE] = FB(278537), [STR_BACK] = FB(278553), [STR_CANCEL] = FB(278566),
    [STR_DEL] = FB(278573), [STR_RUNNING] = FB(278586), [STR_ON] = FB(278608),
    [STR_OFF] = FB(278618), [STR_NTS_NO] = FB(278625), [STR_NTS_ATTEMPT] = FB(278632),
    [STR_NTS_REQUIRE] = FB(278645), [STR_WAITING_NTP] = FB(278667),
    [STR_FMT_SYNCED] = FB(278707), [STR_FMT_SYNCING] = FB(278728),
    [STR_FMT_WAITING] = FB(278764), [STR_WIFI_SETUP] = FB(278784), [STR_SCANNING] = FB(278812),
    [STR_SCAN_FAILED] = FB(278837), [STR_TAP_RETRY] = FB(278859),
    [STR_SELECT_NETWORK] = FB(278923), [STR_NO_NETWORKS] = FB(278957),
    [STR_NETWORK_LABEL] = FB(278991), [STR_ENTER_PASSWORD] = FB(279007),
    [STR_CONNECTING] = FB(279053), [STR_CONNECTING_TO] = FB(279072),
    [STR_CONNECTED] = FB(279091), [STR_CONNECTION_FAILED] = FB(279101),
    [STR_KB_SPACE] = FB(279126), [STR_KB_GO] = FB(279133), [STR_VERSION] = FB(279136),
    [STR_STATUS] = FB(279149), [STR_READ] = FB(279165), [STR_UPDATE] = FB(279175),
    [STR_RESTARTING] = FB(279191), [STR_OTA_UPDATE] = FB(279210), [STR_NTP_SERVER] = FB(279238),
    [STR_SERVER_LABEL] = FB(279257), [STR_NTP_SETTINGS] = FB(279267),
    [STR_NTP_PRESETS] = FB(279295), [STR_PRESETS] = FB(279323), [STR_BENCHMARK] = FB(279339),
    [STR_STOPPING] = FB(279355), [STR_NTP_STATS] = FB(279377), [STR_UNSYNCED] = FB(279402),
    [STR_NONE] = FB(279427), [STR_SELECT_REGION] = FB(279449), [STR_AGE_LABEL] = FB(279483),
    [STR_SYNCS_LABEL] = FB(279508), [STR_FMT_PEERS_NOSYNC] = FB(279533),
    [STR_FMT_PEERS_AGO] = FB(279601), [STR_DST] = FB(279661), [STR_NO_DST] = FB(279683),
};
const char *const weekdays_gu_shaped[7] = {
    FB(279717), FB(279727), FB(279734), FB(279741), FB(279748), FB(279752), FB(279756),
};
const char *const months_gu_shaped[12] = {
    FB(279766), FB(279773), FB(279783), FB(279793), FB(279803), FB(279807), FB(279817),
    FB(279833), FB(279843), FB(279853), FB(279863), FB(279870),
};
const char lang_name_gu_shaped[] = ("\xEE" "\x82" "\xB9" "\xEE" "\x80" "\x95" "\xEE" "\x80" "\x94" "\xEE" "\x80" "\xBE" "\xEE" "\x82" "\x95");

// kn: 217 shaped cluster glyphs (Kannada Sangam MN)
// shaped-source-hash kn 31b46ecce4f64786
const display_glyph_font_t font_kn = {
    .codepoints = FB16(279880),
    .glyphs_rle = fonts_blob + 280531,
    .glyphs_off = FB16(292296),
    .glyphs_2x_rle = fonts_blob + 292732,
    .glyphs_2x_off = FB16(299726),
    .widths = fonts_blob + 280314,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_kn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(300162), [STR_WIFI] = FB(300184), [STR_FAIL] = FB(300190),
    [STR_TIMEZONE] = FB(300200), [STR_BRIGHTNESS] = FB(300222), [STR_LED_BLINK] = FB(300238),
    [STR_ROTATE] = FB(300266), [STR_ABOUT] = FB(300291), [STR_LANGUAGE] = FB(300307),
    [STR_DONE] = FB(300317), [STR_BACK] = FB(300330), [STR_CANCEL] = FB(300340),
    [STR_DEL] = FB(300350), [STR_RUNNING] = FB(300360), [STR_ON] = FB(300373),
    [STR_OFF] = FB(300380), [STR_NTS_NO] = FB(300387), [STR_NTS_ATTEMPT] = FB(300394),
    [STR_NTS_REQUIRE] = FB(300407), [STR_WAITING_NTP] = FB(300420),
    [STR_FMT_SYNCED] = FB(300466), [STR_FMT_SYNCING] = FB(300484),
    [STR_FMT_WAITING] = FB(300517), [STR_WIFI_SETUP] = FB(300543), [STR_SCANNING] = FB(300571),
    [STR_SCAN_FAILED] = FB(300602), [STR_TAP_RETRY] = FB(300636),
    [STR_SELECT_NETWORK] = FB(300670), [STR_NO_NETWORKS] = FB(300695),
    [STR_NETWORK_LABEL] = FB(300720), [STR_ENTER_PASSWORD] = FB(300739),
    [STR_CONNECTING] = FB(300776), [STR_CONNECTING_TO] = FB(300801),
    [STR_CONNECTED] = FB(300826), [STR_CONNECTION_FAILED] = FB(300854),
    [STR_KB_SPACE] = FB(300882), [STR_KB_GO] = FB(300892), [STR_VERSION] = FB(300895),
    [STR_STATUS] = FB(300908), [STR_READ] = FB(300915), [STR_UPDATE] = FB(300928),
    [STR_RESTARTING] = FB(300944), [STR_OTA_UPDATE] = FB(300972), [STR_NTP_SERVER] = FB(301000),
    [STR_SERVER_LABEL] = FB(301025), [STR_NTP_SETTINGS] = FB(301041),
    [STR_NTP_PRESETS] = FB(301075), [STR_PRESETS] = FB(301100), [STR_BENCHMARK] = FB(301113),
    [STR_STOPPING] = FB(301123), [STR_NTP_STATS] = FB(301136), [STR_UNSYNCED] = FB(301167),
    [STR_NONE] = FB(301186), [STR_SELECT_REGION] = FB(301205), [STR_AGE_LABEL] = FB(301227),
    [STR_SYNCS_LABEL] = FB(301255), [STR_FMT_PEERS_NOSYNC] = FB(301274),
    [STR_FMT_PEERS_AGO] = FB(301339), [STR_DST] = FB(301399), [STR_NO_DST] = FB(301418),
};
const char *const weekdays_kn_shaped[7] = {
    FB(301446), FB(301459), FB(301469), FB(301482), FB(301492), FB(301505), FB(301518),
};
const char *const months_kn_shaped[12] = {
    FB(301525), FB(301532), FB(301542), FB(301555), FB(301562), FB(301569), FB(301579),
    FB(301589), FB(301596), FB(301606), FB(301619), FB(301629),
};
const char lang_name_kn_shaped[] = ("\xEE" "\x80" "\xA1" "\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98");

// ml: 193 shaped cluster glyphs (Malayalam Sangam MN)
// shaped-source-hash ml 29dba5a5cd226932
const display_glyph_font_t font_ml = {
    .codepoints = FB16(301636),
    .glyphs_rle = fonts_blob + 302215,
    .glyphs_off = FB16(311358),
    .glyphs_2x_rle = fonts_blob + 311746,
    .glyphs_2x_off = FB16(319134),
    .widths = fonts_blob + 302022,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_ml_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(319522), [STR_WIFI] = FB(319550), [STR_FAIL] = FB(319556),
    [STR_TIMEZONE] = FB(319575), [STR_BRIGHTNESS] = FB(319600), [STR_LED_BLINK] = FB(319619),
    [STR_ROTATE] = FB(319644), [STR_ABOUT] = FB(319678), [STR_LANGUAGE] = FB(319694),
    [STR_DONE] = FB(319704), [STR_BACK] = FB(319723), [STR_CANCEL] = FB(319742),
    [STR_DEL] = FB(319749), [STR_RUNNING] = FB(319765), [STR_ON] = FB(319799),
    [STR_OFF] = FB(319806), [STR_NTS_NO] = FB(319813), [STR_NTS_ATTEMPT] = FB(319820),
    [STR_NTS_REQUIRE] = FB(319833), [STR_WAITING_NTP] = FB(319855),
    [STR_FMT_SYNCED] = FB(319898), [STR_FMT_SYNCING] = FB(319913),
    [STR_FMT_WAITING] = FB(319949), [STR_WIFI_SETUP] = FB(319981), [STR_SCANNING] = FB(320024),
    [STR_SCAN_FAILED] = FB(320055), [STR_TAP_RETRY] = FB(320095),
    [STR_SELECT_NETWORK] = FB(320156), [STR_NO_NETWORKS] = FB(320208),
    [STR_NETWORK_LABEL] = FB(320233), [STR_ENTER_PASSWORD] = FB(320252),
    [STR_CONNECTING] = FB(320286), [STR_CONNECTING_TO] = FB(320314),
    [STR_CONNECTED] = FB(320345), [STR_CONNECTION_FAILED] = FB(320370),
    [STR_KB_SPACE] = FB(320404), [STR_KB_GO] = FB(320417), [STR_VERSION] = FB(320420),
    [STR_STATUS] = FB(320433), [STR_READ] = FB(320446), [STR_UPDATE] = FB(320468),
    [STR_RESTARTING] = FB(320481), [STR_OTA_UPDATE] = FB(320509), [STR_NTP_SERVER] = FB(320534),
    [STR_SERVER_LABEL] = FB(320562), [STR_NTP_SETTINGS] = FB(320581),
    [STR_NTP_PRESETS] = FB(320618), [STR_PRESETS] = FB(320652), [STR_BENCHMARK] = FB(320674),
    [STR_STOPPING] = FB(320690), [STR_NTP_STATS] = FB(320712), [STR_UNSYNCED] = FB(320755),
    [STR_NONE] = FB(320771), [STR_SELECT_REGION] = FB(320790), [STR_AGE_LABEL] = FB(320845),
    [STR_SYNCS_LABEL] = FB(320873), [STR_FMT_PEERS_NOSYNC] = FB(320892),
    [STR_FMT_PEERS_AGO] = FB(320960), [STR_DST] = FB(321023), [STR_NO_DST] = FB(321051),
};
const char *const weekdays_ml_shaped[7] = {
    FB(321088), FB(321101), FB(321114), FB(321127), FB(321140), FB(321156), FB(321169),
};
const char *const months_ml_shaped[12] = {
    FB(321179), FB(321189), FB(321205), FB(321215), FB(321228), FB(321238), FB(321248),
    FB(321261), FB(321268), FB(321281), FB(321294), FB(321304),
};
const char lang_name_ml_shaped[] = ("\xEE" "\x80" "\x82" "\xEE" "\x82" "\xBF" "\xEE" "\x80" "\x90" "\xEE" "\x80" "\x8B" "\xEE" "\x83" "\x80" "\xEE" "\x81" "\x8B");

// ne: 198 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash ne d85c20cd0e9960a9
const display_glyph_font_t font_ne = {
    .codepoints = FB16(321318),
    .glyphs_rle = fonts_blob + 321912,
    .glyphs_off = FB16(330774),
    .glyphs_2x_rle = fonts_blob + 331172,
    .glyphs_2x_off = FB16(336938),
    .widths = fonts_blob + 321714,
    .count = 198,
    .glyph_width = 16,
};
const char *const lang_ne_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(337336), [STR_WIFI] = FB(337352), [STR_FAIL] = FB(337358),
    [STR_TIMEZONE] = FB(337371), [STR_BRIGHTNESS] = FB(337387), [STR_LED_BLINK] = FB(337397),
    [STR_ROTATE] = FB(337428), [STR_ABOUT] = FB(337450), [STR_LANGUAGE] = FB(337466),
    [STR_DONE] = FB(337479), [STR_BACK] = FB(337489), [STR_CANCEL] = FB(337505),
    [STR_DEL] = FB(337512), [STR_RUNNING] = FB(337522), [STR_ON] = FB(337544),
    [STR_OFF] = FB(337551), [STR_NTS_NO] = FB(337558), [STR_NTS_ATTEMPT] = FB(337571),
    [STR_NTS_REQUIRE] = FB(337584), [STR_WAITING_NTP] = FB(337603),
    [STR_FMT_SYNCED] = FB(337631), [STR_FMT_SYNCING] = FB(337652),
    [STR_FMT_WAITING] = FB(337685), [STR_WIFI_SETUP] = FB(337705), [STR_SCANNING] = FB(337733),
    [STR_SCAN_FAILED] = FB(337752), [STR_TAP_RETRY] = FB(337780),
    [STR_SELECT_NETWORK] = FB(337841), [STR_NO_NETWORKS] = FB(337872),
    [STR_NETWORK_LABEL] = FB(337897), [STR_ENTER_PASSWORD] = FB(337913),
    [STR_CONNECTING] = FB(337947), [STR_CONNECTING_TO] = FB(337972),
    [STR_CONNECTED] = FB(338000), [STR_CONNECTION_FAILED] = FB(338028),
    [STR_KB_SPACE] = FB(338056), [STR_KB_GO] = FB(338063), [STR_VERSION] = FB(338066),
    [STR_STATUS] = FB(338082), [STR_READ] = FB(338098), [STR_UPDATE] = FB(338117),
    [STR_RESTARTING] = FB(338127), [STR_OTA_UPDATE] = FB(338140), [STR_NTP_SERVER] = FB(338162),
    [STR_SERVER_LABEL] = FB(338181), [STR_NTP_SETTINGS] = FB(338191),
    [STR_NTP_PRESETS] = FB(338213), [STR_PRESETS] = FB(338244), [STR_BENCHMARK] = FB(338263),
    [STR_STOPPING] = FB(338279), [STR_NTP_STATS] = FB(338298), [STR_UNSYNCED] = FB(338329),
    [STR_NONE] = FB(338354), [STR_SELECT_REGION] = FB(338379), [STR_AGE_LABEL] = FB(338401),
    [STR_SYNCS_LABEL] = FB(338420), [STR_FMT_PEERS_NOSYNC] = FB(338445),
    [STR_FMT_PEERS_AGO] = FB(338513), [STR_DST] = FB(338567), [STR_NO_DST] = FB(338589),
};
const char *const weekdays_ne_shaped[7] = {
    FB(338623), FB(338633), FB(338643), FB(338659), FB(338663), FB(338676), FB(338683),
};
const char *const months_ne_shaped[12] = {
    FB(338693), FB(338709), FB(338725), FB(338735), FB(338748), FB(338752), FB(338756),
    FB(338769), FB(338779), FB(338789), FB(338805), FB(338821),
};
const char lang_name_ne_shaped[] = ("\xEE" "\x83" "\x85" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x88" "\xEE" "\x81" "\x9B");

// si: 158 shaped cluster glyphs (Sinhala Sangam MN)
// shaped-source-hash si 374f0817fdc7c518
const display_glyph_font_t font_si = {
    .codepoints = FB16(338838),
    .glyphs_rle = fonts_blob + 339312,
    .glyphs_off = FB16(346958),
    .glyphs_2x_rle = fonts_blob + 347276,
    .glyphs_2x_off = FB16(353452),
    .widths = fonts_blob + 339154,
    .count = 158,
    .glyph_width = 16,
};
const char *const lang_si_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(353770), [STR_WIFI] = FB(353783), [STR_FAIL] = FB(353789),
    [STR_TIMEZONE] = FB(353811), [STR_BRIGHTNESS] = FB(353842), [STR_LED_BLINK] = FB(353855),
    [STR_ROTATE] = FB(353880), [STR_ABOUT] = FB(353911), [STR_LANGUAGE] = FB(353924),
    [STR_DONE] = FB(353940), [STR_BACK] = FB(353953), [STR_CANCEL] = FB(353963),
    [STR_DEL] = FB(353979), [STR_RUNNING] = FB(353992), [STR_ON] = FB(354017),
    [STR_OFF] = FB(354027), [STR_NTS_NO] = FB(354037), [STR_NTS_ATTEMPT] = FB(354047),
    [STR_NTS_REQUIRE] = FB(354066), [STR_WAITING_NTP] = FB(354085),
    [STR_FMT_SYNCED] = FB(354149), [STR_FMT_SYNCING] = FB(354173),
    [STR_FMT_WAITING] = FB(354212), [STR_WIFI_SETUP] = FB(354232), [STR_SCANNING] = FB(354263),
    [STR_SCAN_FAILED] = FB(354291), [STR_TAP_RETRY] = FB(354328),
    [STR_SELECT_NETWORK] = FB(354389), [STR_NO_NETWORKS] = FB(354423),
    [STR_NETWORK_LABEL] = FB(354454), [STR_ENTER_PASSWORD] = FB(354470),
    [STR_CONNECTING] = FB(354510), [STR_CONNECTING_TO] = FB(354541),
    [STR_CONNECTED] = FB(354575), [STR_CONNECTION_FAILED] = FB(354597),
    [STR_KB_SPACE] = FB(354646), [STR_KB_GO] = FB(354653), [STR_VERSION] = FB(354656),
    [STR_STATUS] = FB(354675), [STR_READ] = FB(354694), [STR_UPDATE] = FB(354704),
    [STR_RESTARTING] = FB(354729), [STR_OTA_UPDATE] = FB(354760), [STR_NTP_SERVER] = FB(354797),
    [STR_SERVER_LABEL] = FB(354837), [STR_NTP_SETTINGS] = FB(354868),
    [STR_NTP_PRESETS] = FB(354893), [STR_PRESETS] = FB(354921), [STR_BENCHMARK] = FB(354937),
    [STR_STOPPING] = FB(354956), [STR_NTP_STATS] = FB(354972), [STR_UNSYNCED] = FB(355012),
    [STR_NONE] = FB(355040), [STR_SELECT_REGION] = FB(355065), [STR_AGE_LABEL] = FB(355102),
    [STR_SYNCS_LABEL] = FB(355124), [STR_FMT_PEERS_NOSYNC] = FB(355146),
    [STR_FMT_PEERS_AGO] = FB(355217), [STR_DST] = FB(355277), [STR_NO_DST] = FB(355311),
};
const char *const weekdays_si_shaped[7] = {
    FB(355357), FB(355370), FB(355383), FB(355393), FB(355409), FB(355419), FB(355426),
};
const char *const months_si_shaped[12] = {
    FB(355436), FB(355443), FB(355453), FB(355463), FB(355473), FB(355483), FB(355487),
    FB(355491), FB(355504), FB(355514), FB(355521), FB(355537),
};
const char lang_name_si_shaped[] = ("\xEE" "\x82" "\x8A" "\xEE" "\x80" "\xAF" "\xEE" "\x80" "\xBA" "\xEE" "\x80" "\x8F");

// km: 193 shaped cluster glyphs (Khmer Sangam MN)
// shaped-source-hash km 001d4323092b620d
const display_glyph_font_t font_km = {
    .codepoints = FB16(355550),
    .glyphs_rle = fonts_blob + 356129,
    .glyphs_off = FB16(365570),
    .glyphs_2x_rle = fonts_blob + 365958,
    .glyphs_2x_off = FB16(370880),
    .widths = fonts_blob + 355936,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_km_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(371268), [STR_WIFI] = FB(371284), [STR_FAIL] = FB(371290),
    [STR_TIMEZONE] = FB(371300), [STR_BRIGHTNESS] = FB(371313), [STR_LED_BLINK] = FB(371320),
    [STR_ROTATE] = FB(371342), [STR_ABOUT] = FB(371361), [STR_LANGUAGE] = FB(371365),
    [STR_DONE] = FB(371372), [STR_BACK] = FB(371382), [STR_CANCEL] = FB(371401),
    [STR_DEL] = FB(371417), [STR_RUNNING] = FB(371421), [STR_ON] = FB(371440),
    [STR_OFF] = FB(371447), [STR_NTS_NO] = FB(371451), [STR_NTS_ATTEMPT] = FB(371458),
    [STR_NTS_REQUIRE] = FB(371471), [STR_WAITING_NTP] = FB(371481),
    [STR_FMT_SYNCED] = FB(371509), [STR_FMT_SYNCING] = FB(371530),
    [STR_FMT_WAITING] = FB(371557), [STR_WIFI_SETUP] = FB(371574), [STR_SCANNING] = FB(371605),
    [STR_SCAN_FAILED] = FB(371633), [STR_TAP_RETRY] = FB(371655),
    [STR_SELECT_NETWORK] = FB(371692), [STR_NO_NETWORKS] = FB(371717),
    [STR_NETWORK_LABEL] = FB(371730), [STR_ENTER_PASSWORD] = FB(371743),
    [STR_CONNECTING] = FB(371768), [STR_CONNECTING_TO] = FB(371778),
    [STR_CONNECTED] = FB(371791), [STR_CONNECTION_FAILED] = FB(371801),
    [STR_KB_SPACE] = FB(371820), [STR_KB_GO] = FB(371830), [STR_VERSION] = FB(371833),
    [STR_STATUS] = FB(371843), [STR_READ] = FB(371859), [STR_UPDATE] = FB(371875),
    [STR_RESTARTING] = FB(371891), [STR_OTA_UPDATE] = FB(371910), [STR_NTP_SERVER] = FB(371938),
    [STR_SERVER_LABEL] = FB(371963), [STR_NTP_SETTINGS] = FB(371979),
    [STR_NTP_PRESETS] = FB(372004), [STR_PRESETS] = FB(372026), [STR_BENCHMARK] = FB(372039),
    [STR_STOPPING] = FB(372055), [STR_NTP_STATS] = FB(372068), [STR_UNSYNCED] = FB(372084),
    [STR_NONE] = FB(372100), [STR_SELECT_REGION] = FB(372104), [STR_AGE_LABEL] = FB(372126),
    [STR_SYNCS_LABEL] = FB(372142), [STR_FMT_PEERS_NOSYNC] = FB(372158),
    [STR_FMT_PEERS_AGO] = FB(372205), [STR_DST] = FB(372250), [STR_NO_DST] = FB(372269),
};
const char *const weekdays_km_shaped[7] = {
    FB(372291), FB(372301), FB(372308), FB(372315), FB(372319), FB(372329), FB(372336),
};
const char *const months_km_shaped[12] = {
    FB(372346), FB(372356), FB(372360), FB(372364), FB(372374), FB(372384), FB(372391),
    FB(372398), FB(372405), FB(372412), FB(372419), FB(372426),
};
const char lang_name_km_shaped[] = ("\xEE" "\x80" "\x88" "\xEE" "\x83" "\x80");

// lo: 169 shaped cluster glyphs (Lao Sangam MN)
// shaped-source-hash lo 3d0778a6b7811038
const display_glyph_font_t font_lo = {
    .codepoints = FB16(372430),
    .glyphs_rle = fonts_blob + 372937,
    .glyphs_off = FB16(381794),
    .glyphs_2x_rle = fonts_blob + 382134,
    .glyphs_2x_off = FB16(386798),
    .widths = fonts_blob + 372768,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_lo_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(387138), [STR_WIFI] = FB(387154), [STR_FAIL] = FB(387160),
    [STR_TIMEZONE] = FB(387173), [STR_BRIGHTNESS] = FB(387195), [STR_LED_BLINK] = FB(387214),
    [STR_ROTATE] = FB(387236), [STR_ABOUT] = FB(387255), [STR_LANGUAGE] = FB(387265),
    [STR_DONE] = FB(387278), [STR_BACK] = FB(387285), [STR_CANCEL] = FB(387292),
    [STR_DEL] = FB(387302), [STR_RUNNING] = FB(387306), [STR_ON] = FB(387328),
    [STR_OFF] = FB(387335), [STR_NTS_NO] = FB(387339), [STR_NTS_ATTEMPT] = FB(387343),
    [STR_NTS_REQUIRE] = FB(387353), [STR_WAITING_NTP] = FB(387360),
    [STR_FMT_SYNCED] = FB(387388), [STR_FMT_SYNCING] = FB(387406),
    [STR_FMT_WAITING] = FB(387424), [STR_WIFI_SETUP] = FB(387441), [STR_SCANNING] = FB(387466),
    [STR_SCAN_FAILED] = FB(387491), [STR_TAP_RETRY] = FB(387519),
    [STR_SELECT_NETWORK] = FB(387550), [STR_NO_NETWORKS] = FB(387572),
    [STR_NETWORK_LABEL] = FB(387591), [STR_ENTER_PASSWORD] = FB(387607),
    [STR_CONNECTING] = FB(387626), [STR_CONNECTING_TO] = FB(387645),
    [STR_CONNECTED] = FB(387661), [STR_CONNECTION_FAILED] = FB(387680),
    [STR_KB_SPACE] = FB(387705), [STR_KB_GO] = FB(387712), [STR_VERSION] = FB(387715),
    [STR_STATUS] = FB(387728), [STR_READ] = FB(387750), [STR_UPDATE] = FB(387760),
    [STR_RESTARTING] = FB(387773), [STR_OTA_UPDATE] = FB(387792), [STR_NTP_SERVER] = FB(387817),
    [STR_SERVER_LABEL] = FB(387839), [STR_NTP_SETTINGS] = FB(387852),
    [STR_NTP_PRESETS] = FB(387871), [STR_PRESETS] = FB(387905), [STR_BENCHMARK] = FB(387927),
    [STR_STOPPING] = FB(387940), [STR_NTP_STATS] = FB(387950), [STR_UNSYNCED] = FB(387972),
    [STR_NONE] = FB(387979), [STR_SELECT_REGION] = FB(387983), [STR_AGE_LABEL] = FB(388002),
    [STR_SYNCS_LABEL] = FB(388021), [STR_FMT_PEERS_NOSYNC] = FB(388037),
    [STR_FMT_PEERS_AGO] = FB(388090), [STR_DST] = FB(388144), [STR_NO_DST] = FB(388172),
};
const char *const weekdays_lo_shaped[7] = {
    FB(388203), FB(388213), FB(388217), FB(388230), FB(388234), FB(388244), FB(388248),
};
const char *const months_lo_shaped[12] = {
    FB(388255), FB(388268), FB(388281), FB(388294), FB(388307), FB(388320), FB(388330),
    FB(388343), FB(388356), FB(388369), FB(388382), FB(388395),
};
const char lang_name_lo_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x80" "\x8E" "\xEE" "\x80" "\x8C");

// my: 190 shaped cluster glyphs (Myanmar Sangam MN)
// shaped-source-hash my cc2dd5bb28ac8ab1
const display_glyph_font_t font_my = {
    .codepoints = FB16(388408),
    .glyphs_rle = fonts_blob + 388978,
    .glyphs_off = FB16(398032),
    .glyphs_2x_rle = fonts_blob + 398414,
    .glyphs_2x_off = FB16(403642),
    .widths = fonts_blob + 388788,
    .count = 190,
    .glyph_width = 16,
};
const char *const lang_my_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(404024), [STR_WIFI] = FB(404046), [STR_FAIL] = FB(404052),
    [STR_TIMEZONE] = FB(404074), [STR_BRIGHTNESS] = FB(404087), [STR_LED_BLINK] = FB(404106),
    [STR_ROTATE] = FB(404128), [STR_ABOUT] = FB(404144), [STR_LANGUAGE] = FB(404163),
    [STR_DONE] = FB(404176), [STR_BACK] = FB(404189), [STR_CANCEL] = FB(404205),
    [STR_DEL] = FB(404221), [STR_RUNNING] = FB(404231), [STR_ON] = FB(404250),
    [STR_OFF] = FB(404254), [STR_NTS_NO] = FB(404261), [STR_NTS_ATTEMPT] = FB(404271),
    [STR_NTS_REQUIRE] = FB(404290), [STR_WAITING_NTP] = FB(404300),
    [STR_FMT_SYNCED] = FB(404337), [STR_FMT_SYNCING] = FB(404352),
    [STR_FMT_WAITING] = FB(404376), [STR_WIFI_SETUP] = FB(404396), [STR_SCANNING] = FB(404427),
    [STR_SCAN_FAILED] = FB(404452), [STR_TAP_RETRY] = FB(404486),
    [STR_SELECT_NETWORK] = FB(404511), [STR_NO_NETWORKS] = FB(404533),
    [STR_NETWORK_LABEL] = FB(404549), [STR_ENTER_PASSWORD] = FB(404559),
    [STR_CONNECTING] = FB(404587), [STR_CONNECTING_TO] = FB(404606),
    [STR_CONNECTED] = FB(404628), [STR_CONNECTION_FAILED] = FB(404647),
    [STR_KB_SPACE] = FB(404684), [STR_KB_GO] = FB(404703), [STR_VERSION] = FB(404706),
    [STR_STATUS] = FB(404725), [STR_READ] = FB(404750), [STR_UPDATE] = FB(404763),
    [STR_RESTARTING] = FB(404773), [STR_OTA_UPDATE] = FB(404789), [STR_NTP_SERVER] = FB(404811),
    [STR_SERVER_LABEL] = FB(404836), [STR_NTP_SETTINGS] = FB(404852),
    [STR_NTP_PRESETS] = FB(404877), [STR_PRESETS] = FB(404899), [STR_BENCHMARK] = FB(404909),
    [STR_STOPPING] = FB(404922), [STR_NTP_STATS] = FB(404938), [STR_UNSYNCED] = FB(404963),
    [STR_NONE] = FB(404976), [STR_SELECT_REGION] = FB(404983), [STR_AGE_LABEL] = FB(405005),
    [STR_SYNCS_LABEL] = FB(405030), [STR_FMT_PEERS_NOSYNC] = FB(405046),
    [STR_FMT_PEERS_AGO] = FB(405114), [STR_DST] = FB(405177), [STR_NO_DST] = FB(405199),
};
const char *const weekdays_my_shaped[7] = {
    FB(405224), FB(405237), FB(405247), FB(405254), FB(405261), FB(405286), FB(405305),
};
const char *const months_my_shaped[12] = {
    FB(405315), FB(405322), FB(405329), FB(405336), FB(405340), FB(405347), FB(405351),
    FB(405355), FB(405359), FB(405366), FB(405379), FB(405383),
};
const char lang_name_my_shaped[] = ("\xEE" "\x80" "\xA6" "\xEE" "\x80" "\x8C" "\xEE" "\x82" "\xBD" "\xEE" "\x80" "\x8A");

// am: 181 shaped cluster glyphs (Kefa)
// shaped-source-hash am c9126eadc16b5c72
const display_glyph_font_t font_am = {
    .codepoints = FB16(405388),
    .glyphs_rle = fonts_blob + 405931,
    .glyphs_off = FB16(415068),
    .glyphs_2x_rle = fonts_blob + 415432,
    .glyphs_2x_off = FB16(422716),
    .widths = fonts_blob + 405750,
    .count = 181,
    .glyph_width = 16,
};
const char *const lang_am_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(423080), [STR_WIFI] = FB(423096), [STR_FAIL] = FB(423102),
    [STR_TIMEZONE] = FB(423121), [STR_BRIGHTNESS] = FB(423143), [STR_LED_BLINK] = FB(423159),
    [STR_ROTATE] = FB(423184), [STR_ABOUT] = FB(423206), [STR_LANGUAGE] = FB(423213),
    [STR_DONE] = FB(423223), [STR_BACK] = FB(423239), [STR_CANCEL] = FB(423252),
    [STR_DEL] = FB(423262), [STR_RUNNING] = FB(423272), [STR_ON] = FB(423294),
    [STR_OFF] = FB(423307), [STR_NTS_NO] = FB(423320), [STR_NTS_ATTEMPT] = FB(423327),
    [STR_NTS_REQUIRE] = FB(423337), [STR_WAITING_NTP] = FB(423347),
    [STR_FMT_SYNCED] = FB(423384), [STR_FMT_SYNCING] = FB(423411),
    [STR_FMT_WAITING] = FB(423438), [STR_WIFI_SETUP] = FB(423461), [STR_SCANNING] = FB(423492),
    [STR_SCAN_FAILED] = FB(423517), [STR_TAP_RETRY] = FB(423548),
    [STR_SELECT_NETWORK] = FB(423591), [STR_NO_NETWORKS] = FB(423628),
    [STR_NETWORK_LABEL] = FB(423665), [STR_ENTER_PASSWORD] = FB(423681),
    [STR_CONNECTING] = FB(423718), [STR_CONNECTING_TO] = FB(423737),
    [STR_CONNECTED] = FB(423759), [STR_CONNECTION_FAILED] = FB(423781),
    [STR_KB_SPACE] = FB(423818), [STR_KB_GO] = FB(423831), [STR_VERSION] = FB(423834),
    [STR_STATUS] = FB(423847), [STR_READ] = FB(423860), [STR_UPDATE] = FB(423879),
    [STR_RESTARTING] = FB(423892), [STR_OTA_UPDATE] = FB(423926), [STR_NTP_SERVER] = FB(423951),
    [STR_SERVER_LABEL] = FB(423979), [STR_NTP_SETTINGS] = FB(423998),
    [STR_NTP_PRESETS] = FB(424026), [STR_PRESETS] = FB(424057), [STR_BENCHMARK] = FB(424073),
    [STR_STOPPING] = FB(424083), [STR_NTP_STATS] = FB(424096), [STR_UNSYNCED] = FB(424130),
    [STR_NONE] = FB(424152), [STR_SELECT_REGION] = FB(424162), [STR_AGE_LABEL] = FB(424184),
    [STR_SYNCS_LABEL] = FB(424206), [STR_FMT_PEERS_NOSYNC] = FB(424228),
    [STR_FMT_PEERS_AGO] = FB(424302), [STR_DST] = FB(424372), [STR_NO_DST] = FB(424394),
};
const char *const weekdays_am_shaped[7] = {
    FB(424428), FB(424438), FB(424445), FB(424455), FB(424465), FB(424475), FB(424485),
};
const char *const months_am_shaped[12] = {
    FB(424495), FB(424502), FB(424509), FB(424519), FB(424529), FB(424536), FB(424543),
    FB(424553), FB(424563), FB(424573), FB(424583), FB(424593),
};
const char lang_name_am_shaped[] = ("\xEE" "\x80" "\x85" "\xEE" "\x81" "\xBF" "\xEE" "\x80" "\xB0" "\xEE" "\x82" "\xB4");

// kok: 172 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash kok 8d37d315f8d9d887
const display_glyph_font_t font_kok = {
    .codepoints = FB16(424604),
    .glyphs_rle = fonts_blob + 425120,
    .glyphs_off = FB16(433040),
    .glyphs_2x_rle = fonts_blob + 433386,
    .glyphs_2x_off = FB16(438346),
    .widths = fonts_blob + 424948,
    .count = 172,
    .glyph_width = 16,
};
const char *const lang_kok_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(438692), [STR_SETTINGS] = FB(438698), [STR_FAIL] = FB(438711),
    [STR_TIMEZONE] = FB(438718), [STR_BRIGHTNESS] = FB(438740), [STR_LED_BLINK] = FB(438756),
    [STR_ROTATE] = FB(438781), [STR_ABOUT] = FB(438806), [STR_LANGUAGE] = FB(438819),
    [STR_DONE] = FB(438829), [STR_BACK] = FB(438839), [STR_CANCEL] = FB(438852),
    [STR_DEL] = FB(438859), [STR_RUNNING] = FB(438869), [STR_ON] = FB(438888),
    [STR_OFF] = FB(438898), [STR_NTS_NO] = FB(438902), [STR_NTS_ATTEMPT] = FB(438909),
    [STR_NTS_REQUIRE] = FB(438916), [STR_WAITING_NTP] = FB(438926),
    [STR_FMT_SYNCED] = FB(438981), [STR_FMT_SYNCING] = FB(439011),
    [STR_FMT_WAITING] = FB(439047), [STR_FMT_PEERS_NOSYNC] = FB(439073),
    [STR_FMT_PEERS_AGO] = FB(439138), [STR_WIFI_SETUP] = FB(439192),
    [STR_SCANNING] = FB(439226), [STR_SCAN_FAILED] = FB(439251), [STR_TAP_RETRY] = FB(439270),
    [STR_SELECT_NETWORK] = FB(439325), [STR_NO_NETWORKS] = FB(439350),
    [STR_NETWORK_LABEL] = FB(439381), [STR_ENTER_PASSWORD] = FB(439397),
    [STR_CONNECTING] = FB(439428), [STR_CONNECTING_TO] = FB(439444),
    [STR_CONNECTED] = FB(439463), [STR_CONNECTION_FAILED] = FB(439476),
    [STR_KB_SPACE] = FB(439501), [STR_KB_GO] = FB(439514), [STR_VERSION] = FB(439517),
    [STR_STATUS] = FB(439530), [STR_READ] = FB(439546), [STR_UPDATE] = FB(439559),
    [STR_RESTARTING] = FB(439569), [STR_OTA_UPDATE] = FB(439600), [STR_NTP_SERVER] = FB(439622),
    [STR_SERVER_LABEL] = FB(439641), [STR_NTP_SETTINGS] = FB(439651),
    [STR_NTP_PRESETS] = FB(439676), [STR_PRESETS] = FB(439701), [STR_BENCHMARK] = FB(439714),
    [STR_STOPPING] = FB(439727), [STR_NTP_STATS] = FB(439740), [STR_UNSYNCED] = FB(439765),
    [STR_SYNCS_LABEL] = FB(439787), [STR_NONE] = FB(439812), [STR_SELECT_REGION] = FB(439819),
    [STR_AGE_LABEL] = FB(439841), [STR_DST] = FB(439869), [STR_NO_DST] = FB(439894),
};
const char *const weekdays_kok_shaped[7] = {
    FB(439928), FB(439944), FB(439960), FB(439973), FB(439986), FB(440005), FB(440018),
};
const char *const months_kok_shaped[12] = {
    FB(440031), FB(440041), FB(440051), FB(440061), FB(440071), FB(440075), FB(440079),
    FB(440086), FB(440093), FB(440100), FB(440110), FB(440120),
};
const char lang_name_kok_shaped[] = ("\xEE" "\x80" "\xAA" "\xEE" "\x82" "\xAB" "\xEE" "\x82" "\x84" "\xEE" "\x81" "\xAB" "\xEE" "\x80" "\xBD");

// as: 162 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash as 49869d97afa2e3e1
const display_glyph_font_t font_as = {
    .codepoints = FB16(440130),
    .glyphs_rle = fonts_blob + 440616,
    .glyphs_off = FB16(447212),
    .glyphs_2x_rle = fonts_blob + 447538,
    .glyphs_2x_off = FB16(452894),
    .widths = fonts_blob + 440454,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_as_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(453220), [STR_SETTINGS] = FB(453226), [STR_FAIL] = FB(453242),
    [STR_TIMEZONE] = FB(453255), [STR_BRIGHTNESS] = FB(453277), [STR_LED_BLINK] = FB(453293),
    [STR_ROTATE] = FB(453327), [STR_ABOUT] = FB(453358), [STR_LANGUAGE] = FB(453374),
    [STR_DONE] = FB(453387), [STR_BACK] = FB(453397), [STR_CANCEL] = FB(453410),
    [STR_DEL] = FB(453426), [STR_RUNNING] = FB(453436), [STR_ON] = FB(453458),
    [STR_OFF] = FB(453465), [STR_NTS_NO] = FB(453472), [STR_NTS_ATTEMPT] = FB(453482),
    [STR_NTS_REQUIRE] = FB(453495), [STR_WAITING_NTP] = FB(453511),
    [STR_FMT_SYNCED] = FB(453557), [STR_FMT_SYNCING] = FB(453590),
    [STR_FMT_WAITING] = FB(453632), [STR_FMT_PEERS_NOSYNC] = FB(453658),
    [STR_FMT_PEERS_AGO] = FB(453738), [STR_WIFI_SETUP] = FB(453804),
    [STR_SCANNING] = FB(453838), [STR_SCAN_FAILED] = FB(453878), [STR_TAP_RETRY] = FB(453903),
    [STR_SELECT_NETWORK] = FB(453961), [STR_NO_NETWORKS] = FB(453995),
    [STR_NETWORK_LABEL] = FB(454047), [STR_ENTER_PASSWORD] = FB(454069),
    [STR_CONNECTING] = FB(454103), [STR_CONNECTING_TO] = FB(454137),
    [STR_CONNECTED] = FB(454159), [STR_CONNECTION_FAILED] = FB(454178),
    [STR_KB_SPACE] = FB(454212), [STR_KB_GO] = FB(454225), [STR_VERSION] = FB(454228),
    [STR_STATUS] = FB(454247), [STR_READ] = FB(454263), [STR_UPDATE] = FB(454288),
    [STR_RESTARTING] = FB(454304), [STR_OTA_UPDATE] = FB(454323), [STR_NTP_SERVER] = FB(454351),
    [STR_SERVER_LABEL] = FB(454382), [STR_NTP_SETTINGS] = FB(454404),
    [STR_NTP_PRESETS] = FB(454432), [STR_PRESETS] = FB(454457), [STR_BENCHMARK] = FB(454470),
    [STR_STOPPING] = FB(454486), [STR_NTP_STATS] = FB(454505), [STR_UNSYNCED] = FB(454542),
    [STR_SYNCS_LABEL] = FB(454567), [STR_NONE] = FB(454592), [STR_SELECT_REGION] = FB(454602),
    [STR_AGE_LABEL] = FB(454627), [STR_DST] = FB(454649), [STR_NO_DST] = FB(454671),
};
const char *const weekdays_as_shaped[7] = {
    FB(454705), FB(454715), FB(454728), FB(454738), FB(454748), FB(454758), FB(454765),
};
const char *const months_as_shaped[12] = {
    FB(454775), FB(454785), FB(454798), FB(454811), FB(454824), FB(454834), FB(454841),
    FB(454854), FB(454861), FB(454874), FB(454887), FB(454897),
};
const char lang_name_as_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x82" "\xA1" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\x88" "\xEE" "\x80" "\x8B" "\xEE" "\x80" "\xA8");

// ti: 173 shaped cluster glyphs (Kefa)
// shaped-source-hash ti 4f351d4fedbcdbcd
const display_glyph_font_t font_ti = {
    .codepoints = FB16(454910),
    .glyphs_rle = fonts_blob + 455429,
    .glyphs_off = FB16(464144),
    .glyphs_2x_rle = fonts_blob + 464492,
    .glyphs_2x_off = FB16(469014),
    .widths = fonts_blob + 455256,
    .count = 173,
    .glyph_width = 16,
};
const char *const lang_ti_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(469362), [STR_SETTINGS] = FB(469368), [STR_FAIL] = FB(469384),
    [STR_TIMEZONE] = FB(469394), [STR_BRIGHTNESS] = FB(469413), [STR_LED_BLINK] = FB(469426),
    [STR_ROTATE] = FB(469451), [STR_ABOUT] = FB(469473), [STR_LANGUAGE] = FB(469486),
    [STR_DONE] = FB(469496), [STR_BACK] = FB(469509), [STR_CANCEL] = FB(469522),
    [STR_DEL] = FB(469532), [STR_RUNNING] = FB(469545), [STR_ON] = FB(469558),
    [STR_OFF] = FB(469568), [STR_NTS_NO] = FB(469578), [STR_NTS_ATTEMPT] = FB(469591),
    [STR_NTS_REQUIRE] = FB(469601), [STR_WAITING_NTP] = FB(469611),
    [STR_FMT_SYNCED] = FB(469642), [STR_FMT_SYNCING] = FB(469666),
    [STR_FMT_WAITING] = FB(469690), [STR_FMT_PEERS_NOSYNC] = FB(469710),
    [STR_FMT_PEERS_AGO] = FB(469781), [STR_WIFI_SETUP] = FB(469845),
    [STR_SCANNING] = FB(469876), [STR_SCAN_FAILED] = FB(469895), [STR_TAP_RETRY] = FB(469920),
    [STR_SELECT_NETWORK] = FB(469966), [STR_NO_NETWORKS] = FB(469991),
    [STR_NETWORK_LABEL] = FB(470028), [STR_ENTER_PASSWORD] = FB(470044),
    [STR_CONNECTING] = FB(470078), [STR_CONNECTING_TO] = FB(470091),
    [STR_CONNECTED] = FB(470113), [STR_CONNECTION_FAILED] = FB(470129),
    [STR_KB_SPACE] = FB(470151), [STR_KB_GO] = FB(470164), [STR_VERSION] = FB(470167),
    [STR_STATUS] = FB(470180), [STR_READ] = FB(470196), [STR_UPDATE] = FB(470212),
    [STR_RESTARTING] = FB(470225), [STR_OTA_UPDATE] = FB(470253), [STR_NTP_SERVER] = FB(470278),
    [STR_SERVER_LABEL] = FB(470303), [STR_NTP_SETTINGS] = FB(470319),
    [STR_NTP_PRESETS] = FB(470347), [STR_PRESETS] = FB(470378), [STR_BENCHMARK] = FB(470388),
    [STR_STOPPING] = FB(470398), [STR_NTP_STATS] = FB(470408), [STR_UNSYNCED] = FB(470439),
    [STR_SYNCS_LABEL] = FB(470461), [STR_NONE] = FB(470483), [STR_SELECT_REGION] = FB(470493),
    [STR_AGE_LABEL] = FB(470512), [STR_DST] = FB(470534), [STR_NO_DST] = FB(470565),
};
const char *const weekdays_ti_shaped[7] = {
    FB(470608), FB(470615), FB(470622), FB(470629), FB(470636), FB(470643), FB(470650),
};
const char *const months_ti_shaped[12] = {
    FB(470657), FB(470664), FB(470671), FB(470678), FB(470685), FB(470692), FB(470699),
    FB(470706), FB(470713), FB(470720), FB(470727), FB(470734),
};
const char lang_name_ti_shaped[] = ("\xEE" "\x82" "\xAB" "\xEE" "\x80" "\xBC" "\xEE" "\x80" "\x9D" "\xEE" "\x82" "\xAC");

// yo: 162 shaped cluster glyphs (Menlo)
// shaped-source-hash yo 982118199a97bd15
const display_glyph_font_t font_yo = {
    .codepoints = FB16(470742),
    .glyphs_rle = fonts_blob + 471228,
    .glyphs_off = FB16(478236),
    .glyphs_2x_rle = fonts_blob + 478562,
    .glyphs_2x_off = FB16(484724),
    .widths = fonts_blob + 471066,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_yo_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(485050), [STR_SETTINGS] = FB(485056), [STR_FAIL] = FB(485066),
    [STR_TIMEZONE] = FB(485079), [STR_BRIGHTNESS] = FB(485119), [STR_LED_BLINK] = FB(485135),
    [STR_ROTATE] = FB(485169), [STR_ABOUT] = FB(485188), [STR_LANGUAGE] = FB(485201),
    [STR_DONE] = FB(485211), [STR_BACK] = FB(485224), [STR_CANCEL] = FB(485237),
    [STR_DEL] = FB(485256), [STR_RUNNING] = FB(485269), [STR_ON] = FB(485285),
    [STR_OFF] = FB(485295), [STR_NTS_NO] = FB(485298), [STR_NTS_ATTEMPT] = FB(485311),
    [STR_NTS_REQUIRE] = FB(485336), [STR_WAITING_NTP] = FB(485343),
    [STR_FMT_SYNCED] = FB(485392), [STR_FMT_SYNCING] = FB(485428),
    [STR_FMT_WAITING] = FB(485470), [STR_FMT_PEERS_NOSYNC] = FB(485499),
    [STR_FMT_PEERS_AGO] = FB(485579), [STR_WIFI_SETUP] = FB(485642),
    [STR_SCANNING] = FB(485673), [STR_SCAN_FAILED] = FB(485695), [STR_TAP_RETRY] = FB(485729),
    [STR_SELECT_NETWORK] = FB(485790), [STR_NO_NETWORKS] = FB(485827),
    [STR_NETWORK_LABEL] = FB(485870), [STR_ENTER_PASSWORD] = FB(485898),
    [STR_CONNECTING] = FB(485941), [STR_CONNECTING_TO] = FB(485966),
    [STR_CONNECTED] = FB(485997), [STR_CONNECTION_FAILED] = FB(486025),
    [STR_KB_SPACE] = FB(486059), [STR_KB_GO] = FB(486069), [STR_VERSION] = FB(486072),
    [STR_STATUS] = FB(486088), [STR_READ] = FB(486101), [STR_UPDATE] = FB(486120),
    [STR_RESTARTING] = FB(486139), [STR_OTA_UPDATE] = FB(486176), [STR_NTP_SERVER] = FB(486207),
    [STR_SERVER_LABEL] = FB(486232), [STR_NTP_SETTINGS] = FB(486248),
    [STR_NTP_PRESETS] = FB(486270), [STR_PRESETS] = FB(486301), [STR_BENCHMARK] = FB(486320),
    [STR_STOPPING] = FB(486339), [STR_NTP_STATS] = FB(486370), [STR_UNSYNCED] = FB(486398),
    [STR_SYNCS_LABEL] = FB(486429), [STR_NONE] = FB(486438), [STR_SELECT_REGION] = FB(486454),
    [STR_AGE_LABEL] = FB(486488), [STR_DST] = FB(486519), [STR_NO_DST] = FB(486523),
};
const char *const weekdays_yo_shaped[7] = {
    FB(486551), FB(486564), FB(486574), FB(486590), FB(486603), FB(486616), FB(486626),
};
const char *const months_yo_shaped[12] = {
    FB(486645), FB(486652), FB(486668), FB(486687), FB(486700), FB(486719), FB(486735),
    FB(486751), FB(486764), FB(486770), FB(486789), FB(486802),
};
const char lang_name_yo_shaped[] = ("\xEE" "\x80" "\xA0" "\xEE" "\x82" "\xA1" "\xEE" "\x80" "\xAC" "\xEE" "\x81" "\xAA" "\xEE" "\x81" "\xAE" "\xEE" "\x80" "\x9E");

// pcm: 76 shaped cluster glyphs (Menlo)
// shaped-source-hash pcm cf5006cfbcbb2501
const display_glyph_font_t font_pcm = {
    .codepoints = FB16(486818),
    .glyphs_rle = fonts_blob + 487046,
    .glyphs_off = FB16(490496),
    .glyphs_2x_rle = fonts_blob + 490650,
    .glyphs_2x_off = FB16(494164),
    .widths = fonts_blob + 486970,
    .count = 76,
    .glyph_width = 16,
};
const char *const lang_pcm_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(494318), [STR_SETTINGS] = FB(494324), [STR_FAIL] = FB(494343),
    [STR_TIMEZONE] = FB(494347), [STR_BRIGHTNESS] = FB(494356), [STR_LED_BLINK] = FB(494381),
    [STR_ROTATE] = FB(494391), [STR_ABOUT] = FB(494400), [STR_LANGUAGE] = FB(494406),
    [STR_DONE] = FB(494414), [STR_BACK] = FB(494418), [STR_CANCEL] = FB(494422),
    [STR_DEL] = FB(494441), [STR_RUNNING] = FB(494446), [STR_ON] = FB(494453),
    [STR_OFF] = FB(494456), [STR_NTS_NO] = FB(494459), [STR_NTS_ATTEMPT] = FB(494462),
    [STR_NTS_REQUIRE] = FB(494467), [STR_WAITING_NTP] = FB(494472),
    [STR_FMT_SYNCED] = FB(494490), [STR_FMT_SYNCING] = FB(494503),
    [STR_FMT_WAITING] = FB(494515), [STR_FMT_PEERS_NOSYNC] = FB(494528),
    [STR_FMT_PEERS_AGO] = FB(494557), [STR_WIFI_SETUP] = FB(494589),
    [STR_SCANNING] = FB(494599), [STR_SCAN_FAILED] = FB(494610), [STR_TAP_RETRY] = FB(494623),
    [STR_SELECT_NETWORK] = FB(494645), [STR_NO_NETWORKS] = FB(494673),
    [STR_NETWORK_LABEL] = FB(494710), [STR_ENTER_PASSWORD] = FB(494729),
    [STR_CONNECTING] = FB(494760), [STR_CONNECTING_TO] = FB(494769),
    [STR_CONNECTED] = FB(494781), [STR_CONNECTION_FAILED] = FB(494792),
    [STR_KB_SPACE] = FB(494806), [STR_KB_GO] = FB(494811), [STR_VERSION] = FB(494814),
    [STR_STATUS] = FB(494833), [STR_READ] = FB(494844), [STR_UPDATE] = FB(494853),
    [STR_RESTARTING] = FB(494869), [STR_OTA_UPDATE] = FB(494883), [STR_NTP_SERVER] = FB(494894),
    [STR_SERVER_LABEL] = FB(494903), [STR_NTP_SETTINGS] = FB(494909),
    [STR_NTP_PRESETS] = FB(494940), [STR_PRESETS] = FB(494950), [STR_BENCHMARK] = FB(494956),
    [STR_STOPPING] = FB(494969), [STR_NTP_STATS] = FB(494977), [STR_UNSYNCED] = FB(494987),
    [STR_SYNCS_LABEL] = FB(494995), [STR_NONE] = FB(495004), [STR_SELECT_REGION] = FB(495020),
    [STR_AGE_LABEL] = FB(495048), [STR_DST] = FB(495055), [STR_NO_DST] = FB(495059),
};
const char *const weekdays_pcm_shaped[7] = {
    FB(495066), FB(495073), FB(495080), FB(495090), FB(495097), FB(495104), FB(495117),
};
const char *const months_pcm_shaped[12] = {
    FB(495127), FB(495137), FB(495144), FB(495149), FB(495159), FB(495163), FB(495167),
    FB(495171), FB(495181), FB(495191), FB(495201), FB(495211),
};
const char lang_name_pcm_shaped[] = ("\xEE" "\x80" "\x9B" "\xEE" "\x80" "\x8F" "\xEE" "\x81" "\x89" "\xEE" "\x81" "\x8A" "\xEE" "\x81" "\x8B");

// pa_arab: 190 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash pa_arab 8cb15c6e013b6adb
const display_glyph_font_t font_pa_arab = {
    .codepoints = FB16(495216),
    .glyphs_rle = fonts_blob + 495786,
    .glyphs_off = FB16(502568),
    .glyphs_2x_rle = fonts_blob + 502950,
    .glyphs_2x_off = FB16(507382),
    .widths = fonts_blob + 495596,
    .count = 190,
    .glyph_width = 16,
};
const char *const lang_pa_arab_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(507764), [STR_SETTINGS] = FB(507770), [STR_FAIL] = FB(507792),
    [STR_TIMEZONE] = FB(507808), [STR_BRIGHTNESS] = FB(507842), [STR_LED_BLINK] = FB(507852),
    [STR_ROTATE] = FB(507877), [STR_ABOUT] = FB(507905), [STR_LANGUAGE] = FB(507927),
    [STR_DONE] = FB(507940), [STR_BACK] = FB(507959), [STR_CANCEL] = FB(507972),
    [STR_DEL] = FB(507988), [STR_RUNNING] = FB(508001), [STR_ON] = FB(508032),
    [STR_OFF] = FB(508045), [STR_NTS_NO] = FB(508055), [STR_NTS_ATTEMPT] = FB(508068),
    [STR_NTS_REQUIRE] = FB(508081), [STR_WAITING_NTP] = FB(508094),
    [STR_FMT_SYNCED] = FB(508137), [STR_FMT_SYNCING] = FB(508164),
    [STR_FMT_WAITING] = FB(508215), [STR_FMT_PEERS_NOSYNC] = FB(508238),
    [STR_FMT_PEERS_AGO] = FB(508321), [STR_WIFI_SETUP] = FB(508384),
    [STR_SCANNING] = FB(508421), [STR_SCAN_FAILED] = FB(508464), [STR_TAP_RETRY] = FB(508507),
    [STR_SELECT_NETWORK] = FB(508562), [STR_NO_NETWORKS] = FB(508593),
    [STR_NETWORK_LABEL] = FB(508642), [STR_ENTER_PASSWORD] = FB(508664),
    [STR_CONNECTING] = FB(508698), [STR_CONNECTING_TO] = FB(508729),
    [STR_CONNECTED] = FB(508763), [STR_CONNECTION_FAILED] = FB(508785),
    [STR_KB_SPACE] = FB(508819), [STR_KB_GO] = FB(508832), [STR_VERSION] = FB(508835),
    [STR_STATUS] = FB(508851), [STR_READ] = FB(508867), [STR_UPDATE] = FB(508886),
    [STR_RESTARTING] = FB(508905), [STR_OTA_UPDATE] = FB(508954), [STR_NTP_SERVER] = FB(508985),
    [STR_SERVER_LABEL] = FB(509010), [STR_NTP_SETTINGS] = FB(509026),
    [STR_NTP_PRESETS] = FB(509060), [STR_PRESETS] = FB(509091), [STR_BENCHMARK] = FB(509110),
    [STR_STOPPING] = FB(509123), [STR_NTP_STATS] = FB(509154), [STR_UNSYNCED] = FB(509191),
    [STR_SYNCS_LABEL] = FB(509225), [STR_NONE] = FB(509247), [STR_SELECT_REGION] = FB(509275),
    [STR_AGE_LABEL] = FB(509297), [STR_DST] = FB(509319), [STR_NO_DST] = FB(509359),
};
const char *const weekdays_pa_arab_shaped[7] = {
    FB(509396), FB(509412), FB(509422), FB(509435), FB(509442), FB(509461), FB(509474),
};
const char *const months_pa_arab_shaped[12] = {
    FB(509487), FB(509503), FB(509519), FB(509532), FB(509548), FB(509555), FB(509565),
    FB(509581), FB(509594), FB(509610), FB(509629), FB(509645),
};
const char lang_name_pa_arab_shaped[] = ("\xEE" "\x80" "\xAA" "\xEE" "\x82" "\xBB" "\xEE" "\x80" "\x88" "\xEE" "\x82" "\xBC" "\xEE" "\x80" "\x83" "\xEE" "\x82" "\xBD");

// bho: 181 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash bho 4ce0231b25142dc0
const display_glyph_font_t font_bho = {
    .codepoints = FB16(509662),
    .glyphs_rle = fonts_blob + 510205,
    .glyphs_off = FB16(518336),
    .glyphs_2x_rle = fonts_blob + 518700,
    .glyphs_2x_off = FB16(523448),
    .widths = fonts_blob + 510024,
    .count = 181,
    .glyph_width = 16,
};
const char *const lang_bho_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(523812), [STR_SETTINGS] = FB(523818), [STR_FAIL] = FB(523831),
    [STR_TIMEZONE] = FB(523844), [STR_BRIGHTNESS] = FB(523860), [STR_LED_BLINK] = FB(523870),
    [STR_ROTATE] = FB(523892), [STR_ABOUT] = FB(523914), [STR_LANGUAGE] = FB(523930),
    [STR_DONE] = FB(523943), [STR_BACK] = FB(523959), [STR_CANCEL] = FB(523972),
    [STR_DEL] = FB(523979), [STR_RUNNING] = FB(523989), [STR_ON] = FB(524008),
    [STR_OFF] = FB(524018), [STR_NTS_NO] = FB(524022), [STR_NTS_ATTEMPT] = FB(524029),
    [STR_NTS_REQUIRE] = FB(524045), [STR_WAITING_NTP] = FB(524058),
    [STR_FMT_SYNCED] = FB(524107), [STR_FMT_SYNCING] = FB(524140),
    [STR_FMT_WAITING] = FB(524176), [STR_FMT_PEERS_NOSYNC] = FB(524205),
    [STR_FMT_PEERS_AGO] = FB(524273), [STR_WIFI_SETUP] = FB(524330),
    [STR_SCANNING] = FB(524358), [STR_SCAN_FAILED] = FB(524389), [STR_TAP_RETRY] = FB(524414),
    [STR_SELECT_NETWORK] = FB(524475), [STR_NO_NETWORKS] = FB(524497),
    [STR_NETWORK_LABEL] = FB(524522), [STR_ENTER_PASSWORD] = FB(524538),
    [STR_CONNECTING] = FB(524566), [STR_CONNECTING_TO] = FB(524582),
    [STR_CONNECTED] = FB(524601), [STR_CONNECTION_FAILED] = FB(524620),
    [STR_KB_SPACE] = FB(524648), [STR_KB_GO] = FB(524655), [STR_VERSION] = FB(524658),
    [STR_STATUS] = FB(524674), [STR_READ] = FB(524690), [STR_UPDATE] = FB(524703),
    [STR_RESTARTING] = FB(524713), [STR_OTA_UPDATE] = FB(524744), [STR_NTP_SERVER] = FB(524766),
    [STR_SERVER_LABEL] = FB(524785), [STR_NTP_SETTINGS] = FB(524795),
    [STR_NTP_PRESETS] = FB(524820), [STR_PRESETS] = FB(524845), [STR_BENCHMARK] = FB(524858),
    [STR_STOPPING] = FB(524865), [STR_NTP_STATS] = FB(524884), [STR_UNSYNCED] = FB(524912),
    [STR_SYNCS_LABEL] = FB(524937), [STR_NONE] = FB(524962), [STR_SELECT_REGION] = FB(524987),
    [STR_AGE_LABEL] = FB(525000), [STR_DST] = FB(525025), [STR_NO_DST] = FB(525059),
};
const char *const weekdays_bho_shaped[7] = {
    FB(525096), FB(525115), FB(525134), FB(525150), FB(525163), FB(525176), FB(525192),
};
const char *const months_bho_shaped[12] = {
    FB(525208), FB(525224), FB(525240), FB(525250), FB(525257), FB(525264), FB(525268),
    FB(525281), FB(525291), FB(525307), FB(525323), FB(525333),
};
const char lang_name_bho_shaped[] = ("\xEE" "\x80" "\x9E" "\xEE" "\x81" "\x93" "\xEE" "\x80" "\xAE" "\xEE" "\x82" "\xB4" "\xEE" "\x80" "\xB0");

// ps: 174 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ps 2bba1a83065bc917
const display_glyph_font_t font_ps = {
    .codepoints = FB16(525346),
    .glyphs_rle = fonts_blob + 525868,
    .glyphs_off = FB16(531962),
    .glyphs_2x_rle = fonts_blob + 532312,
    .glyphs_2x_off = FB16(536580),
    .widths = fonts_blob + 525694,
    .count = 174,
    .glyph_width = 16,
};
const char *const lang_ps_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(536930), [STR_SETTINGS] = FB(536936), [STR_FAIL] = FB(536955),
    [STR_TIMEZONE] = FB(536971), [STR_BRIGHTNESS] = FB(537002), [STR_LED_BLINK] = FB(537021),
    [STR_ROTATE] = FB(537049), [STR_ABOUT] = FB(537077), [STR_LANGUAGE] = FB(537096),
    [STR_DONE] = FB(537106), [STR_BACK] = FB(537119), [STR_CANCEL] = FB(537132),
    [STR_DEL] = FB(537145), [STR_RUNNING] = FB(537155), [STR_ON] = FB(537177),
    [STR_OFF] = FB(537190), [STR_NTS_NO] = FB(537200), [STR_NTS_ATTEMPT] = FB(537207),
    [STR_NTS_REQUIRE] = FB(537217), [STR_WAITING_NTP] = FB(537230),
    [STR_FMT_SYNCED] = FB(537276), [STR_FMT_SYNCING] = FB(537300),
    [STR_FMT_WAITING] = FB(537339), [STR_FMT_PEERS_NOSYNC] = FB(537368),
    [STR_FMT_PEERS_AGO] = FB(537448), [STR_WIFI_SETUP] = FB(537511),
    [STR_SCANNING] = FB(537551), [STR_SCAN_FAILED] = FB(537573), [STR_TAP_RETRY] = FB(537604),
    [STR_SELECT_NETWORK] = FB(537668), [STR_NO_NETWORKS] = FB(537699),
    [STR_NETWORK_LABEL] = FB(537754), [STR_ENTER_PASSWORD] = FB(537770),
    [STR_CONNECTING] = FB(537804), [STR_CONNECTING_TO] = FB(537823),
    [STR_CONNECTED] = FB(537854), [STR_CONNECTION_FAILED] = FB(537876),
    [STR_KB_SPACE] = FB(537913), [STR_KB_GO] = FB(537923), [STR_VERSION] = FB(537926),
    [STR_STATUS] = FB(537942), [STR_READ] = FB(537958), [STR_UPDATE] = FB(537989),
    [STR_RESTARTING] = FB(538002), [STR_OTA_UPDATE] = FB(538033), [STR_NTP_SERVER] = FB(538064),
    [STR_SERVER_LABEL] = FB(538095), [STR_NTP_SETTINGS] = FB(538111),
    [STR_NTP_PRESETS] = FB(538148), [STR_PRESETS] = FB(538182), [STR_BENCHMARK] = FB(538198),
    [STR_STOPPING] = FB(538220), [STR_NTP_STATS] = FB(538236), [STR_UNSYNCED] = FB(538270),
    [STR_SYNCS_LABEL] = FB(538301), [STR_NONE] = FB(538329), [STR_SELECT_REGION] = FB(538339),
    [STR_AGE_LABEL] = FB(538370), [STR_DST] = FB(538392), [STR_NO_DST] = FB(538423),
};
const char *const weekdays_ps_shaped[7] = {
    FB(538469), FB(538482), FB(538495), FB(538511), FB(538527), FB(538546), FB(538559),
};
const char *const months_ps_shaped[12] = {
    FB(538572), FB(538588), FB(538607), FB(538620), FB(538636), FB(538643), FB(538653),
    FB(538666), FB(538679), FB(538701), FB(538720), FB(538736),
};
const char lang_name_ps_shaped[] = ("\xEE" "\x80" "\xB2" "\xEE" "\x80" "\x82" "\xEE" "\x82" "\xAD" "\xEE" "\x80" "\xA9");

// or: 197 shaped cluster glyphs (Oriya Sangam MN)
// shaped-source-hash or c99f812c1858939d
const display_glyph_font_t font_or = {
    .codepoints = FB16(538752),
    .glyphs_rle = fonts_blob + 539343,
    .glyphs_off = FB16(547494),
    .glyphs_2x_rle = fonts_blob + 547890,
    .glyphs_2x_off = FB16(554316),
    .widths = fonts_blob + 539146,
    .count = 197,
    .glyph_width = 16,
};
const char *const lang_or_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(554712), [STR_SETTINGS] = FB(554718), [STR_FAIL] = FB(554734),
    [STR_TIMEZONE] = FB(554747), [STR_BRIGHTNESS] = FB(554769), [STR_LED_BLINK] = FB(554791),
    [STR_ROTATE] = FB(554813), [STR_ABOUT] = FB(554844), [STR_LANGUAGE] = FB(554863),
    [STR_DONE] = FB(554876), [STR_BACK] = FB(554898), [STR_CANCEL] = FB(554911),
    [STR_DEL] = FB(554927), [STR_RUNNING] = FB(554943), [STR_ON] = FB(554962),
    [STR_OFF] = FB(554975), [STR_NTS_NO] = FB(554982), [STR_NTS_ATTEMPT] = FB(554995),
    [STR_NTS_REQUIRE] = FB(555008), [STR_WAITING_NTP] = FB(555024),
    [STR_FMT_SYNCED] = FB(555070), [STR_FMT_SYNCING] = FB(555103),
    [STR_FMT_WAITING] = FB(555139), [STR_FMT_PEERS_NOSYNC] = FB(555165),
    [STR_FMT_PEERS_AGO] = FB(555236), [STR_WIFI_SETUP] = FB(555296),
    [STR_SCANNING] = FB(555330), [STR_SCAN_FAILED] = FB(555361), [STR_TAP_RETRY] = FB(555392),
    [STR_SELECT_NETWORK] = FB(555444), [STR_NO_NETWORKS] = FB(555475),
    [STR_NETWORK_LABEL] = FB(555524), [STR_ENTER_PASSWORD] = FB(555540),
    [STR_CONNECTING] = FB(555574), [STR_CONNECTING_TO] = FB(555611),
    [STR_CONNECTED] = FB(555642), [STR_CONNECTION_FAILED] = FB(555661),
    [STR_KB_SPACE] = FB(555695), [STR_KB_GO] = FB(555708), [STR_VERSION] = FB(555711),
    [STR_STATUS] = FB(555733), [STR_READ] = FB(555746), [STR_UPDATE] = FB(555768),
    [STR_RESTARTING] = FB(555784), [STR_OTA_UPDATE] = FB(555809), [STR_NTP_SERVER] = FB(555837),
    [STR_SERVER_LABEL] = FB(555859), [STR_NTP_SETTINGS] = FB(555872),
    [STR_NTP_PRESETS] = FB(555900), [STR_PRESETS] = FB(555928), [STR_BENCHMARK] = FB(555944),
    [STR_STOPPING] = FB(555960), [STR_NTP_STATS] = FB(555979), [STR_UNSYNCED] = FB(556019),
    [STR_SYNCS_LABEL] = FB(556044), [STR_NONE] = FB(556066), [STR_SELECT_REGION] = FB(556079),
    [STR_AGE_LABEL] = FB(556107), [STR_DST] = FB(556129), [STR_NO_DST] = FB(556154),
};
const char *const weekdays_or_shaped[7] = {
    FB(556194), FB(556204), FB(556217), FB(556227), FB(556237), FB(556250), FB(556260),
};
const char *const months_or_shaped[12] = {
    FB(556270), FB(556292), FB(556314), FB(556324), FB(556337), FB(556344), FB(556354),
    FB(556370), FB(556380), FB(556402), FB(556424), FB(556440),
};
const char lang_name_or_shaped[] = ("\xEE" "\x83" "\x82" "\xEE" "\x83" "\x83" "\xEE" "\x80" "\x83" "\xEE" "\x83" "\x84");

// sd: 181 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash sd e0fd28302e3a057a
const display_glyph_font_t font_sd = {
    .codepoints = FB16(556460),
    .glyphs_rle = fonts_blob + 557003,
    .glyphs_off = FB16(563526),
    .glyphs_2x_rle = fonts_blob + 563890,
    .glyphs_2x_off = FB16(568478),
    .widths = fonts_blob + 556822,
    .count = 181,
    .glyph_width = 16,
};
const char *const lang_sd_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(568842), [STR_SETTINGS] = FB(568848), [STR_FAIL] = FB(568870),
    [STR_TIMEZONE] = FB(568886), [STR_BRIGHTNESS] = FB(568923), [STR_LED_BLINK] = FB(568933),
    [STR_ROTATE] = FB(568958), [STR_ABOUT] = FB(568989), [STR_LANGUAGE] = FB(569002),
    [STR_DONE] = FB(569015), [STR_BACK] = FB(569034), [STR_CANCEL] = FB(569050),
    [STR_DEL] = FB(569066), [STR_RUNNING] = FB(569082), [STR_ON] = FB(569119),
    [STR_OFF] = FB(569132), [STR_NTS_NO] = FB(569142), [STR_NTS_ATTEMPT] = FB(569149),
    [STR_NTS_REQUIRE] = FB(569162), [STR_WAITING_NTP] = FB(569175),
    [STR_FMT_SYNCED] = FB(569224), [STR_FMT_SYNCING] = FB(569251),
    [STR_FMT_WAITING] = FB(569302), [STR_FMT_PEERS_NOSYNC] = FB(569331),
    [STR_FMT_PEERS_AGO] = FB(569414), [STR_WIFI_SETUP] = FB(569471),
    [STR_SCANNING] = FB(569508), [STR_SCAN_FAILED] = FB(569545), [STR_TAP_RETRY] = FB(569573),
    [STR_SELECT_NETWORK] = FB(569619), [STR_NO_NETWORKS] = FB(569662),
    [STR_NETWORK_LABEL] = FB(569708), [STR_ENTER_PASSWORD] = FB(569733),
    [STR_CONNECTING] = FB(569785), [STR_CONNECTING_TO] = FB(569816),
    [STR_CONNECTED] = FB(569862), [STR_CONNECTION_FAILED] = FB(569893),
    [STR_KB_SPACE] = FB(569930), [STR_KB_GO] = FB(569946), [STR_VERSION] = FB(569949),
    [STR_STATUS] = FB(569965), [STR_READ] = FB(569981), [STR_UPDATE] = FB(570012),
    [STR_RESTARTING] = FB(570028), [STR_OTA_UPDATE] = FB(570077), [STR_NTP_SERVER] = FB(570105),
    [STR_SERVER_LABEL] = FB(570130), [STR_NTP_SETTINGS] = FB(570146),
    [STR_NTP_PRESETS] = FB(570180), [STR_PRESETS] = FB(570211), [STR_BENCHMARK] = FB(570230),
    [STR_STOPPING] = FB(570243), [STR_NTP_STATS] = FB(570271), [STR_UNSYNCED] = FB(570305),
    [STR_SYNCS_LABEL] = FB(570339), [STR_NONE] = FB(570361), [STR_SELECT_REGION] = FB(570389),
    [STR_AGE_LABEL] = FB(570426), [STR_DST] = FB(570448), [STR_NO_DST] = FB(570491),
};
const char *const weekdays_sd_shaped[7] = {
    FB(570540), FB(570550), FB(570563), FB(570579), FB(570592), FB(570605), FB(570618),
};
const char *const months_sd_shaped[12] = {
    FB(570631), FB(570647), FB(570669), FB(570682), FB(570698), FB(570708), FB(570718),
    FB(570731), FB(570744), FB(570766), FB(570785), FB(570801),
};
const char lang_name_sd_shaped[] = ("\xEE" "\x82" "\xA1" "\xEE" "\x82" "\xB4" "\xEE" "\x80" "\xB5" "\xEE" "\x80" "\x86");

// mai: 193 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash mai a0c2110e905fe8bf
const display_glyph_font_t font_mai = {
    .codepoints = FB16(570818),
    .glyphs_rle = fonts_blob + 571397,
    .glyphs_off = FB16(580148),
    .glyphs_2x_rle = fonts_blob + 580536,
    .glyphs_2x_off = FB16(585032),
    .widths = fonts_blob + 571204,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_mai_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(585420), [STR_SETTINGS] = FB(585426), [STR_FAIL] = FB(585439),
    [STR_TIMEZONE] = FB(585452), [STR_BRIGHTNESS] = FB(585468), [STR_LED_BLINK] = FB(585478),
    [STR_ROTATE] = FB(585500), [STR_ABOUT] = FB(585522), [STR_LANGUAGE] = FB(585535),
    [STR_DONE] = FB(585548), [STR_BACK] = FB(585561), [STR_CANCEL] = FB(585574),
    [STR_DEL] = FB(585581), [STR_RUNNING] = FB(585591), [STR_ON] = FB(585625),
    [STR_OFF] = FB(585635), [STR_NTS_NO] = FB(585642), [STR_NTS_ATTEMPT] = FB(585652),
    [STR_NTS_REQUIRE] = FB(585665), [STR_WAITING_NTP] = FB(585678),
    [STR_FMT_SYNCED] = FB(585721), [STR_FMT_SYNCING] = FB(585748),
    [STR_FMT_WAITING] = FB(585790), [STR_FMT_PEERS_NOSYNC] = FB(585816),
    [STR_FMT_PEERS_AGO] = FB(585884), [STR_WIFI_SETUP] = FB(585941),
    [STR_SCANNING] = FB(585969), [STR_SCAN_FAILED] = FB(586003), [STR_TAP_RETRY] = FB(586028),
    [STR_SELECT_NETWORK] = FB(586077), [STR_NO_NETWORKS] = FB(586096),
    [STR_NETWORK_LABEL] = FB(586130), [STR_ENTER_PASSWORD] = FB(586146),
    [STR_CONNECTING] = FB(586171), [STR_CONNECTING_TO] = FB(586190),
    [STR_CONNECTED] = FB(586215), [STR_CONNECTION_FAILED] = FB(586231),
    [STR_KB_SPACE] = FB(586259), [STR_KB_GO] = FB(586266), [STR_VERSION] = FB(586269),
    [STR_STATUS] = FB(586285), [STR_READ] = FB(586301), [STR_UPDATE] = FB(586320),
    [STR_RESTARTING] = FB(586330), [STR_OTA_UPDATE] = FB(586370), [STR_NTP_SERVER] = FB(586392),
    [STR_SERVER_LABEL] = FB(586411), [STR_NTP_SETTINGS] = FB(586421),
    [STR_NTP_PRESETS] = FB(586446), [STR_PRESETS] = FB(586471), [STR_BENCHMARK] = FB(586484),
    [STR_STOPPING] = FB(586491), [STR_NTP_STATS] = FB(586513), [STR_UNSYNCED] = FB(586541),
    [STR_SYNCS_LABEL] = FB(586566), [STR_NONE] = FB(586591), [STR_SELECT_REGION] = FB(586616),
    [STR_AGE_LABEL] = FB(586626), [STR_DST] = FB(586642), [STR_NO_DST] = FB(586664),
};
const char *const weekdays_mai_shaped[7] = {
    FB(586698), FB(586708), FB(586718), FB(586725), FB(586729), FB(586733), FB(586740),
};
const char *const months_mai_shaped[12] = {
    FB(586750), FB(586760), FB(586770), FB(586780), FB(586787), FB(586794), FB(586798),
    FB(586808), FB(586818), FB(586831), FB(586841), FB(586851),
};
const char lang_name_mai_shaped[] = ("\xEE" "\x82" "\xBE" "\xEE" "\x82" "\xBF" "\xEE" "\x83" "\x80" "\xEE" "\x81" "\x80");

