// Generated by tools/gen_fonts.swift; do not edit by hand.
// Bulk glyph and string data lives in fonts.bin (embedded into the app
// image via EMBED_FILES); everything here is offsets into that blob.
#include "fonts.h"

#ifndef FONTS_BLOB_HOST
extern const uint8_t fonts_blob[] __asm__("_binary_fonts_bin_start");
#else
extern const uint8_t fonts_blob[];  // host harness provides the blob
#endif

// Pointer-into-blob shorthands: FB is a string, FB16 a uint16 table.
#define FB(off)   ((const char *)(fonts_blob + (off)))
#define FB16(off) ((const uint16_t *)(const void *)(fonts_blob + (off)))
// hy: 57 glyphs (Noto Sans Armenian)
const display_glyph_font_t font_hy = {
    .codepoints = FB16(0),
    .glyphs_rle = fonts_blob + 114,
    .glyphs_off = FB16(2570),
    .glyphs_2x_rle = fonts_blob + 2686,
    .glyphs_2x_off = FB16(4948),
    .count = 57,
    .glyph_width = 10,
};
// ja: 112 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_ja = {
    .codepoints = FB16(5064),
    .glyphs_rle = fonts_blob + 5288,
    .glyphs_off = FB16(14654),
    .glyphs_2x_rle = fonts_blob + 14880,
    .glyphs_2x_off = FB16(16824),
    .count = 112,
    .glyph_width = 16,
};
// ka: 29 glyphs (Helvetica)
const display_glyph_font_t font_ka = {
    .codepoints = FB16(17050),
    .glyphs_rle = fonts_blob + 17108,
    .glyphs_off = FB16(18742),
    .glyphs_2x_rle = fonts_blob + 18802,
    .glyphs_2x_off = FB16(21554),
    .count = 29,
    .glyph_width = 10,
};
// ko: 104 glyphs (Apple SD Gothic Neo)
const display_glyph_font_t font_ko = {
    .codepoints = FB16(21614),
    .glyphs_rle = fonts_blob + 21822,
    .glyphs_off = FB16(29544),
    .glyphs_2x_rle = fonts_blob + 29754,
    .glyphs_2x_off = FB16(31252),
    .count = 104,
    .glyph_width = 16,
};
// yue: 108 glyphs (PingFang HK)
const display_glyph_font_t font_yue = {
    .codepoints = FB16(31462),
    .glyphs_rle = fonts_blob + 31678,
    .glyphs_off = FB16(40980),
    .glyphs_2x_rle = fonts_blob + 41198,
    .glyphs_2x_off = FB16(42626),
    .count = 108,
    .glyph_width = 16,
};
// zh: 114 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_zh = {
    .codepoints = FB16(42844),
    .glyphs_rle = fonts_blob + 43072,
    .glyphs_off = FB16(53400),
    .glyphs_2x_rle = fonts_blob + 53630,
    .glyphs_2x_off = FB16(55290),
    .count = 114,
    .glyph_width = 16,
};
// zh_hant: 115 glyphs (PingFang TC)
const display_glyph_font_t font_zh_hant = {
    .codepoints = FB16(55520),
    .glyphs_rle = fonts_blob + 55750,
    .glyphs_off = FB16(65668),
    .glyphs_2x_rle = fonts_blob + 65900,
    .glyphs_2x_off = FB16(67506),
    .count = 115,
    .glyph_width = 16,
};
// base: ASCII plus 272 supplementary glyphs (Menlo)
const uint8_t *const font_base_ascii_rle = fonts_blob + 67738;
const uint16_t *const font_base_ascii_off = FB16(71006);
const uint8_t *const font_base_ascii_2x_rle = fonts_blob + 71198;
const uint16_t *const font_base_ascii_2x_off = FB16(76926);
const uint16_t *const font_base_ext_cp = FB16(77118);
const uint8_t *const font_base_ext_rle = fonts_blob + 77662;
const uint16_t *const font_base_ext_off = FB16(89016);
const uint8_t *const font_base_ext_2x_rle = fonts_blob + 89562;
const uint16_t *const font_base_ext_2x_off = FB16(102798);
const uint16_t font_base_ext_count = 272;
// ar: 178 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ar 3321610560661b54
const display_glyph_font_t font_ar = {
    .codepoints = FB16(103344),
    .glyphs_rle = fonts_blob + 103878,
    .glyphs_off = FB16(110570),
    .glyphs_2x_rle = fonts_blob + 110928,
    .glyphs_2x_off = FB16(115284),
    .widths = fonts_blob + 103700,
    .count = 178,
    .glyph_width = 16,
};
const char *const lang_ar_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(115642), [STR_WIFI] = FB(115667), [STR_FAIL] = FB(115673),
    [STR_TIMEZONE] = FB(115683), [STR_BRIGHTNESS] = FB(115726), [STR_LED_BLINK] = FB(115745),
    [STR_ROTATE] = FB(115770), [STR_ABOUT] = FB(115798), [STR_LANGUAGE] = FB(115808),
    [STR_DONE] = FB(115824), [STR_BACK] = FB(115831), [STR_CANCEL] = FB(115844),
    [STR_DEL] = FB(115860), [STR_RUNNING] = FB(115870), [STR_ON] = FB(115883),
    [STR_OFF] = FB(115896), [STR_NTS_NO] = FB(115909), [STR_NTS_ATTEMPT] = FB(115913),
    [STR_NTS_REQUIRE] = FB(115932), [STR_WAITING_NTP] = FB(115948),
    [STR_FMT_SYNCED] = FB(115991), [STR_FMT_SYNCING] = FB(116018),
    [STR_FMT_WAITING] = FB(116045), [STR_WIFI_SETUP] = FB(116074), [STR_SCANNING] = FB(116108),
    [STR_SCAN_FAILED] = FB(116130), [STR_TAP_RETRY] = FB(116158),
    [STR_SELECT_NETWORK] = FB(116213), [STR_NO_NETWORKS] = FB(116247),
    [STR_NETWORK_LABEL] = FB(116284), [STR_ENTER_PASSWORD] = FB(116306),
    [STR_CONNECTING] = FB(116352), [STR_CONNECTING_TO] = FB(116365),
    [STR_CONNECTED] = FB(116393), [STR_CONNECTION_FAILED] = FB(116409),
    [STR_KB_SPACE] = FB(116440), [STR_KB_GO] = FB(116456), [STR_VERSION] = FB(116459),
    [STR_STATUS] = FB(116481), [STR_READ] = FB(116503), [STR_UPDATE] = FB(116516),
    [STR_RESTARTING] = FB(116532), [STR_OTA_UPDATE] = FB(116566), [STR_NTP_SERVER] = FB(116594),
    [STR_SERVER_LABEL] = FB(116619), [STR_NTP_SETTINGS] = FB(116641),
    [STR_NTP_PRESETS] = FB(116675), [STR_PRESETS] = FB(116703), [STR_BENCHMARK] = FB(116719),
    [STR_STOPPING] = FB(116738), [STR_NTP_STATS] = FB(116754), [STR_UNSYNCED] = FB(116788),
    [STR_NONE] = FB(116819), [STR_SELECT_REGION] = FB(116835), [STR_AGE_LABEL] = FB(116869),
    [STR_SYNCS_LABEL] = FB(116897), [STR_FMT_PEERS_NOSYNC] = FB(116928),
    [STR_FMT_PEERS_AGO] = FB(117002), [STR_DST] = FB(117066), [STR_NO_DST] = FB(117097),
};
const char *const weekdays_ar_shaped[7] = {
    FB(117137), FB(117150), FB(117166), FB(117188), FB(117210), FB(117229), FB(117248),
};
const char *const months_ar_shaped[12] = {
    FB(117264), FB(117274), FB(117284), FB(117294), FB(117304), FB(117314), FB(117324),
    FB(117334), FB(117344), FB(117354), FB(117364), FB(117374),
};
const char lang_name_ar_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\xA1" "\xEE" "\x80" "\xB8" "\xEE" "\x80" "\xAB" "\xEE" "\x80" "\xAC");

// fa: 211 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash fa dbfe059c4f36839d
const display_glyph_font_t font_fa = {
    .codepoints = FB16(117384),
    .glyphs_rle = fonts_blob + 118017,
    .glyphs_off = FB16(126118),
    .glyphs_2x_rle = fonts_blob + 126542,
    .glyphs_2x_off = FB16(132076),
    .widths = fonts_blob + 117806,
    .count = 211,
    .glyph_width = 16,
};
const char *const lang_fa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(132500), [STR_WIFI] = FB(132522), [STR_FAIL] = FB(132528),
    [STR_TIMEZONE] = FB(132538), [STR_BRIGHTNESS] = FB(132572), [STR_LED_BLINK] = FB(132594),
    [STR_ROTATE] = FB(132619), [STR_ABOUT] = FB(132644), [STR_LANGUAGE] = FB(132663),
    [STR_DONE] = FB(132676), [STR_BACK] = FB(132692), [STR_CANCEL] = FB(132711),
    [STR_DEL] = FB(132721), [STR_RUNNING] = FB(132731), [STR_ON] = FB(132765),
    [STR_OFF] = FB(132778), [STR_NTS_NO] = FB(132794), [STR_NTS_ATTEMPT] = FB(132804),
    [STR_NTS_REQUIRE] = FB(132814), [STR_WAITING_NTP] = FB(132830),
    [STR_FMT_SYNCED] = FB(132879), [STR_FMT_SYNCING] = FB(132903),
    [STR_FMT_WAITING] = FB(132936), [STR_WIFI_SETUP] = FB(132965), [STR_SCANNING] = FB(132999),
    [STR_SCAN_FAILED] = FB(133024), [STR_TAP_RETRY] = FB(133061),
    [STR_SELECT_NETWORK] = FB(133125), [STR_NO_NETWORKS] = FB(133159),
    [STR_NETWORK_LABEL] = FB(133202), [STR_ENTER_PASSWORD] = FB(133218),
    [STR_CONNECTING] = FB(133279), [STR_CONNECTING_TO] = FB(133316),
    [STR_CONNECTED] = FB(133341), [STR_CONNECTION_FAILED] = FB(133366),
    [STR_KB_SPACE] = FB(133403), [STR_KB_GO] = FB(133419), [STR_VERSION] = FB(133422),
    [STR_STATUS] = FB(133438), [STR_READ] = FB(133457), [STR_UPDATE] = FB(133479),
    [STR_RESTARTING] = FB(133507), [STR_OTA_UPDATE] = FB(133547), [STR_NTP_SERVER] = FB(133587),
    [STR_SERVER_LABEL] = FB(133612), [STR_NTP_SETTINGS] = FB(133628),
    [STR_NTP_PRESETS] = FB(133662), [STR_PRESETS] = FB(133696), [STR_BENCHMARK] = FB(133721),
    [STR_STOPPING] = FB(133737), [STR_NTP_STATS] = FB(133750), [STR_UNSYNCED] = FB(133775),
    [STR_NONE] = FB(133797), [STR_SELECT_REGION] = FB(133807), [STR_AGE_LABEL] = FB(133844),
    [STR_SYNCS_LABEL] = FB(133866), [STR_FMT_PEERS_NOSYNC] = FB(133894),
    [STR_FMT_PEERS_AGO] = FB(133974), [STR_DST] = FB(134034), [STR_NO_DST] = FB(134074),
};
const char *const weekdays_fa_shaped[7] = {
    FB(134129), FB(134148), FB(134167), FB(134183), FB(134208), FB(134230), FB(134243),
};
const char *const months_fa_shaped[12] = {
    FB(134256), FB(134278), FB(134303), FB(134319), FB(134329), FB(134345), FB(134364),
    FB(134374), FB(134387), FB(134397), FB(134404), FB(134417),
};
const char lang_name_fa_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x83" "\x88" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\x81" "\xEE" "\x81" "\xB2");

// he: 98 shaped cluster glyphs (Arial Hebrew)
// shaped-source-hash he 04d99dae314644b5
const display_glyph_font_t font_he = {
    .codepoints = FB16(134434),
    .glyphs_rle = fonts_blob + 134728,
    .glyphs_off = FB16(138424),
    .glyphs_2x_rle = fonts_blob + 138622,
    .glyphs_2x_off = FB16(141526),
    .widths = fonts_blob + 134630,
    .count = 98,
    .glyph_width = 16,
};
const char *const lang_he_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(141724), [STR_WIFI] = FB(141743), [STR_FAIL] = FB(141749),
    [STR_TIMEZONE] = FB(141762), [STR_BRIGHTNESS] = FB(141787), [STR_LED_BLINK] = FB(141806),
    [STR_ROTATE] = FB(141834), [STR_ABOUT] = FB(141862), [STR_LANGUAGE] = FB(141878),
    [STR_DONE] = FB(141888), [STR_BACK] = FB(141901), [STR_CANCEL] = FB(141914),
    [STR_DEL] = FB(141930), [STR_RUNNING] = FB(141940), [STR_ON] = FB(141953),
    [STR_OFF] = FB(141966), [STR_NTS_NO] = FB(141979), [STR_NTS_ATTEMPT] = FB(141986),
    [STR_NTS_REQUIRE] = FB(141996), [STR_WAITING_NTP] = FB(142009),
    [STR_FMT_SYNCED] = FB(142052), [STR_FMT_SYNCING] = FB(142082),
    [STR_FMT_WAITING] = FB(142112), [STR_WIFI_SETUP] = FB(142138), [STR_SCANNING] = FB(142172),
    [STR_SCAN_FAILED] = FB(142194), [STR_TAP_RETRY] = FB(142231),
    [STR_SELECT_NETWORK] = FB(142280), [STR_NO_NETWORKS] = FB(142302),
    [STR_NETWORK_LABEL] = FB(142345), [STR_ENTER_PASSWORD] = FB(142358),
    [STR_CONNECTING] = FB(142386), [STR_CONNECTING_TO] = FB(142402),
    [STR_CONNECTED] = FB(142427), [STR_CONNECTION_FAILED] = FB(142446),
    [STR_KB_SPACE] = FB(142480), [STR_KB_GO] = FB(142493), [STR_VERSION] = FB(142496),
    [STR_STATUS] = FB(142512), [STR_READ] = FB(142525), [STR_UPDATE] = FB(142541),
    [STR_RESTARTING] = FB(142554), [STR_OTA_UPDATE] = FB(142585), [STR_NTP_SERVER] = FB(142613),
    [STR_SERVER_LABEL] = FB(142635), [STR_NTP_SETTINGS] = FB(142648),
    [STR_NTP_PRESETS] = FB(142679), [STR_PRESETS] = FB(142713), [STR_BENCHMARK] = FB(142738),
    [STR_STOPPING] = FB(142754), [STR_NTP_STATS] = FB(142767), [STR_UNSYNCED] = FB(142807),
    [STR_NONE] = FB(142838), [STR_SELECT_REGION] = FB(142848), [STR_AGE_LABEL] = FB(142873),
    [STR_SYNCS_LABEL] = FB(142895), [STR_FMT_PEERS_NOSYNC] = FB(142926),
    [STR_FMT_PEERS_AGO] = FB(143009), [STR_DST] = FB(143079), [STR_NO_DST] = FB(143104),
};
const char *const weekdays_he_shaped[7] = {
    FB(143141), FB(143160), FB(143179), FB(143198), FB(143217), FB(143236), FB(143255),
};
const char *const months_he_shaped[12] = {
    FB(143265), FB(143275), FB(143285), FB(143295), FB(143305), FB(143315), FB(143325),
    FB(143335), FB(143345), FB(143355), FB(143365), FB(143375),
};
const char lang_name_he_shaped[] = ("\xEE" "\x80" "\x80" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x82" "\xEE" "\x80" "\x98" "\xEE" "\x80" "\xA6");

// hi: 186 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash hi fb71ec9a96a8553e
const display_glyph_font_t font_hi = {
    .codepoints = FB16(143386),
    .glyphs_rle = fonts_blob + 143944,
    .glyphs_off = FB16(152306),
    .glyphs_2x_rle = fonts_blob + 152680,
    .glyphs_2x_off = FB16(157032),
    .widths = fonts_blob + 143758,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_hi_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(157406), [STR_WIFI] = FB(157419), [STR_FAIL] = FB(157425),
    [STR_TIMEZONE] = FB(157438), [STR_BRIGHTNESS] = FB(157454), [STR_LED_BLINK] = FB(157464),
    [STR_ROTATE] = FB(157489), [STR_ABOUT] = FB(157514), [STR_LANGUAGE] = FB(157536),
    [STR_DONE] = FB(157549), [STR_BACK] = FB(157568), [STR_CANCEL] = FB(157581),
    [STR_DEL] = FB(157588), [STR_RUNNING] = FB(157604), [STR_ON] = FB(157623),
    [STR_OFF] = FB(157633), [STR_NTS_NO] = FB(157637), [STR_NTS_ATTEMPT] = FB(157647),
    [STR_NTS_REQUIRE] = FB(157660), [STR_WAITING_NTP] = FB(157673),
    [STR_FMT_SYNCED] = FB(157719), [STR_FMT_SYNCING] = FB(157740),
    [STR_FMT_WAITING] = FB(157782), [STR_WIFI_SETUP] = FB(157808), [STR_SCANNING] = FB(157836),
    [STR_SCAN_FAILED] = FB(157867), [STR_TAP_RETRY] = FB(157892),
    [STR_SELECT_NETWORK] = FB(157935), [STR_NO_NETWORKS] = FB(157954),
    [STR_NETWORK_LABEL] = FB(157991), [STR_ENTER_PASSWORD] = FB(158007),
    [STR_CONNECTING] = FB(158035), [STR_CONNECTING_TO] = FB(158057),
    [STR_CONNECTED] = FB(158082), [STR_CONNECTION_FAILED] = FB(158101),
    [STR_KB_SPACE] = FB(158129), [STR_KB_GO] = FB(158136), [STR_VERSION] = FB(158139),
    [STR_STATUS] = FB(158155), [STR_READ] = FB(158171), [STR_UPDATE] = FB(158184),
    [STR_RESTARTING] = FB(158194), [STR_OTA_UPDATE] = FB(158210), [STR_NTP_SERVER] = FB(158232),
    [STR_SERVER_LABEL] = FB(158251), [STR_NTP_SETTINGS] = FB(158261),
    [STR_NTP_PRESETS] = FB(158286), [STR_PRESETS] = FB(158317), [STR_BENCHMARK] = FB(158336),
    [STR_STOPPING] = FB(158352), [STR_NTP_STATS] = FB(158371), [STR_UNSYNCED] = FB(158396),
    [STR_NONE] = FB(158421), [STR_SELECT_REGION] = FB(158443), [STR_AGE_LABEL] = FB(158453),
    [STR_SYNCS_LABEL] = FB(158469), [STR_FMT_PEERS_NOSYNC] = FB(158494),
    [STR_FMT_PEERS_AGO] = FB(158562), [STR_DST] = FB(158616), [STR_NO_DST] = FB(158638),
};
const char *const weekdays_hi_shaped[7] = {
    FB(158672), FB(158682), FB(158692), FB(158699), FB(158703), FB(158707), FB(158714),
};
const char *const months_hi_shaped[12] = {
    FB(158724), FB(158734), FB(158744), FB(158754), FB(158761), FB(158768), FB(158772),
    FB(158782), FB(158792), FB(158805), FB(158818), FB(158828),
};
const char lang_name_hi_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\xA5" "\xEE" "\x82" "\xB9" "\xEE" "\x80" "\xA1");

// bn: 169 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash bn cf309888208f71a7
const display_glyph_font_t font_bn = {
    .codepoints = FB16(158842),
    .glyphs_rle = fonts_blob + 159349,
    .glyphs_off = FB16(166532),
    .glyphs_2x_rle = fonts_blob + 166872,
    .glyphs_2x_off = FB16(171716),
    .widths = fonts_blob + 159180,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_bn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(172056), [STR_WIFI] = FB(172072), [STR_FAIL] = FB(172078),
    [STR_TIMEZONE] = FB(172088), [STR_BRIGHTNESS] = FB(172110), [STR_LED_BLINK] = FB(172126),
    [STR_ROTATE] = FB(172148), [STR_ABOUT] = FB(172179), [STR_LANGUAGE] = FB(172195),
    [STR_DONE] = FB(172208), [STR_BACK] = FB(172218), [STR_CANCEL] = FB(172234),
    [STR_DEL] = FB(172250), [STR_RUNNING] = FB(172260), [STR_ON] = FB(172273),
    [STR_OFF] = FB(172283), [STR_NTS_NO] = FB(172290), [STR_NTS_ATTEMPT] = FB(172297),
    [STR_NTS_REQUIRE] = FB(172310), [STR_WAITING_NTP] = FB(172326),
    [STR_FMT_SYNCED] = FB(172366), [STR_FMT_SYNCING] = FB(172387),
    [STR_FMT_WAITING] = FB(172420), [STR_WIFI_SETUP] = FB(172446), [STR_SCANNING] = FB(172480),
    [STR_SCAN_FAILED] = FB(172502), [STR_TAP_RETRY] = FB(172527),
    [STR_SELECT_NETWORK] = FB(172582), [STR_NO_NETWORKS] = FB(172625),
    [STR_NETWORK_LABEL] = FB(172662), [STR_ENTER_PASSWORD] = FB(172690),
    [STR_CONNECTING] = FB(172727), [STR_CONNECTING_TO] = FB(172758),
    [STR_CONNECTED] = FB(172792), [STR_CONNECTION_FAILED] = FB(172811),
    [STR_KB_SPACE] = FB(172842), [STR_KB_GO] = FB(172852), [STR_VERSION] = FB(172855),
    [STR_STATUS] = FB(172874), [STR_READ] = FB(172890), [STR_UPDATE] = FB(172903),
    [STR_RESTARTING] = FB(172919), [STR_OTA_UPDATE] = FB(172944), [STR_NTP_SERVER] = FB(172972),
    [STR_SERVER_LABEL] = FB(173003), [STR_NTP_SETTINGS] = FB(173025),
    [STR_NTP_PRESETS] = FB(173053), [STR_PRESETS] = FB(173087), [STR_BENCHMARK] = FB(173109),
    [STR_STOPPING] = FB(173125), [STR_NTP_STATS] = FB(173141), [STR_UNSYNCED] = FB(173181),
    [STR_NONE] = FB(173206), [STR_SELECT_REGION] = FB(173231), [STR_AGE_LABEL] = FB(173259),
    [STR_SYNCS_LABEL] = FB(173281), [STR_FMT_PEERS_NOSYNC] = FB(173306),
    [STR_FMT_PEERS_AGO] = FB(173386), [STR_DST] = FB(173452), [STR_NO_DST] = FB(173474),
};
const char *const weekdays_bn_shaped[7] = {
    FB(173508), FB(173518), FB(173531), FB(173541), FB(173551), FB(173561), FB(173568),
};
const char *const months_bn_shaped[12] = {
    FB(173578), FB(173588), FB(173598), FB(173611), FB(173621), FB(173628), FB(173635),
    FB(173645), FB(173652), FB(173662), FB(173675), FB(173685),
};
const char lang_name_bn_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\x98" "\xEE" "\x81" "\xA5" "\xEE" "\x80" "\x8C" "\xEE" "\x80" "\x98");

// th: 162 shaped cluster glyphs (Thonburi)
// shaped-source-hash th 0031e23b06de2ba5
const display_glyph_font_t font_th = {
    .codepoints = FB16(173698),
    .glyphs_rle = fonts_blob + 174184,
    .glyphs_off = FB16(179966),
    .glyphs_2x_rle = fonts_blob + 180292,
    .glyphs_2x_off = FB16(182442),
    .widths = fonts_blob + 174022,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_th_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(182768), [STR_WIFI] = FB(182790), [STR_FAIL] = FB(182796),
    [STR_TIMEZONE] = FB(182815), [STR_BRIGHTNESS] = FB(182837), [STR_LED_BLINK] = FB(182862),
    [STR_ROTATE] = FB(182890), [STR_ABOUT] = FB(182912), [STR_LANGUAGE] = FB(182931),
    [STR_DONE] = FB(182944), [STR_BACK] = FB(182957), [STR_CANCEL] = FB(182967),
    [STR_DEL] = FB(182983), [STR_RUNNING] = FB(182990), [STR_ON] = FB(183012),
    [STR_OFF] = FB(183022), [STR_NTS_NO] = FB(183029), [STR_NTS_ATTEMPT] = FB(183036),
    [STR_NTS_REQUIRE] = FB(183046), [STR_WAITING_NTP] = FB(183059),
    [STR_FMT_SYNCED] = FB(183087), [STR_FMT_SYNCING] = FB(183114),
    [STR_FMT_WAITING] = FB(183141), [STR_WIFI_SETUP] = FB(183158), [STR_SCANNING] = FB(183189),
    [STR_SCAN_FAILED] = FB(183220), [STR_TAP_RETRY] = FB(183251),
    [STR_SELECT_NETWORK] = FB(183288), [STR_NO_NETWORKS] = FB(183322),
    [STR_NETWORK_LABEL] = FB(183356), [STR_ENTER_PASSWORD] = FB(183381),
    [STR_CONNECTING] = FB(183406), [STR_CONNECTING_TO] = FB(183434),
    [STR_CONNECTED] = FB(183459), [STR_CONNECTION_FAILED] = FB(183490),
    [STR_KB_SPACE] = FB(183527), [STR_KB_GO] = FB(183549), [STR_VERSION] = FB(183552),
    [STR_STATUS] = FB(183574), [STR_READ] = FB(183593), [STR_UPDATE] = FB(183606),
    [STR_RESTARTING] = FB(183622), [STR_OTA_UPDATE] = FB(183650), [STR_NTP_SERVER] = FB(183678),
    [STR_SERVER_LABEL] = FB(183715), [STR_NTP_SETTINGS] = FB(183743),
    [STR_NTP_PRESETS] = FB(183768), [STR_PRESETS] = FB(183799), [STR_BENCHMARK] = FB(183818),
    [STR_STOPPING] = FB(183834), [STR_NTP_STATS] = FB(183853), [STR_UNSYNCED] = FB(183875),
    [STR_NONE] = FB(183891), [STR_SELECT_REGION] = FB(183901), [STR_AGE_LABEL] = FB(183929),
    [STR_SYNCS_LABEL] = FB(183951), [STR_FMT_PEERS_NOSYNC] = FB(183973),
    [STR_FMT_PEERS_AGO] = FB(184038), [STR_DST] = FB(184101), [STR_NO_DST] = FB(184132),
};
const char *const weekdays_th_shaped[7] = {
    FB(184172), FB(184182), FB(184189), FB(184196), FB(184203), FB(184213), FB(184220),
};
const char *const months_th_shaped[12] = {
    FB(184227), FB(184240), FB(184253), FB(184266), FB(184282), FB(184295), FB(184308),
    FB(184321), FB(184334), FB(184347), FB(184360), FB(184373),
};
const char lang_name_th_shaped[] = ("\xEE" "\x80" "\xB9" "\xEE" "\x82" "\xA1" "\xEE" "\x82" "\x9E");

// ur: 195 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ur e35c9ea86d6afe82
const display_glyph_font_t font_ur = {
    .codepoints = FB16(184386),
    .glyphs_rle = fonts_blob + 184971,
    .glyphs_off = FB16(191972),
    .glyphs_2x_rle = fonts_blob + 192364,
    .glyphs_2x_off = FB16(196538),
    .widths = fonts_blob + 184776,
    .count = 195,
    .glyph_width = 16,
};
const char *const lang_ur_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(196930), [STR_WIFI] = FB(196952), [STR_FAIL] = FB(196958),
    [STR_TIMEZONE] = FB(196974), [STR_BRIGHTNESS] = FB(196999), [STR_LED_BLINK] = FB(197009),
    [STR_ROTATE] = FB(197034), [STR_ABOUT] = FB(197068), [STR_LANGUAGE] = FB(197084),
    [STR_DONE] = FB(197097), [STR_BACK] = FB(197116), [STR_CANCEL] = FB(197129),
    [STR_DEL] = FB(197145), [STR_RUNNING] = FB(197164), [STR_ON] = FB(197192),
    [STR_OFF] = FB(197199), [STR_NTS_NO] = FB(197206), [STR_NTS_ATTEMPT] = FB(197219),
    [STR_NTS_REQUIRE] = FB(197232), [STR_WAITING_NTP] = FB(197245),
    [STR_FMT_SYNCED] = FB(197294), [STR_FMT_SYNCING] = FB(197324),
    [STR_FMT_WAITING] = FB(197357), [STR_WIFI_SETUP] = FB(197386), [STR_SCANNING] = FB(197423),
    [STR_SCAN_FAILED] = FB(197457), [STR_TAP_RETRY] = FB(197485),
    [STR_SELECT_NETWORK] = FB(197573), [STR_NO_NETWORKS] = FB(197610),
    [STR_NETWORK_LABEL] = FB(197662), [STR_ENTER_PASSWORD] = FB(197687),
    [STR_CONNECTING] = FB(197736), [STR_CONNECTING_TO] = FB(197782),
    [STR_CONNECTED] = FB(197831), [STR_CONNECTION_FAILED] = FB(197850),
    [STR_KB_SPACE] = FB(197884), [STR_KB_GO] = FB(197909), [STR_VERSION] = FB(197912),
    [STR_STATUS] = FB(197928), [STR_READ] = FB(197944), [STR_UPDATE] = FB(197960),
    [STR_RESTARTING] = FB(197979), [STR_OTA_UPDATE] = FB(198013), [STR_NTP_SERVER] = FB(198044),
    [STR_SERVER_LABEL] = FB(198069), [STR_NTP_SETTINGS] = FB(198085),
    [STR_NTP_PRESETS] = FB(198119), [STR_PRESETS] = FB(198153), [STR_BENCHMARK] = FB(198175),
    [STR_STOPPING] = FB(198188), [STR_NTP_STATS] = FB(198216), [STR_UNSYNCED] = FB(198265),
    [STR_NONE] = FB(198299), [STR_SELECT_REGION] = FB(198324), [STR_AGE_LABEL] = FB(198349),
    [STR_SYNCS_LABEL] = FB(198371), [STR_FMT_PEERS_NOSYNC] = FB(198393),
    [STR_FMT_PEERS_AGO] = FB(198479), [STR_DST] = FB(198542), [STR_NO_DST] = FB(198573),
};
const char *const weekdays_ur_shaped[7] = {
    FB(198619), FB(198635), FB(198645), FB(198658), FB(198668), FB(198687), FB(198700),
};
const char *const months_ur_shaped[12] = {
    FB(198713), FB(198729), FB(198745), FB(198758), FB(198774), FB(198784), FB(198794),
    FB(198810), FB(198823), FB(198839), FB(198858), FB(198874),
};
const char lang_name_ur_shaped[] = ("\xEE" "\x80" "\x8B" "\xEE" "\x83" "\x82" "\xEE" "\x81" "\x84" "\xEE" "\x81" "\x88");

// mr: 179 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash mr 0004a1284112fffe
const display_glyph_font_t font_mr = {
    .codepoints = FB16(198890),
    .glyphs_rle = fonts_blob + 199427,
    .glyphs_off = FB16(207564),
    .glyphs_2x_rle = fonts_blob + 207924,
    .glyphs_2x_off = FB16(212616),
    .widths = fonts_blob + 199248,
    .count = 179,
    .glyph_width = 16,
};
const char *const lang_mr_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(212976), [STR_WIFI] = FB(212989), [STR_FAIL] = FB(212995),
    [STR_TIMEZONE] = FB(213011), [STR_BRIGHTNESS] = FB(213021), [STR_LED_BLINK] = FB(213031),
    [STR_ROTATE] = FB(213056), [STR_ABOUT] = FB(213084), [STR_LANGUAGE] = FB(213103),
    [STR_DONE] = FB(213116), [STR_BACK] = FB(213126), [STR_CANCEL] = FB(213136),
    [STR_DEL] = FB(213143), [STR_RUNNING] = FB(213156), [STR_ON] = FB(213169),
    [STR_OFF] = FB(213179), [STR_NTS_NO] = FB(213183), [STR_NTS_ATTEMPT] = FB(213196),
    [STR_NTS_REQUIRE] = FB(213206), [STR_WAITING_NTP] = FB(213219),
    [STR_FMT_SYNCED] = FB(213265), [STR_FMT_SYNCING] = FB(213286),
    [STR_FMT_WAITING] = FB(213328), [STR_WIFI_SETUP] = FB(213354), [STR_SCANNING] = FB(213382),
    [STR_SCAN_FAILED] = FB(213413), [STR_TAP_RETRY] = FB(213441),
    [STR_SELECT_NETWORK] = FB(213499), [STR_NO_NETWORKS] = FB(213530),
    [STR_NETWORK_LABEL] = FB(213558), [STR_ENTER_PASSWORD] = FB(213574),
    [STR_CONNECTING] = FB(213602), [STR_CONNECTING_TO] = FB(213624),
    [STR_CONNECTED] = FB(213649), [STR_CONNECTION_FAILED] = FB(213662),
    [STR_KB_SPACE] = FB(213693), [STR_KB_GO] = FB(213700), [STR_VERSION] = FB(213703),
    [STR_STATUS] = FB(213716), [STR_READ] = FB(213732), [STR_UPDATE] = FB(213745),
    [STR_RESTARTING] = FB(213755), [STR_OTA_UPDATE] = FB(213768), [STR_NTP_SERVER] = FB(213790),
    [STR_SERVER_LABEL] = FB(213812), [STR_NTP_SETTINGS] = FB(213825),
    [STR_NTP_PRESETS] = FB(213850), [STR_PRESETS] = FB(213881), [STR_BENCHMARK] = FB(213900),
    [STR_STOPPING] = FB(213916), [STR_NTP_STATS] = FB(213935), [STR_UNSYNCED] = FB(213966),
    [STR_NONE] = FB(213994), [STR_SELECT_REGION] = FB(214022), [STR_AGE_LABEL] = FB(214050),
    [STR_SYNCS_LABEL] = FB(214069), [STR_FMT_PEERS_NOSYNC] = FB(214094),
    [STR_FMT_PEERS_AGO] = FB(214168), [STR_DST] = FB(214225), [STR_NO_DST] = FB(214247),
};
const char *const weekdays_mr_shaped[7] = {
    FB(214284), FB(214294), FB(214304), FB(214311), FB(214315), FB(214319), FB(214326),
};
const char *const months_mr_shaped[12] = {
    FB(214336), FB(214346), FB(214356), FB(214366), FB(214376), FB(214380), FB(214384),
    FB(214391), FB(214398), FB(214405), FB(214415), FB(214425),
};
const char lang_name_mr_shaped[] = ("\xEE" "\x80" "\x9D" "\xEE" "\x80" "\x97" "\xEE" "\x80" "\x9E" "\xEE" "\x82" "\xB2" "\xEE" "\x80" "\xB4");

// ta: 158 shaped cluster glyphs (Tamil Sangam MN)
// shaped-source-hash ta a2efda2869793b62
const display_glyph_font_t font_ta = {
    .codepoints = FB16(214436),
    .glyphs_rle = fonts_blob + 214910,
    .glyphs_off = FB16(222188),
    .glyphs_2x_rle = fonts_blob + 222506,
    .glyphs_2x_off = FB16(227798),
    .widths = fonts_blob + 214752,
    .count = 158,
    .glyph_width = 16,
};
const char *const lang_ta_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(228116), [STR_WIFI] = FB(228138), [STR_FAIL] = FB(228144),
    [STR_TIMEZONE] = FB(228160), [STR_BRIGHTNESS] = FB(228188), [STR_LED_BLINK] = FB(228201),
    [STR_ROTATE] = FB(228226), [STR_ABOUT] = FB(228251), [STR_LANGUAGE] = FB(228261),
    [STR_DONE] = FB(228274), [STR_BACK] = FB(228290), [STR_CANCEL] = FB(228297),
    [STR_DEL] = FB(228307), [STR_RUNNING] = FB(228317), [STR_ON] = FB(228339),
    [STR_OFF] = FB(228352), [STR_NTS_NO] = FB(228362), [STR_NTS_ATTEMPT] = FB(228375),
    [STR_NTS_REQUIRE] = FB(228388), [STR_WAITING_NTP] = FB(228407),
    [STR_FMT_SYNCED] = FB(228450), [STR_FMT_SYNCING] = FB(228477),
    [STR_FMT_WAITING] = FB(228510), [STR_WIFI_SETUP] = FB(228542), [STR_SCANNING] = FB(228576),
    [STR_SCAN_FAILED] = FB(228604), [STR_TAP_RETRY] = FB(228635),
    [STR_SELECT_NETWORK] = FB(228678), [STR_NO_NETWORKS] = FB(228718),
    [STR_NETWORK_LABEL] = FB(228758), [STR_ENTER_PASSWORD] = FB(228786),
    [STR_CONNECTING] = FB(228832), [STR_CONNECTING_TO] = FB(228854),
    [STR_CONNECTED] = FB(228879), [STR_CONNECTION_FAILED] = FB(228901),
    [STR_KB_SPACE] = FB(228935), [STR_KB_GO] = FB(228954), [STR_VERSION] = FB(228957),
    [STR_STATUS] = FB(228973), [STR_READ] = FB(228986), [STR_UPDATE] = FB(229005),
    [STR_RESTARTING] = FB(229018), [STR_OTA_UPDATE] = FB(229046), [STR_NTP_SERVER] = FB(229077),
    [STR_SERVER_LABEL] = FB(229111), [STR_NTP_SETTINGS] = FB(229136),
    [STR_NTP_PRESETS] = FB(229170), [STR_PRESETS] = FB(229201), [STR_BENCHMARK] = FB(229220),
    [STR_STOPPING] = FB(229239), [STR_NTP_STATS] = FB(229261), [STR_UNSYNCED] = FB(229295),
    [STR_NONE] = FB(229308), [STR_SELECT_REGION] = FB(229327), [STR_AGE_LABEL] = FB(229352),
    [STR_SYNCS_LABEL] = FB(229374), [STR_FMT_PEERS_NOSYNC] = FB(229396),
    [STR_FMT_PEERS_AGO] = FB(229470), [STR_DST] = FB(229527), [STR_NO_DST] = FB(229558),
};
const char *const weekdays_ta_shaped[7] = {
    FB(229604), FB(229617), FB(229627), FB(229640), FB(229650), FB(229663), FB(229676),
};
const char *const months_ta_shaped[12] = {
    FB(229683), FB(229693), FB(229703), FB(229716), FB(229726), FB(229733), FB(229740),
    FB(229750), FB(229760), FB(229773), FB(229783), FB(229793),
};
const char lang_name_ta_shaped[] = ("\xEE" "\x81" "\x9C" "\xEE" "\x80" "\x9B" "\xEE" "\x82" "\x9D");

// te: 217 shaped cluster glyphs (Kohinoor Telugu)
// shaped-source-hash te e2a06a76c473ea8b
const display_glyph_font_t font_te = {
    .codepoints = FB16(229804),
    .glyphs_rle = fonts_blob + 230455,
    .glyphs_off = FB16(239758),
    .glyphs_2x_rle = fonts_blob + 240194,
    .glyphs_2x_off = FB16(245792),
    .widths = fonts_blob + 230238,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_te_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(246228), [STR_WIFI] = FB(246247), [STR_FAIL] = FB(246253),
    [STR_TIMEZONE] = FB(246266), [STR_BRIGHTNESS] = FB(246294), [STR_LED_BLINK] = FB(246310),
    [STR_ROTATE] = FB(246332), [STR_ABOUT] = FB(246354), [STR_LANGUAGE] = FB(246367),
    [STR_DONE] = FB(246374), [STR_BACK] = FB(246384), [STR_CANCEL] = FB(246397),
    [STR_DEL] = FB(246407), [STR_RUNNING] = FB(246423), [STR_ON] = FB(246442),
    [STR_OFF] = FB(246449), [STR_NTS_NO] = FB(246456), [STR_NTS_ATTEMPT] = FB(246463),
    [STR_NTS_REQUIRE] = FB(246482), [STR_WAITING_NTP] = FB(246501),
    [STR_FMT_SYNCED] = FB(246541), [STR_FMT_SYNCING] = FB(246559),
    [STR_FMT_WAITING] = FB(246595), [STR_WIFI_SETUP] = FB(246612), [STR_SCANNING] = FB(246640),
    [STR_SCAN_FAILED] = FB(246668), [STR_TAP_RETRY] = FB(246693),
    [STR_SELECT_NETWORK] = FB(246745), [STR_NO_NETWORKS] = FB(246779),
    [STR_NETWORK_LABEL] = FB(246801), [STR_ENTER_PASSWORD] = FB(246817),
    [STR_CONNECTING] = FB(246842), [STR_CONNECTING_TO] = FB(246873),
    [STR_CONNECTED] = FB(246907), [STR_CONNECTION_FAILED] = FB(246938),
    [STR_KB_SPACE] = FB(246969), [STR_KB_GO] = FB(246976), [STR_VERSION] = FB(246979),
    [STR_STATUS] = FB(246995), [STR_READ] = FB(247008), [STR_UPDATE] = FB(247027),
    [STR_RESTARTING] = FB(247043), [STR_OTA_UPDATE] = FB(247071), [STR_NTP_SERVER] = FB(247099),
    [STR_SERVER_LABEL] = FB(247124), [STR_NTP_SETTINGS] = FB(247140),
    [STR_NTP_PRESETS] = FB(247171), [STR_PRESETS] = FB(247199), [STR_BENCHMARK] = FB(247215),
    [STR_STOPPING] = FB(247228), [STR_NTP_STATS] = FB(247244), [STR_UNSYNCED] = FB(247272),
    [STR_NONE] = FB(247291), [STR_SELECT_REGION] = FB(247307), [STR_AGE_LABEL] = FB(247344),
    [STR_SYNCS_LABEL] = FB(247366), [STR_FMT_PEERS_NOSYNC] = FB(247388),
    [STR_FMT_PEERS_AGO] = FB(247456), [STR_DST] = FB(247519), [STR_NO_DST] = FB(247544),
};
const char *const weekdays_te_shaped[7] = {
    FB(247578), FB(247585), FB(247592), FB(247605), FB(247612), FB(247619), FB(247629),
};
const char *const months_te_shaped[12] = {
    FB(247636), FB(247643), FB(247653), FB(247663), FB(247673), FB(247677), FB(247684),
    FB(247691), FB(247698), FB(247711), FB(247721), FB(247731),
};
const char lang_name_te_shaped[] = ("\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98" "\xEE" "\x80" "\x9F");

// pa: 166 shaped cluster glyphs (Gurmukhi Sangam MN)
// shaped-source-hash pa 2d3a9b02f345682a
const display_glyph_font_t font_pa = {
    .codepoints = FB16(247742),
    .glyphs_rle = fonts_blob + 248240,
    .glyphs_off = FB16(256682),
    .glyphs_2x_rle = fonts_blob + 257016,
    .glyphs_2x_off = FB16(261454),
    .widths = fonts_blob + 248074,
    .count = 166,
    .glyph_width = 16,
};
const char *const lang_pa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(261788), [STR_WIFI] = FB(261798), [STR_FAIL] = FB(261804),
    [STR_TIMEZONE] = FB(261817), [STR_BRIGHTNESS] = FB(261836), [STR_LED_BLINK] = FB(261846),
    [STR_ROTATE] = FB(261868), [STR_ABOUT] = FB(261890), [STR_LANGUAGE] = FB(261900),
    [STR_DONE] = FB(261913), [STR_BACK] = FB(261926), [STR_CANCEL] = FB(261933),
    [STR_DEL] = FB(261937), [STR_RUNNING] = FB(261953), [STR_ON] = FB(261972),
    [STR_OFF] = FB(261982), [STR_NTS_NO] = FB(261986), [STR_NTS_ATTEMPT] = FB(261996),
    [STR_NTS_REQUIRE] = FB(262006), [STR_WAITING_NTP] = FB(262022),
    [STR_FMT_SYNCED] = FB(262053), [STR_FMT_SYNCING] = FB(262068),
    [STR_FMT_WAITING] = FB(262101), [STR_WIFI_SETUP] = FB(262124), [STR_SCANNING] = FB(262149),
    [STR_SCAN_FAILED] = FB(262177), [STR_TAP_RETRY] = FB(262196),
    [STR_SELECT_NETWORK] = FB(262245), [STR_NO_NETWORKS] = FB(262267),
    [STR_NETWORK_LABEL] = FB(262304), [STR_ENTER_PASSWORD] = FB(262323),
    [STR_CONNECTING] = FB(262351), [STR_CONNECTING_TO] = FB(262370),
    [STR_CONNECTED] = FB(262392), [STR_CONNECTION_FAILED] = FB(262411),
    [STR_KB_SPACE] = FB(262439), [STR_KB_GO] = FB(262446), [STR_VERSION] = FB(262449),
    [STR_STATUS] = FB(262465), [STR_READ] = FB(262484), [STR_UPDATE] = FB(262500),
    [STR_RESTARTING] = FB(262507), [STR_OTA_UPDATE] = FB(262517), [STR_NTP_SERVER] = FB(262536),
    [STR_SERVER_LABEL] = FB(262561), [STR_NTP_SETTINGS] = FB(262577),
    [STR_NTP_PRESETS] = FB(262596), [STR_PRESETS] = FB(262618), [STR_BENCHMARK] = FB(262631),
    [STR_STOPPING] = FB(262641), [STR_NTP_STATS] = FB(262660), [STR_UNSYNCED] = FB(262679),
    [STR_NONE] = FB(262698), [STR_SELECT_REGION] = FB(262714), [STR_AGE_LABEL] = FB(262727),
    [STR_SYNCS_LABEL] = FB(262749), [STR_FMT_PEERS_NOSYNC] = FB(262768),
    [STR_FMT_PEERS_AGO] = FB(262836), [STR_DST] = FB(262902), [STR_NO_DST] = FB(262927),
};
const char *const weekdays_pa_shaped[7] = {
    FB(262964), FB(262971), FB(262975), FB(262982), FB(262986), FB(262996), FB(263003),
};
const char *const months_pa_shaped[12] = {
    FB(263013), FB(263020), FB(263027), FB(263040), FB(263047), FB(263054), FB(263058),
    FB(263065), FB(263072), FB(263079), FB(263089), FB(263096),
};
const char lang_name_pa_shaped[] = ("\xEE" "\x82" "\xA3" "\xEE" "\x80" "\x94" "\xEE" "\x82" "\xA4" "\xEE" "\x82" "\xA5");

// gu: 186 shaped cluster glyphs (Kohinoor Gujarati)
// shaped-source-hash gu fbd4bb74daaf15bf
const display_glyph_font_t font_gu = {
    .codepoints = FB16(263104),
    .glyphs_rle = fonts_blob + 263662,
    .glyphs_off = FB16(272008),
    .glyphs_2x_rle = fonts_blob + 272382,
    .glyphs_2x_off = FB16(277366),
    .widths = fonts_blob + 263476,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_gu_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(277740), [STR_WIFI] = FB(277756), [STR_FAIL] = FB(277762),
    [STR_TIMEZONE] = FB(277775), [STR_BRIGHTNESS] = FB(277794), [STR_LED_BLINK] = FB(277798),
    [STR_ROTATE] = FB(277829), [STR_ABOUT] = FB(277854), [STR_LANGUAGE] = FB(277864),
    [STR_DONE] = FB(277877), [STR_BACK] = FB(277893), [STR_CANCEL] = FB(277906),
    [STR_DEL] = FB(277913), [STR_RUNNING] = FB(277926), [STR_ON] = FB(277948),
    [STR_OFF] = FB(277958), [STR_NTS_NO] = FB(277965), [STR_NTS_ATTEMPT] = FB(277972),
    [STR_NTS_REQUIRE] = FB(277985), [STR_WAITING_NTP] = FB(278007),
    [STR_FMT_SYNCED] = FB(278047), [STR_FMT_SYNCING] = FB(278068),
    [STR_FMT_WAITING] = FB(278104), [STR_WIFI_SETUP] = FB(278124), [STR_SCANNING] = FB(278152),
    [STR_SCAN_FAILED] = FB(278177), [STR_TAP_RETRY] = FB(278199),
    [STR_SELECT_NETWORK] = FB(278263), [STR_NO_NETWORKS] = FB(278297),
    [STR_NETWORK_LABEL] = FB(278331), [STR_ENTER_PASSWORD] = FB(278347),
    [STR_CONNECTING] = FB(278393), [STR_CONNECTING_TO] = FB(278412),
    [STR_CONNECTED] = FB(278431), [STR_CONNECTION_FAILED] = FB(278441),
    [STR_KB_SPACE] = FB(278466), [STR_KB_GO] = FB(278473), [STR_VERSION] = FB(278476),
    [STR_STATUS] = FB(278489), [STR_READ] = FB(278505), [STR_UPDATE] = FB(278515),
    [STR_RESTARTING] = FB(278531), [STR_OTA_UPDATE] = FB(278550), [STR_NTP_SERVER] = FB(278578),
    [STR_SERVER_LABEL] = FB(278597), [STR_NTP_SETTINGS] = FB(278607),
    [STR_NTP_PRESETS] = FB(278635), [STR_PRESETS] = FB(278663), [STR_BENCHMARK] = FB(278679),
    [STR_STOPPING] = FB(278695), [STR_NTP_STATS] = FB(278717), [STR_UNSYNCED] = FB(278742),
    [STR_NONE] = FB(278767), [STR_SELECT_REGION] = FB(278789), [STR_AGE_LABEL] = FB(278823),
    [STR_SYNCS_LABEL] = FB(278848), [STR_FMT_PEERS_NOSYNC] = FB(278873),
    [STR_FMT_PEERS_AGO] = FB(278941), [STR_DST] = FB(279001), [STR_NO_DST] = FB(279023),
};
const char *const weekdays_gu_shaped[7] = {
    FB(279057), FB(279067), FB(279074), FB(279081), FB(279088), FB(279092), FB(279096),
};
const char *const months_gu_shaped[12] = {
    FB(279106), FB(279113), FB(279123), FB(279133), FB(279143), FB(279147), FB(279157),
    FB(279173), FB(279183), FB(279193), FB(279203), FB(279210),
};
const char lang_name_gu_shaped[] = ("\xEE" "\x82" "\xB9" "\xEE" "\x80" "\x95" "\xEE" "\x80" "\x94" "\xEE" "\x80" "\xBE" "\xEE" "\x82" "\x95");

// kn: 217 shaped cluster glyphs (Kannada Sangam MN)
// shaped-source-hash kn 31b46ecce4f64786
const display_glyph_font_t font_kn = {
    .codepoints = FB16(279220),
    .glyphs_rle = fonts_blob + 279871,
    .glyphs_off = FB16(291636),
    .glyphs_2x_rle = fonts_blob + 292072,
    .glyphs_2x_off = FB16(299066),
    .widths = fonts_blob + 279654,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_kn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(299502), [STR_WIFI] = FB(299524), [STR_FAIL] = FB(299530),
    [STR_TIMEZONE] = FB(299540), [STR_BRIGHTNESS] = FB(299562), [STR_LED_BLINK] = FB(299578),
    [STR_ROTATE] = FB(299606), [STR_ABOUT] = FB(299631), [STR_LANGUAGE] = FB(299647),
    [STR_DONE] = FB(299657), [STR_BACK] = FB(299670), [STR_CANCEL] = FB(299680),
    [STR_DEL] = FB(299690), [STR_RUNNING] = FB(299700), [STR_ON] = FB(299713),
    [STR_OFF] = FB(299720), [STR_NTS_NO] = FB(299727), [STR_NTS_ATTEMPT] = FB(299734),
    [STR_NTS_REQUIRE] = FB(299747), [STR_WAITING_NTP] = FB(299760),
    [STR_FMT_SYNCED] = FB(299806), [STR_FMT_SYNCING] = FB(299824),
    [STR_FMT_WAITING] = FB(299857), [STR_WIFI_SETUP] = FB(299883), [STR_SCANNING] = FB(299911),
    [STR_SCAN_FAILED] = FB(299942), [STR_TAP_RETRY] = FB(299976),
    [STR_SELECT_NETWORK] = FB(300010), [STR_NO_NETWORKS] = FB(300035),
    [STR_NETWORK_LABEL] = FB(300060), [STR_ENTER_PASSWORD] = FB(300079),
    [STR_CONNECTING] = FB(300116), [STR_CONNECTING_TO] = FB(300141),
    [STR_CONNECTED] = FB(300166), [STR_CONNECTION_FAILED] = FB(300194),
    [STR_KB_SPACE] = FB(300222), [STR_KB_GO] = FB(300232), [STR_VERSION] = FB(300235),
    [STR_STATUS] = FB(300248), [STR_READ] = FB(300255), [STR_UPDATE] = FB(300268),
    [STR_RESTARTING] = FB(300284), [STR_OTA_UPDATE] = FB(300312), [STR_NTP_SERVER] = FB(300340),
    [STR_SERVER_LABEL] = FB(300365), [STR_NTP_SETTINGS] = FB(300381),
    [STR_NTP_PRESETS] = FB(300415), [STR_PRESETS] = FB(300440), [STR_BENCHMARK] = FB(300453),
    [STR_STOPPING] = FB(300463), [STR_NTP_STATS] = FB(300476), [STR_UNSYNCED] = FB(300507),
    [STR_NONE] = FB(300526), [STR_SELECT_REGION] = FB(300545), [STR_AGE_LABEL] = FB(300567),
    [STR_SYNCS_LABEL] = FB(300595), [STR_FMT_PEERS_NOSYNC] = FB(300614),
    [STR_FMT_PEERS_AGO] = FB(300679), [STR_DST] = FB(300739), [STR_NO_DST] = FB(300758),
};
const char *const weekdays_kn_shaped[7] = {
    FB(300786), FB(300799), FB(300809), FB(300822), FB(300832), FB(300845), FB(300858),
};
const char *const months_kn_shaped[12] = {
    FB(300865), FB(300872), FB(300882), FB(300895), FB(300902), FB(300909), FB(300919),
    FB(300929), FB(300936), FB(300946), FB(300959), FB(300969),
};
const char lang_name_kn_shaped[] = ("\xEE" "\x80" "\xA1" "\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98");

// ml: 190 shaped cluster glyphs (Malayalam Sangam MN)
// shaped-source-hash ml 84ed9b8b37b36c9e
const display_glyph_font_t font_ml = {
    .codepoints = FB16(300976),
    .glyphs_rle = fonts_blob + 301546,
    .glyphs_off = FB16(310548),
    .glyphs_2x_rle = fonts_blob + 310930,
    .glyphs_2x_off = FB16(318318),
    .widths = fonts_blob + 301356,
    .count = 190,
    .glyph_width = 16,
};
const char *const lang_ml_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(318700), [STR_WIFI] = FB(318728), [STR_FAIL] = FB(318734),
    [STR_TIMEZONE] = FB(318753), [STR_BRIGHTNESS] = FB(318778), [STR_LED_BLINK] = FB(318797),
    [STR_ROTATE] = FB(318822), [STR_ABOUT] = FB(318856), [STR_LANGUAGE] = FB(318872),
    [STR_DONE] = FB(318882), [STR_BACK] = FB(318901), [STR_CANCEL] = FB(318920),
    [STR_DEL] = FB(318927), [STR_RUNNING] = FB(318943), [STR_ON] = FB(318977),
    [STR_OFF] = FB(318984), [STR_NTS_NO] = FB(318991), [STR_NTS_ATTEMPT] = FB(318998),
    [STR_NTS_REQUIRE] = FB(319011), [STR_WAITING_NTP] = FB(319033),
    [STR_FMT_SYNCED] = FB(319076), [STR_FMT_SYNCING] = FB(319091),
    [STR_FMT_WAITING] = FB(319127), [STR_WIFI_SETUP] = FB(319159), [STR_SCANNING] = FB(319202),
    [STR_SCAN_FAILED] = FB(319233), [STR_TAP_RETRY] = FB(319273),
    [STR_SELECT_NETWORK] = FB(319334), [STR_NO_NETWORKS] = FB(319371),
    [STR_NETWORK_LABEL] = FB(319396), [STR_ENTER_PASSWORD] = FB(319415),
    [STR_CONNECTING] = FB(319449), [STR_CONNECTING_TO] = FB(319477),
    [STR_CONNECTED] = FB(319508), [STR_CONNECTION_FAILED] = FB(319533),
    [STR_KB_SPACE] = FB(319567), [STR_KB_GO] = FB(319580), [STR_VERSION] = FB(319583),
    [STR_STATUS] = FB(319596), [STR_READ] = FB(319609), [STR_UPDATE] = FB(319631),
    [STR_RESTARTING] = FB(319644), [STR_OTA_UPDATE] = FB(319672), [STR_NTP_SERVER] = FB(319697),
    [STR_SERVER_LABEL] = FB(319725), [STR_NTP_SETTINGS] = FB(319744),
    [STR_NTP_PRESETS] = FB(319781), [STR_PRESETS] = FB(319815), [STR_BENCHMARK] = FB(319837),
    [STR_STOPPING] = FB(319853), [STR_NTP_STATS] = FB(319875), [STR_UNSYNCED] = FB(319918),
    [STR_NONE] = FB(319934), [STR_SELECT_REGION] = FB(319953), [STR_AGE_LABEL] = FB(319993),
    [STR_SYNCS_LABEL] = FB(320021), [STR_FMT_PEERS_NOSYNC] = FB(320040),
    [STR_FMT_PEERS_AGO] = FB(320108), [STR_DST] = FB(320171), [STR_NO_DST] = FB(320199),
};
const char *const weekdays_ml_shaped[7] = {
    FB(320236), FB(320249), FB(320262), FB(320275), FB(320288), FB(320304), FB(320317),
};
const char *const months_ml_shaped[12] = {
    FB(320327), FB(320337), FB(320353), FB(320363), FB(320376), FB(320386), FB(320396),
    FB(320409), FB(320416), FB(320429), FB(320442), FB(320452),
};
const char lang_name_ml_shaped[] = ("\xEE" "\x80" "\x82" "\xEE" "\x82" "\xBC" "\xEE" "\x80" "\x90" "\xEE" "\x80" "\x8B" "\xEE" "\x82" "\xBD" "\xEE" "\x81" "\x8B");

// ne: 198 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash ne d85c20cd0e9960a9
const display_glyph_font_t font_ne = {
    .codepoints = FB16(320466),
    .glyphs_rle = fonts_blob + 321060,
    .glyphs_off = FB16(329922),
    .glyphs_2x_rle = fonts_blob + 330320,
    .glyphs_2x_off = FB16(336086),
    .widths = fonts_blob + 320862,
    .count = 198,
    .glyph_width = 16,
};
const char *const lang_ne_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(336484), [STR_WIFI] = FB(336500), [STR_FAIL] = FB(336506),
    [STR_TIMEZONE] = FB(336519), [STR_BRIGHTNESS] = FB(336535), [STR_LED_BLINK] = FB(336545),
    [STR_ROTATE] = FB(336576), [STR_ABOUT] = FB(336598), [STR_LANGUAGE] = FB(336614),
    [STR_DONE] = FB(336627), [STR_BACK] = FB(336637), [STR_CANCEL] = FB(336653),
    [STR_DEL] = FB(336660), [STR_RUNNING] = FB(336670), [STR_ON] = FB(336692),
    [STR_OFF] = FB(336699), [STR_NTS_NO] = FB(336706), [STR_NTS_ATTEMPT] = FB(336719),
    [STR_NTS_REQUIRE] = FB(336732), [STR_WAITING_NTP] = FB(336751),
    [STR_FMT_SYNCED] = FB(336779), [STR_FMT_SYNCING] = FB(336800),
    [STR_FMT_WAITING] = FB(336833), [STR_WIFI_SETUP] = FB(336853), [STR_SCANNING] = FB(336881),
    [STR_SCAN_FAILED] = FB(336900), [STR_TAP_RETRY] = FB(336928),
    [STR_SELECT_NETWORK] = FB(336989), [STR_NO_NETWORKS] = FB(337020),
    [STR_NETWORK_LABEL] = FB(337045), [STR_ENTER_PASSWORD] = FB(337061),
    [STR_CONNECTING] = FB(337095), [STR_CONNECTING_TO] = FB(337120),
    [STR_CONNECTED] = FB(337148), [STR_CONNECTION_FAILED] = FB(337176),
    [STR_KB_SPACE] = FB(337204), [STR_KB_GO] = FB(337211), [STR_VERSION] = FB(337214),
    [STR_STATUS] = FB(337230), [STR_READ] = FB(337246), [STR_UPDATE] = FB(337265),
    [STR_RESTARTING] = FB(337275), [STR_OTA_UPDATE] = FB(337288), [STR_NTP_SERVER] = FB(337310),
    [STR_SERVER_LABEL] = FB(337329), [STR_NTP_SETTINGS] = FB(337339),
    [STR_NTP_PRESETS] = FB(337361), [STR_PRESETS] = FB(337392), [STR_BENCHMARK] = FB(337411),
    [STR_STOPPING] = FB(337427), [STR_NTP_STATS] = FB(337446), [STR_UNSYNCED] = FB(337477),
    [STR_NONE] = FB(337502), [STR_SELECT_REGION] = FB(337527), [STR_AGE_LABEL] = FB(337549),
    [STR_SYNCS_LABEL] = FB(337568), [STR_FMT_PEERS_NOSYNC] = FB(337593),
    [STR_FMT_PEERS_AGO] = FB(337661), [STR_DST] = FB(337715), [STR_NO_DST] = FB(337737),
};
const char *const weekdays_ne_shaped[7] = {
    FB(337771), FB(337781), FB(337791), FB(337807), FB(337811), FB(337824), FB(337831),
};
const char *const months_ne_shaped[12] = {
    FB(337841), FB(337857), FB(337873), FB(337883), FB(337896), FB(337900), FB(337904),
    FB(337917), FB(337927), FB(337937), FB(337953), FB(337969),
};
const char lang_name_ne_shaped[] = ("\xEE" "\x83" "\x85" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x88" "\xEE" "\x81" "\x9B");

// si: 162 shaped cluster glyphs (Sinhala Sangam MN)
// shaped-source-hash si a30676e11139b215
const display_glyph_font_t font_si = {
    .codepoints = FB16(337986),
    .glyphs_rle = fonts_blob + 338472,
    .glyphs_off = FB16(346286),
    .glyphs_2x_rle = fonts_blob + 346612,
    .glyphs_2x_off = FB16(353764),
    .widths = fonts_blob + 338310,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_si_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(354090), [STR_WIFI] = FB(354103), [STR_FAIL] = FB(354109),
    [STR_TIMEZONE] = FB(354131), [STR_BRIGHTNESS] = FB(354162), [STR_LED_BLINK] = FB(354175),
    [STR_ROTATE] = FB(354200), [STR_ABOUT] = FB(354231), [STR_LANGUAGE] = FB(354244),
    [STR_DONE] = FB(354260), [STR_BACK] = FB(354273), [STR_CANCEL] = FB(354283),
    [STR_DEL] = FB(354299), [STR_RUNNING] = FB(354312), [STR_ON] = FB(354337),
    [STR_OFF] = FB(354347), [STR_NTS_NO] = FB(354357), [STR_NTS_ATTEMPT] = FB(354367),
    [STR_NTS_REQUIRE] = FB(354386), [STR_WAITING_NTP] = FB(354405),
    [STR_FMT_SYNCED] = FB(354469), [STR_FMT_SYNCING] = FB(354493),
    [STR_FMT_WAITING] = FB(354532), [STR_WIFI_SETUP] = FB(354552), [STR_SCANNING] = FB(354583),
    [STR_SCAN_FAILED] = FB(354611), [STR_TAP_RETRY] = FB(354648),
    [STR_SELECT_NETWORK] = FB(354709), [STR_NO_NETWORKS] = FB(354743),
    [STR_NETWORK_LABEL] = FB(354774), [STR_ENTER_PASSWORD] = FB(354790),
    [STR_CONNECTING] = FB(354830), [STR_CONNECTING_TO] = FB(354861),
    [STR_CONNECTED] = FB(354895), [STR_CONNECTION_FAILED] = FB(354917),
    [STR_KB_SPACE] = FB(354966), [STR_KB_GO] = FB(354973), [STR_VERSION] = FB(354976),
    [STR_STATUS] = FB(354995), [STR_READ] = FB(355014), [STR_UPDATE] = FB(355024),
    [STR_RESTARTING] = FB(355037), [STR_OTA_UPDATE] = FB(355068), [STR_NTP_SERVER] = FB(355105),
    [STR_SERVER_LABEL] = FB(355145), [STR_NTP_SETTINGS] = FB(355176),
    [STR_NTP_PRESETS] = FB(355201), [STR_PRESETS] = FB(355229), [STR_BENCHMARK] = FB(355245),
    [STR_STOPPING] = FB(355264), [STR_NTP_STATS] = FB(355280), [STR_UNSYNCED] = FB(355320),
    [STR_NONE] = FB(355348), [STR_SELECT_REGION] = FB(355373), [STR_AGE_LABEL] = FB(355410),
    [STR_SYNCS_LABEL] = FB(355432), [STR_FMT_PEERS_NOSYNC] = FB(355454),
    [STR_FMT_PEERS_AGO] = FB(355525), [STR_DST] = FB(355585), [STR_NO_DST] = FB(355619),
};
const char *const weekdays_si_shaped[7] = {
    FB(355665), FB(355678), FB(355691), FB(355701), FB(355717), FB(355727), FB(355734),
};
const char *const months_si_shaped[12] = {
    FB(355744), FB(355754), FB(355764), FB(355777), FB(355784), FB(355797), FB(355819),
    FB(355829), FB(355839), FB(355849), FB(355856), FB(355863),
};
const char lang_name_si_shaped[] = ("\xEE" "\x82" "\x8A" "\xEE" "\x80" "\xAF" "\xEE" "\x80" "\xBA" "\xEE" "\x80" "\x8F");

// km: 193 shaped cluster glyphs (Khmer Sangam MN)
// shaped-source-hash km 001d4323092b620d
const display_glyph_font_t font_km = {
    .codepoints = FB16(355876),
    .glyphs_rle = fonts_blob + 356455,
    .glyphs_off = FB16(365896),
    .glyphs_2x_rle = fonts_blob + 366284,
    .glyphs_2x_off = FB16(371206),
    .widths = fonts_blob + 356262,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_km_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(371594), [STR_WIFI] = FB(371610), [STR_FAIL] = FB(371616),
    [STR_TIMEZONE] = FB(371626), [STR_BRIGHTNESS] = FB(371639), [STR_LED_BLINK] = FB(371646),
    [STR_ROTATE] = FB(371668), [STR_ABOUT] = FB(371687), [STR_LANGUAGE] = FB(371691),
    [STR_DONE] = FB(371698), [STR_BACK] = FB(371708), [STR_CANCEL] = FB(371727),
    [STR_DEL] = FB(371743), [STR_RUNNING] = FB(371747), [STR_ON] = FB(371766),
    [STR_OFF] = FB(371773), [STR_NTS_NO] = FB(371777), [STR_NTS_ATTEMPT] = FB(371784),
    [STR_NTS_REQUIRE] = FB(371797), [STR_WAITING_NTP] = FB(371807),
    [STR_FMT_SYNCED] = FB(371835), [STR_FMT_SYNCING] = FB(371856),
    [STR_FMT_WAITING] = FB(371883), [STR_WIFI_SETUP] = FB(371900), [STR_SCANNING] = FB(371931),
    [STR_SCAN_FAILED] = FB(371959), [STR_TAP_RETRY] = FB(371981),
    [STR_SELECT_NETWORK] = FB(372018), [STR_NO_NETWORKS] = FB(372043),
    [STR_NETWORK_LABEL] = FB(372056), [STR_ENTER_PASSWORD] = FB(372069),
    [STR_CONNECTING] = FB(372094), [STR_CONNECTING_TO] = FB(372104),
    [STR_CONNECTED] = FB(372117), [STR_CONNECTION_FAILED] = FB(372127),
    [STR_KB_SPACE] = FB(372146), [STR_KB_GO] = FB(372156), [STR_VERSION] = FB(372159),
    [STR_STATUS] = FB(372169), [STR_READ] = FB(372185), [STR_UPDATE] = FB(372201),
    [STR_RESTARTING] = FB(372217), [STR_OTA_UPDATE] = FB(372236), [STR_NTP_SERVER] = FB(372264),
    [STR_SERVER_LABEL] = FB(372289), [STR_NTP_SETTINGS] = FB(372305),
    [STR_NTP_PRESETS] = FB(372330), [STR_PRESETS] = FB(372352), [STR_BENCHMARK] = FB(372365),
    [STR_STOPPING] = FB(372381), [STR_NTP_STATS] = FB(372394), [STR_UNSYNCED] = FB(372410),
    [STR_NONE] = FB(372426), [STR_SELECT_REGION] = FB(372430), [STR_AGE_LABEL] = FB(372452),
    [STR_SYNCS_LABEL] = FB(372468), [STR_FMT_PEERS_NOSYNC] = FB(372484),
    [STR_FMT_PEERS_AGO] = FB(372531), [STR_DST] = FB(372576), [STR_NO_DST] = FB(372595),
};
const char *const weekdays_km_shaped[7] = {
    FB(372617), FB(372627), FB(372634), FB(372641), FB(372645), FB(372655), FB(372662),
};
const char *const months_km_shaped[12] = {
    FB(372672), FB(372682), FB(372686), FB(372690), FB(372700), FB(372710), FB(372717),
    FB(372724), FB(372731), FB(372738), FB(372745), FB(372752),
};
const char lang_name_km_shaped[] = ("\xEE" "\x80" "\x88" "\xEE" "\x83" "\x80");

// lo: 169 shaped cluster glyphs (Lao Sangam MN)
// shaped-source-hash lo 3d0778a6b7811038
const display_glyph_font_t font_lo = {
    .codepoints = FB16(372756),
    .glyphs_rle = fonts_blob + 373263,
    .glyphs_off = FB16(382120),
    .glyphs_2x_rle = fonts_blob + 382460,
    .glyphs_2x_off = FB16(387124),
    .widths = fonts_blob + 373094,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_lo_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(387464), [STR_WIFI] = FB(387480), [STR_FAIL] = FB(387486),
    [STR_TIMEZONE] = FB(387499), [STR_BRIGHTNESS] = FB(387521), [STR_LED_BLINK] = FB(387540),
    [STR_ROTATE] = FB(387562), [STR_ABOUT] = FB(387581), [STR_LANGUAGE] = FB(387591),
    [STR_DONE] = FB(387604), [STR_BACK] = FB(387611), [STR_CANCEL] = FB(387618),
    [STR_DEL] = FB(387628), [STR_RUNNING] = FB(387632), [STR_ON] = FB(387654),
    [STR_OFF] = FB(387661), [STR_NTS_NO] = FB(387665), [STR_NTS_ATTEMPT] = FB(387669),
    [STR_NTS_REQUIRE] = FB(387679), [STR_WAITING_NTP] = FB(387686),
    [STR_FMT_SYNCED] = FB(387714), [STR_FMT_SYNCING] = FB(387732),
    [STR_FMT_WAITING] = FB(387750), [STR_WIFI_SETUP] = FB(387767), [STR_SCANNING] = FB(387792),
    [STR_SCAN_FAILED] = FB(387817), [STR_TAP_RETRY] = FB(387845),
    [STR_SELECT_NETWORK] = FB(387876), [STR_NO_NETWORKS] = FB(387898),
    [STR_NETWORK_LABEL] = FB(387917), [STR_ENTER_PASSWORD] = FB(387933),
    [STR_CONNECTING] = FB(387952), [STR_CONNECTING_TO] = FB(387971),
    [STR_CONNECTED] = FB(387987), [STR_CONNECTION_FAILED] = FB(388006),
    [STR_KB_SPACE] = FB(388031), [STR_KB_GO] = FB(388038), [STR_VERSION] = FB(388041),
    [STR_STATUS] = FB(388054), [STR_READ] = FB(388076), [STR_UPDATE] = FB(388086),
    [STR_RESTARTING] = FB(388099), [STR_OTA_UPDATE] = FB(388118), [STR_NTP_SERVER] = FB(388143),
    [STR_SERVER_LABEL] = FB(388165), [STR_NTP_SETTINGS] = FB(388178),
    [STR_NTP_PRESETS] = FB(388197), [STR_PRESETS] = FB(388231), [STR_BENCHMARK] = FB(388253),
    [STR_STOPPING] = FB(388266), [STR_NTP_STATS] = FB(388276), [STR_UNSYNCED] = FB(388298),
    [STR_NONE] = FB(388305), [STR_SELECT_REGION] = FB(388309), [STR_AGE_LABEL] = FB(388328),
    [STR_SYNCS_LABEL] = FB(388347), [STR_FMT_PEERS_NOSYNC] = FB(388363),
    [STR_FMT_PEERS_AGO] = FB(388416), [STR_DST] = FB(388470), [STR_NO_DST] = FB(388498),
};
const char *const weekdays_lo_shaped[7] = {
    FB(388529), FB(388539), FB(388543), FB(388556), FB(388560), FB(388570), FB(388574),
};
const char *const months_lo_shaped[12] = {
    FB(388581), FB(388594), FB(388607), FB(388620), FB(388633), FB(388646), FB(388656),
    FB(388669), FB(388682), FB(388695), FB(388708), FB(388721),
};
const char lang_name_lo_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x80" "\x8E" "\xEE" "\x80" "\x8C");

// my: 188 shaped cluster glyphs (Myanmar Sangam MN)
// shaped-source-hash my 56bd2343a1a303fd
const display_glyph_font_t font_my = {
    .codepoints = FB16(388734),
    .glyphs_rle = fonts_blob + 389298,
    .glyphs_off = FB16(398238),
    .glyphs_2x_rle = fonts_blob + 398616,
    .glyphs_2x_off = FB16(403844),
    .widths = fonts_blob + 389110,
    .count = 188,
    .glyph_width = 16,
};
const char *const lang_my_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(404222), [STR_WIFI] = FB(404244), [STR_FAIL] = FB(404250),
    [STR_TIMEZONE] = FB(404272), [STR_BRIGHTNESS] = FB(404285), [STR_LED_BLINK] = FB(404304),
    [STR_ROTATE] = FB(404326), [STR_ABOUT] = FB(404342), [STR_LANGUAGE] = FB(404361),
    [STR_DONE] = FB(404374), [STR_BACK] = FB(404387), [STR_CANCEL] = FB(404403),
    [STR_DEL] = FB(404419), [STR_RUNNING] = FB(404429), [STR_ON] = FB(404448),
    [STR_OFF] = FB(404452), [STR_NTS_NO] = FB(404459), [STR_NTS_ATTEMPT] = FB(404469),
    [STR_NTS_REQUIRE] = FB(404488), [STR_WAITING_NTP] = FB(404498),
    [STR_FMT_SYNCED] = FB(404535), [STR_FMT_SYNCING] = FB(404550),
    [STR_FMT_WAITING] = FB(404574), [STR_WIFI_SETUP] = FB(404594), [STR_SCANNING] = FB(404625),
    [STR_SCAN_FAILED] = FB(404650), [STR_TAP_RETRY] = FB(404666),
    [STR_SELECT_NETWORK] = FB(404691), [STR_NO_NETWORKS] = FB(404713),
    [STR_NETWORK_LABEL] = FB(404729), [STR_ENTER_PASSWORD] = FB(404739),
    [STR_CONNECTING] = FB(404767), [STR_CONNECTING_TO] = FB(404786),
    [STR_CONNECTED] = FB(404808), [STR_CONNECTION_FAILED] = FB(404827),
    [STR_KB_SPACE] = FB(404864), [STR_KB_GO] = FB(404883), [STR_VERSION] = FB(404886),
    [STR_STATUS] = FB(404905), [STR_READ] = FB(404930), [STR_UPDATE] = FB(404943),
    [STR_RESTARTING] = FB(404953), [STR_OTA_UPDATE] = FB(404969), [STR_NTP_SERVER] = FB(404991),
    [STR_SERVER_LABEL] = FB(405016), [STR_NTP_SETTINGS] = FB(405032),
    [STR_NTP_PRESETS] = FB(405057), [STR_PRESETS] = FB(405079), [STR_BENCHMARK] = FB(405089),
    [STR_STOPPING] = FB(405102), [STR_NTP_STATS] = FB(405118), [STR_UNSYNCED] = FB(405143),
    [STR_NONE] = FB(405156), [STR_SELECT_REGION] = FB(405163), [STR_AGE_LABEL] = FB(405185),
    [STR_SYNCS_LABEL] = FB(405210), [STR_FMT_PEERS_NOSYNC] = FB(405226),
    [STR_FMT_PEERS_AGO] = FB(405294), [STR_DST] = FB(405357), [STR_NO_DST] = FB(405379),
};
const char *const weekdays_my_shaped[7] = {
    FB(405404), FB(405417), FB(405427), FB(405434), FB(405441), FB(405466), FB(405485),
};
const char *const months_my_shaped[12] = {
    FB(405495), FB(405502), FB(405509), FB(405516), FB(405520), FB(405527), FB(405531),
    FB(405535), FB(405539), FB(405546), FB(405559), FB(405563),
};
const char lang_name_my_shaped[] = ("\xEE" "\x80" "\xA6" "\xEE" "\x80" "\x8C" "\xEE" "\x82" "\xBB" "\xEE" "\x80" "\x8A");

// am: 176 shaped cluster glyphs (Kefa)
// shaped-source-hash am 1a59f6efe1a107eb
const display_glyph_font_t font_am = {
    .codepoints = FB16(405568),
    .glyphs_rle = fonts_blob + 406096,
    .glyphs_off = FB16(414956),
    .glyphs_2x_rle = fonts_blob + 415310,
    .glyphs_2x_off = FB16(422594),
    .widths = fonts_blob + 405920,
    .count = 176,
    .glyph_width = 16,
};
const char *const lang_am_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(422948), [STR_WIFI] = FB(422964), [STR_FAIL] = FB(422970),
    [STR_TIMEZONE] = FB(422989), [STR_BRIGHTNESS] = FB(423011), [STR_LED_BLINK] = FB(423027),
    [STR_ROTATE] = FB(423052), [STR_ABOUT] = FB(423074), [STR_LANGUAGE] = FB(423081),
    [STR_DONE] = FB(423091), [STR_BACK] = FB(423107), [STR_CANCEL] = FB(423120),
    [STR_DEL] = FB(423130), [STR_RUNNING] = FB(423140), [STR_ON] = FB(423162),
    [STR_OFF] = FB(423175), [STR_NTS_NO] = FB(423188), [STR_NTS_ATTEMPT] = FB(423195),
    [STR_NTS_REQUIRE] = FB(423205), [STR_WAITING_NTP] = FB(423215),
    [STR_FMT_SYNCED] = FB(423252), [STR_FMT_SYNCING] = FB(423279),
    [STR_FMT_WAITING] = FB(423306), [STR_WIFI_SETUP] = FB(423329), [STR_SCANNING] = FB(423360),
    [STR_SCAN_FAILED] = FB(423385), [STR_TAP_RETRY] = FB(423416),
    [STR_SELECT_NETWORK] = FB(423459), [STR_NO_NETWORKS] = FB(423496),
    [STR_NETWORK_LABEL] = FB(423533), [STR_ENTER_PASSWORD] = FB(423549),
    [STR_CONNECTING] = FB(423586), [STR_CONNECTING_TO] = FB(423605),
    [STR_CONNECTED] = FB(423627), [STR_CONNECTION_FAILED] = FB(423649),
    [STR_KB_SPACE] = FB(423686), [STR_KB_GO] = FB(423699), [STR_VERSION] = FB(423702),
    [STR_STATUS] = FB(423715), [STR_READ] = FB(423728), [STR_UPDATE] = FB(423747),
    [STR_RESTARTING] = FB(423760), [STR_OTA_UPDATE] = FB(423794), [STR_NTP_SERVER] = FB(423819),
    [STR_SERVER_LABEL] = FB(423847), [STR_NTP_SETTINGS] = FB(423866),
    [STR_NTP_PRESETS] = FB(423894), [STR_PRESETS] = FB(423919), [STR_BENCHMARK] = FB(423932),
    [STR_STOPPING] = FB(423942), [STR_NTP_STATS] = FB(423955), [STR_UNSYNCED] = FB(423989),
    [STR_NONE] = FB(424011), [STR_SELECT_REGION] = FB(424021), [STR_AGE_LABEL] = FB(424043),
    [STR_SYNCS_LABEL] = FB(424065), [STR_FMT_PEERS_NOSYNC] = FB(424087),
    [STR_FMT_PEERS_AGO] = FB(424161), [STR_DST] = FB(424231), [STR_NO_DST] = FB(424253),
};
const char *const weekdays_am_shaped[7] = {
    FB(424287), FB(424297), FB(424304), FB(424314), FB(424324), FB(424334), FB(424344),
};
const char *const months_am_shaped[12] = {
    FB(424354), FB(424361), FB(424368), FB(424378), FB(424388), FB(424395), FB(424402),
    FB(424412), FB(424422), FB(424432), FB(424442), FB(424452),
};
const char lang_name_am_shaped[] = ("\xEE" "\x80" "\x85" "\xEE" "\x81" "\xBF" "\xEE" "\x80" "\xAE" "\xEE" "\x82" "\xAF");

// kok: 172 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash kok 8d37d315f8d9d887
const display_glyph_font_t font_kok = {
    .codepoints = FB16(424462),
    .glyphs_rle = fonts_blob + 424978,
    .glyphs_off = FB16(432898),
    .glyphs_2x_rle = fonts_blob + 433244,
    .glyphs_2x_off = FB16(438204),
    .widths = fonts_blob + 424806,
    .count = 172,
    .glyph_width = 16,
};
const char *const lang_kok_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(438550), [STR_SETTINGS] = FB(438556), [STR_FAIL] = FB(438569),
    [STR_TIMEZONE] = FB(438576), [STR_BRIGHTNESS] = FB(438598), [STR_LED_BLINK] = FB(438614),
    [STR_ROTATE] = FB(438639), [STR_ABOUT] = FB(438664), [STR_LANGUAGE] = FB(438677),
    [STR_DONE] = FB(438687), [STR_BACK] = FB(438697), [STR_CANCEL] = FB(438710),
    [STR_DEL] = FB(438717), [STR_RUNNING] = FB(438727), [STR_ON] = FB(438746),
    [STR_OFF] = FB(438756), [STR_NTS_NO] = FB(438760), [STR_NTS_ATTEMPT] = FB(438767),
    [STR_NTS_REQUIRE] = FB(438774), [STR_WAITING_NTP] = FB(438784),
    [STR_FMT_SYNCED] = FB(438839), [STR_FMT_SYNCING] = FB(438869),
    [STR_FMT_WAITING] = FB(438905), [STR_FMT_PEERS_NOSYNC] = FB(438931),
    [STR_FMT_PEERS_AGO] = FB(438996), [STR_WIFI_SETUP] = FB(439050),
    [STR_SCANNING] = FB(439084), [STR_SCAN_FAILED] = FB(439109), [STR_TAP_RETRY] = FB(439128),
    [STR_SELECT_NETWORK] = FB(439183), [STR_NO_NETWORKS] = FB(439208),
    [STR_NETWORK_LABEL] = FB(439239), [STR_ENTER_PASSWORD] = FB(439255),
    [STR_CONNECTING] = FB(439286), [STR_CONNECTING_TO] = FB(439302),
    [STR_CONNECTED] = FB(439321), [STR_CONNECTION_FAILED] = FB(439334),
    [STR_KB_SPACE] = FB(439359), [STR_KB_GO] = FB(439372), [STR_VERSION] = FB(439375),
    [STR_STATUS] = FB(439388), [STR_READ] = FB(439404), [STR_UPDATE] = FB(439417),
    [STR_RESTARTING] = FB(439427), [STR_OTA_UPDATE] = FB(439458), [STR_NTP_SERVER] = FB(439480),
    [STR_SERVER_LABEL] = FB(439499), [STR_NTP_SETTINGS] = FB(439509),
    [STR_NTP_PRESETS] = FB(439534), [STR_PRESETS] = FB(439559), [STR_BENCHMARK] = FB(439572),
    [STR_STOPPING] = FB(439585), [STR_NTP_STATS] = FB(439598), [STR_UNSYNCED] = FB(439623),
    [STR_SYNCS_LABEL] = FB(439645), [STR_NONE] = FB(439670), [STR_SELECT_REGION] = FB(439677),
    [STR_AGE_LABEL] = FB(439699), [STR_DST] = FB(439727), [STR_NO_DST] = FB(439752),
};
const char *const weekdays_kok_shaped[7] = {
    FB(439786), FB(439802), FB(439818), FB(439831), FB(439844), FB(439863), FB(439876),
};
const char *const months_kok_shaped[12] = {
    FB(439889), FB(439899), FB(439909), FB(439919), FB(439929), FB(439933), FB(439937),
    FB(439944), FB(439951), FB(439958), FB(439968), FB(439978),
};
const char lang_name_kok_shaped[] = ("\xEE" "\x80" "\xAA" "\xEE" "\x82" "\xAB" "\xEE" "\x82" "\x84" "\xEE" "\x81" "\xAB" "\xEE" "\x80" "\xBD");

// as: 162 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash as 49869d97afa2e3e1
const display_glyph_font_t font_as = {
    .codepoints = FB16(439988),
    .glyphs_rle = fonts_blob + 440474,
    .glyphs_off = FB16(447070),
    .glyphs_2x_rle = fonts_blob + 447396,
    .glyphs_2x_off = FB16(452752),
    .widths = fonts_blob + 440312,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_as_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(453078), [STR_SETTINGS] = FB(453084), [STR_FAIL] = FB(453100),
    [STR_TIMEZONE] = FB(453113), [STR_BRIGHTNESS] = FB(453135), [STR_LED_BLINK] = FB(453151),
    [STR_ROTATE] = FB(453185), [STR_ABOUT] = FB(453216), [STR_LANGUAGE] = FB(453232),
    [STR_DONE] = FB(453245), [STR_BACK] = FB(453255), [STR_CANCEL] = FB(453268),
    [STR_DEL] = FB(453284), [STR_RUNNING] = FB(453294), [STR_ON] = FB(453316),
    [STR_OFF] = FB(453323), [STR_NTS_NO] = FB(453330), [STR_NTS_ATTEMPT] = FB(453340),
    [STR_NTS_REQUIRE] = FB(453353), [STR_WAITING_NTP] = FB(453369),
    [STR_FMT_SYNCED] = FB(453415), [STR_FMT_SYNCING] = FB(453448),
    [STR_FMT_WAITING] = FB(453490), [STR_FMT_PEERS_NOSYNC] = FB(453516),
    [STR_FMT_PEERS_AGO] = FB(453596), [STR_WIFI_SETUP] = FB(453662),
    [STR_SCANNING] = FB(453696), [STR_SCAN_FAILED] = FB(453736), [STR_TAP_RETRY] = FB(453761),
    [STR_SELECT_NETWORK] = FB(453819), [STR_NO_NETWORKS] = FB(453853),
    [STR_NETWORK_LABEL] = FB(453905), [STR_ENTER_PASSWORD] = FB(453927),
    [STR_CONNECTING] = FB(453961), [STR_CONNECTING_TO] = FB(453995),
    [STR_CONNECTED] = FB(454017), [STR_CONNECTION_FAILED] = FB(454036),
    [STR_KB_SPACE] = FB(454070), [STR_KB_GO] = FB(454083), [STR_VERSION] = FB(454086),
    [STR_STATUS] = FB(454105), [STR_READ] = FB(454121), [STR_UPDATE] = FB(454146),
    [STR_RESTARTING] = FB(454162), [STR_OTA_UPDATE] = FB(454181), [STR_NTP_SERVER] = FB(454209),
    [STR_SERVER_LABEL] = FB(454240), [STR_NTP_SETTINGS] = FB(454262),
    [STR_NTP_PRESETS] = FB(454290), [STR_PRESETS] = FB(454315), [STR_BENCHMARK] = FB(454328),
    [STR_STOPPING] = FB(454344), [STR_NTP_STATS] = FB(454363), [STR_UNSYNCED] = FB(454400),
    [STR_SYNCS_LABEL] = FB(454425), [STR_NONE] = FB(454450), [STR_SELECT_REGION] = FB(454460),
    [STR_AGE_LABEL] = FB(454485), [STR_DST] = FB(454507), [STR_NO_DST] = FB(454529),
};
const char *const weekdays_as_shaped[7] = {
    FB(454563), FB(454573), FB(454586), FB(454596), FB(454606), FB(454616), FB(454623),
};
const char *const months_as_shaped[12] = {
    FB(454633), FB(454643), FB(454656), FB(454669), FB(454682), FB(454692), FB(454699),
    FB(454712), FB(454719), FB(454732), FB(454745), FB(454755),
};
const char lang_name_as_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x82" "\xA1" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\x88" "\xEE" "\x80" "\x8B" "\xEE" "\x80" "\xA8");

// ti: 177 shaped cluster glyphs (Kefa)
// shaped-source-hash ti 072e1eae69078ac8
const display_glyph_font_t font_ti = {
    .codepoints = FB16(454768),
    .glyphs_rle = fonts_blob + 455299,
    .glyphs_off = FB16(464210),
    .glyphs_2x_rle = fonts_blob + 464566,
    .glyphs_2x_off = FB16(469088),
    .widths = fonts_blob + 455122,
    .count = 177,
    .glyph_width = 16,
};
const char *const lang_ti_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(469444), [STR_SETTINGS] = FB(469450), [STR_FAIL] = FB(469466),
    [STR_TIMEZONE] = FB(469476), [STR_BRIGHTNESS] = FB(469495), [STR_LED_BLINK] = FB(469508),
    [STR_ROTATE] = FB(469533), [STR_ABOUT] = FB(469555), [STR_LANGUAGE] = FB(469568),
    [STR_DONE] = FB(469578), [STR_BACK] = FB(469591), [STR_CANCEL] = FB(469604),
    [STR_DEL] = FB(469614), [STR_RUNNING] = FB(469627), [STR_ON] = FB(469640),
    [STR_OFF] = FB(469650), [STR_NTS_NO] = FB(469660), [STR_NTS_ATTEMPT] = FB(469673),
    [STR_NTS_REQUIRE] = FB(469683), [STR_WAITING_NTP] = FB(469693),
    [STR_FMT_SYNCED] = FB(469724), [STR_FMT_SYNCING] = FB(469748),
    [STR_FMT_WAITING] = FB(469772), [STR_FMT_PEERS_NOSYNC] = FB(469792),
    [STR_FMT_PEERS_AGO] = FB(469863), [STR_WIFI_SETUP] = FB(469927),
    [STR_SCANNING] = FB(469958), [STR_SCAN_FAILED] = FB(469977), [STR_TAP_RETRY] = FB(470002),
    [STR_SELECT_NETWORK] = FB(470048), [STR_NO_NETWORKS] = FB(470073),
    [STR_NETWORK_LABEL] = FB(470110), [STR_ENTER_PASSWORD] = FB(470126),
    [STR_CONNECTING] = FB(470160), [STR_CONNECTING_TO] = FB(470173),
    [STR_CONNECTED] = FB(470195), [STR_CONNECTION_FAILED] = FB(470211),
    [STR_KB_SPACE] = FB(470233), [STR_KB_GO] = FB(470246), [STR_VERSION] = FB(470249),
    [STR_STATUS] = FB(470262), [STR_READ] = FB(470278), [STR_UPDATE] = FB(470294),
    [STR_RESTARTING] = FB(470307), [STR_OTA_UPDATE] = FB(470338), [STR_NTP_SERVER] = FB(470363),
    [STR_SERVER_LABEL] = FB(470388), [STR_NTP_SETTINGS] = FB(470404),
    [STR_NTP_PRESETS] = FB(470432), [STR_PRESETS] = FB(470463), [STR_BENCHMARK] = FB(470473),
    [STR_STOPPING] = FB(470483), [STR_NTP_STATS] = FB(470493), [STR_UNSYNCED] = FB(470524),
    [STR_SYNCS_LABEL] = FB(470546), [STR_NONE] = FB(470568), [STR_SELECT_REGION] = FB(470578),
    [STR_AGE_LABEL] = FB(470597), [STR_DST] = FB(470619), [STR_NO_DST] = FB(470650),
};
const char *const weekdays_ti_shaped[7] = {
    FB(470693), FB(470700), FB(470707), FB(470714), FB(470721), FB(470728), FB(470735),
};
const char *const months_ti_shaped[12] = {
    FB(470742), FB(470749), FB(470756), FB(470763), FB(470770), FB(470777), FB(470784),
    FB(470791), FB(470798), FB(470805), FB(470812), FB(470819),
};
const char lang_name_ti_shaped[] = ("\xEE" "\x82" "\xAF" "\xEE" "\x80" "\xBC" "\xEE" "\x80" "\x9D" "\xEE" "\x82" "\xB0");

// yo: 160 shaped cluster glyphs (Menlo)
// shaped-source-hash yo ae6afc109bb3d82d
const display_glyph_font_t font_yo = {
    .codepoints = FB16(470826),
    .glyphs_rle = fonts_blob + 471306,
    .glyphs_off = FB16(478138),
    .glyphs_2x_rle = fonts_blob + 478460,
    .glyphs_2x_off = FB16(484612),
    .widths = fonts_blob + 471146,
    .count = 160,
    .glyph_width = 16,
};
const char *const lang_yo_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(484934), [STR_SETTINGS] = FB(484940), [STR_FAIL] = FB(484950),
    [STR_TIMEZONE] = FB(484963), [STR_BRIGHTNESS] = FB(485003), [STR_LED_BLINK] = FB(485019),
    [STR_ROTATE] = FB(485053), [STR_ABOUT] = FB(485072), [STR_LANGUAGE] = FB(485085),
    [STR_DONE] = FB(485095), [STR_BACK] = FB(485108), [STR_CANCEL] = FB(485121),
    [STR_DEL] = FB(485140), [STR_RUNNING] = FB(485153), [STR_ON] = FB(485169),
    [STR_OFF] = FB(485179), [STR_NTS_NO] = FB(485182), [STR_NTS_ATTEMPT] = FB(485195),
    [STR_NTS_REQUIRE] = FB(485220), [STR_WAITING_NTP] = FB(485227),
    [STR_FMT_SYNCED] = FB(485276), [STR_FMT_SYNCING] = FB(485288),
    [STR_FMT_WAITING] = FB(485330), [STR_FMT_PEERS_NOSYNC] = FB(485359),
    [STR_FMT_PEERS_AGO] = FB(485439), [STR_WIFI_SETUP] = FB(485502),
    [STR_SCANNING] = FB(485533), [STR_SCAN_FAILED] = FB(485555), [STR_TAP_RETRY] = FB(485589),
    [STR_SELECT_NETWORK] = FB(485650), [STR_NO_NETWORKS] = FB(485687),
    [STR_NETWORK_LABEL] = FB(485730), [STR_ENTER_PASSWORD] = FB(485758),
    [STR_CONNECTING] = FB(485801), [STR_CONNECTING_TO] = FB(485826),
    [STR_CONNECTED] = FB(485857), [STR_CONNECTION_FAILED] = FB(485885),
    [STR_KB_SPACE] = FB(485919), [STR_KB_GO] = FB(485929), [STR_VERSION] = FB(485932),
    [STR_STATUS] = FB(485948), [STR_READ] = FB(485961), [STR_UPDATE] = FB(485980),
    [STR_RESTARTING] = FB(485999), [STR_OTA_UPDATE] = FB(486036), [STR_NTP_SERVER] = FB(486067),
    [STR_SERVER_LABEL] = FB(486092), [STR_NTP_SETTINGS] = FB(486108),
    [STR_NTP_PRESETS] = FB(486130), [STR_PRESETS] = FB(486161), [STR_BENCHMARK] = FB(486180),
    [STR_STOPPING] = FB(486199), [STR_NTP_STATS] = FB(486218), [STR_UNSYNCED] = FB(486246),
    [STR_SYNCS_LABEL] = FB(486277), [STR_NONE] = FB(486286), [STR_SELECT_REGION] = FB(486302),
    [STR_AGE_LABEL] = FB(486336), [STR_DST] = FB(486367), [STR_NO_DST] = FB(486371),
};
const char *const weekdays_yo_shaped[7] = {
    FB(486399), FB(486412), FB(486422), FB(486438), FB(486451), FB(486464), FB(486474),
};
const char *const months_yo_shaped[12] = {
    FB(486493), FB(486500), FB(486516), FB(486535), FB(486548), FB(486567), FB(486583),
    FB(486599), FB(486612), FB(486618), FB(486637), FB(486650),
};
const char lang_name_yo_shaped[] = ("\xEE" "\x80" "\xA0" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\xAC" "\xEE" "\x81" "\xA7" "\xEE" "\x81" "\xAB" "\xEE" "\x80" "\x9E");

// pcm: 73 shaped cluster glyphs (Menlo)
// shaped-source-hash pcm 4219c090bd10a9f9
const display_glyph_font_t font_pcm = {
    .codepoints = FB16(486666),
    .glyphs_rle = fonts_blob + 486885,
    .glyphs_off = FB16(490186),
    .glyphs_2x_rle = fonts_blob + 490334,
    .glyphs_2x_off = FB16(493864),
    .widths = fonts_blob + 486812,
    .count = 73,
    .glyph_width = 16,
};
const char *const lang_pcm_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(494012), [STR_SETTINGS] = FB(494018), [STR_FAIL] = FB(494037),
    [STR_TIMEZONE] = FB(494041), [STR_BRIGHTNESS] = FB(494050), [STR_LED_BLINK] = FB(494075),
    [STR_ROTATE] = FB(494085), [STR_ABOUT] = FB(494094), [STR_LANGUAGE] = FB(494100),
    [STR_DONE] = FB(494108), [STR_BACK] = FB(494112), [STR_CANCEL] = FB(494116),
    [STR_DEL] = FB(494135), [STR_RUNNING] = FB(494140), [STR_ON] = FB(494147),
    [STR_OFF] = FB(494150), [STR_NTS_NO] = FB(494153), [STR_NTS_ATTEMPT] = FB(494156),
    [STR_NTS_REQUIRE] = FB(494161), [STR_WAITING_NTP] = FB(494166),
    [STR_FMT_SYNCED] = FB(494184), [STR_FMT_SYNCING] = FB(494197),
    [STR_FMT_WAITING] = FB(494209), [STR_FMT_PEERS_NOSYNC] = FB(494222),
    [STR_FMT_PEERS_AGO] = FB(494251), [STR_WIFI_SETUP] = FB(494283),
    [STR_SCANNING] = FB(494293), [STR_SCAN_FAILED] = FB(494304), [STR_TAP_RETRY] = FB(494317),
    [STR_SELECT_NETWORK] = FB(494339), [STR_NO_NETWORKS] = FB(494367),
    [STR_NETWORK_LABEL] = FB(494404), [STR_ENTER_PASSWORD] = FB(494423),
    [STR_CONNECTING] = FB(494454), [STR_CONNECTING_TO] = FB(494463),
    [STR_CONNECTED] = FB(494475), [STR_CONNECTION_FAILED] = FB(494486),
    [STR_KB_SPACE] = FB(494500), [STR_KB_GO] = FB(494505), [STR_VERSION] = FB(494508),
    [STR_STATUS] = FB(494527), [STR_READ] = FB(494538), [STR_UPDATE] = FB(494547),
    [STR_RESTARTING] = FB(494554), [STR_OTA_UPDATE] = FB(494568), [STR_NTP_SERVER] = FB(494579),
    [STR_SERVER_LABEL] = FB(494588), [STR_NTP_SETTINGS] = FB(494594),
    [STR_NTP_PRESETS] = FB(494625), [STR_PRESETS] = FB(494635), [STR_BENCHMARK] = FB(494641),
    [STR_STOPPING] = FB(494654), [STR_NTP_STATS] = FB(494662), [STR_UNSYNCED] = FB(494672),
    [STR_SYNCS_LABEL] = FB(494680), [STR_NONE] = FB(494689), [STR_SELECT_REGION] = FB(494705),
    [STR_AGE_LABEL] = FB(494733), [STR_DST] = FB(494740), [STR_NO_DST] = FB(494744),
};
const char *const weekdays_pcm_shaped[7] = {
    FB(494751), FB(494758), FB(494765), FB(494775), FB(494782), FB(494789), FB(494802),
};
const char *const months_pcm_shaped[12] = {
    FB(494812), FB(494822), FB(494829), FB(494834), FB(494844), FB(494848), FB(494852),
    FB(494856), FB(494866), FB(494876), FB(494886), FB(494896),
};
const char lang_name_pcm_shaped[] = ("\xEE" "\x80" "\x9B" "\xEE" "\x80" "\x8F" "\xEE" "\x81" "\x86" "\xEE" "\x81" "\x87" "\xEE" "\x81" "\x88");

// pa_arab: 189 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash pa_arab 7aefa33ecb599e6e
const display_glyph_font_t font_pa_arab = {
    .codepoints = FB16(494900),
    .glyphs_rle = fonts_blob + 495467,
    .glyphs_off = FB16(502214),
    .glyphs_2x_rle = fonts_blob + 502594,
    .glyphs_2x_off = FB16(507026),
    .widths = fonts_blob + 495278,
    .count = 189,
    .glyph_width = 16,
};
const char *const lang_pa_arab_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(507406), [STR_SETTINGS] = FB(507412), [STR_FAIL] = FB(507434),
    [STR_TIMEZONE] = FB(507450), [STR_BRIGHTNESS] = FB(507484), [STR_LED_BLINK] = FB(507494),
    [STR_ROTATE] = FB(507519), [STR_ABOUT] = FB(507547), [STR_LANGUAGE] = FB(507569),
    [STR_DONE] = FB(507582), [STR_BACK] = FB(507601), [STR_CANCEL] = FB(507614),
    [STR_DEL] = FB(507630), [STR_RUNNING] = FB(507643), [STR_ON] = FB(507674),
    [STR_OFF] = FB(507687), [STR_NTS_NO] = FB(507697), [STR_NTS_ATTEMPT] = FB(507710),
    [STR_NTS_REQUIRE] = FB(507723), [STR_WAITING_NTP] = FB(507736),
    [STR_FMT_SYNCED] = FB(507779), [STR_FMT_SYNCING] = FB(507806),
    [STR_FMT_WAITING] = FB(507857), [STR_FMT_PEERS_NOSYNC] = FB(507880),
    [STR_FMT_PEERS_AGO] = FB(507963), [STR_WIFI_SETUP] = FB(508026),
    [STR_SCANNING] = FB(508063), [STR_SCAN_FAILED] = FB(508106), [STR_TAP_RETRY] = FB(508149),
    [STR_SELECT_NETWORK] = FB(508204), [STR_NO_NETWORKS] = FB(508235),
    [STR_NETWORK_LABEL] = FB(508284), [STR_ENTER_PASSWORD] = FB(508306),
    [STR_CONNECTING] = FB(508340), [STR_CONNECTING_TO] = FB(508371),
    [STR_CONNECTED] = FB(508405), [STR_CONNECTION_FAILED] = FB(508427),
    [STR_KB_SPACE] = FB(508461), [STR_KB_GO] = FB(508474), [STR_VERSION] = FB(508477),
    [STR_STATUS] = FB(508493), [STR_READ] = FB(508509), [STR_UPDATE] = FB(508528),
    [STR_RESTARTING] = FB(508547), [STR_OTA_UPDATE] = FB(508596), [STR_NTP_SERVER] = FB(508627),
    [STR_SERVER_LABEL] = FB(508652), [STR_NTP_SETTINGS] = FB(508668),
    [STR_NTP_PRESETS] = FB(508702), [STR_PRESETS] = FB(508733), [STR_BENCHMARK] = FB(508752),
    [STR_STOPPING] = FB(508765), [STR_NTP_STATS] = FB(508796), [STR_UNSYNCED] = FB(508818),
    [STR_SYNCS_LABEL] = FB(508852), [STR_NONE] = FB(508861), [STR_SELECT_REGION] = FB(508889),
    [STR_AGE_LABEL] = FB(508911), [STR_DST] = FB(508933), [STR_NO_DST] = FB(508973),
};
const char *const weekdays_pa_arab_shaped[7] = {
    FB(509010), FB(509026), FB(509036), FB(509049), FB(509056), FB(509075), FB(509088),
};
const char *const months_pa_arab_shaped[12] = {
    FB(509101), FB(509117), FB(509133), FB(509146), FB(509162), FB(509169), FB(509179),
    FB(509195), FB(509208), FB(509224), FB(509243), FB(509259),
};
const char lang_name_pa_arab_shaped[] = ("\xEE" "\x80" "\xAA" "\xEE" "\x82" "\xBA" "\xEE" "\x80" "\x88" "\xEE" "\x82" "\xBB" "\xEE" "\x80" "\x83" "\xEE" "\x82" "\xBC");

// bho: 179 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash bho 8f965617dc82b1ce
const display_glyph_font_t font_bho = {
    .codepoints = FB16(509276),
    .glyphs_rle = fonts_blob + 509813,
    .glyphs_off = FB16(517850),
    .glyphs_2x_rle = fonts_blob + 518210,
    .glyphs_2x_off = FB16(522958),
    .widths = fonts_blob + 509634,
    .count = 179,
    .glyph_width = 16,
};
const char *const lang_bho_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(523318), [STR_SETTINGS] = FB(523324), [STR_FAIL] = FB(523337),
    [STR_TIMEZONE] = FB(523350), [STR_BRIGHTNESS] = FB(523366), [STR_LED_BLINK] = FB(523376),
    [STR_ROTATE] = FB(523398), [STR_ABOUT] = FB(523420), [STR_LANGUAGE] = FB(523436),
    [STR_DONE] = FB(523449), [STR_BACK] = FB(523465), [STR_CANCEL] = FB(523478),
    [STR_DEL] = FB(523485), [STR_RUNNING] = FB(523495), [STR_ON] = FB(523514),
    [STR_OFF] = FB(523524), [STR_NTS_NO] = FB(523528), [STR_NTS_ATTEMPT] = FB(523535),
    [STR_NTS_REQUIRE] = FB(523551), [STR_WAITING_NTP] = FB(523564),
    [STR_FMT_SYNCED] = FB(523613), [STR_FMT_SYNCING] = FB(523646),
    [STR_FMT_WAITING] = FB(523682), [STR_FMT_PEERS_NOSYNC] = FB(523711),
    [STR_FMT_PEERS_AGO] = FB(523779), [STR_WIFI_SETUP] = FB(523836),
    [STR_SCANNING] = FB(523864), [STR_SCAN_FAILED] = FB(523895), [STR_TAP_RETRY] = FB(523920),
    [STR_SELECT_NETWORK] = FB(523981), [STR_NO_NETWORKS] = FB(524003),
    [STR_NETWORK_LABEL] = FB(524028), [STR_ENTER_PASSWORD] = FB(524044),
    [STR_CONNECTING] = FB(524072), [STR_CONNECTING_TO] = FB(524088),
    [STR_CONNECTED] = FB(524107), [STR_CONNECTION_FAILED] = FB(524126),
    [STR_KB_SPACE] = FB(524154), [STR_KB_GO] = FB(524161), [STR_VERSION] = FB(524164),
    [STR_STATUS] = FB(524180), [STR_READ] = FB(524196), [STR_UPDATE] = FB(524209),
    [STR_RESTARTING] = FB(524219), [STR_OTA_UPDATE] = FB(524250), [STR_NTP_SERVER] = FB(524272),
    [STR_SERVER_LABEL] = FB(524291), [STR_NTP_SETTINGS] = FB(524301),
    [STR_NTP_PRESETS] = FB(524326), [STR_PRESETS] = FB(524351), [STR_BENCHMARK] = FB(524364),
    [STR_STOPPING] = FB(524371), [STR_NTP_STATS] = FB(524390), [STR_UNSYNCED] = FB(524418),
    [STR_SYNCS_LABEL] = FB(524443), [STR_NONE] = FB(524468), [STR_SELECT_REGION] = FB(524493),
    [STR_AGE_LABEL] = FB(524506), [STR_DST] = FB(524531), [STR_NO_DST] = FB(524565),
};
const char *const weekdays_bho_shaped[7] = {
    FB(524602), FB(524621), FB(524640), FB(524656), FB(524669), FB(524682), FB(524698),
};
const char *const months_bho_shaped[12] = {
    FB(524714), FB(524730), FB(524746), FB(524756), FB(524763), FB(524770), FB(524774),
    FB(524787), FB(524797), FB(524813), FB(524829), FB(524839),
};
const char lang_name_bho_shaped[] = ("\xEE" "\x80" "\x9E" "\xEE" "\x81" "\x93" "\xEE" "\x80" "\xAE" "\xEE" "\x82" "\xB2" "\xEE" "\x80" "\xB0");

// ps: 174 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ps d140a0e430230cb8
const display_glyph_font_t font_ps = {
    .codepoints = FB16(524852),
    .glyphs_rle = fonts_blob + 525374,
    .glyphs_off = FB16(531468),
    .glyphs_2x_rle = fonts_blob + 531818,
    .glyphs_2x_off = FB16(536086),
    .widths = fonts_blob + 525200,
    .count = 174,
    .glyph_width = 16,
};
const char *const lang_ps_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(536436), [STR_SETTINGS] = FB(536442), [STR_FAIL] = FB(536461),
    [STR_TIMEZONE] = FB(536477), [STR_BRIGHTNESS] = FB(536508), [STR_LED_BLINK] = FB(536527),
    [STR_ROTATE] = FB(536555), [STR_ABOUT] = FB(536583), [STR_LANGUAGE] = FB(536602),
    [STR_DONE] = FB(536612), [STR_BACK] = FB(536625), [STR_CANCEL] = FB(536638),
    [STR_DEL] = FB(536651), [STR_RUNNING] = FB(536661), [STR_ON] = FB(536683),
    [STR_OFF] = FB(536696), [STR_NTS_NO] = FB(536706), [STR_NTS_ATTEMPT] = FB(536713),
    [STR_NTS_REQUIRE] = FB(536723), [STR_WAITING_NTP] = FB(536736),
    [STR_FMT_SYNCED] = FB(536782), [STR_FMT_SYNCING] = FB(536806),
    [STR_FMT_WAITING] = FB(536845), [STR_FMT_PEERS_NOSYNC] = FB(536874),
    [STR_FMT_PEERS_AGO] = FB(536954), [STR_WIFI_SETUP] = FB(537017),
    [STR_SCANNING] = FB(537057), [STR_SCAN_FAILED] = FB(537079), [STR_TAP_RETRY] = FB(537110),
    [STR_SELECT_NETWORK] = FB(537174), [STR_NO_NETWORKS] = FB(537205),
    [STR_NETWORK_LABEL] = FB(537260), [STR_ENTER_PASSWORD] = FB(537276),
    [STR_CONNECTING] = FB(537310), [STR_CONNECTING_TO] = FB(537329),
    [STR_CONNECTED] = FB(537360), [STR_CONNECTION_FAILED] = FB(537382),
    [STR_KB_SPACE] = FB(537419), [STR_KB_GO] = FB(537429), [STR_VERSION] = FB(537432),
    [STR_STATUS] = FB(537448), [STR_READ] = FB(537464), [STR_UPDATE] = FB(537495),
    [STR_RESTARTING] = FB(537508), [STR_OTA_UPDATE] = FB(537539), [STR_NTP_SERVER] = FB(537570),
    [STR_SERVER_LABEL] = FB(537601), [STR_NTP_SETTINGS] = FB(537617),
    [STR_NTP_PRESETS] = FB(537654), [STR_PRESETS] = FB(537688), [STR_BENCHMARK] = FB(537704),
    [STR_STOPPING] = FB(537726), [STR_NTP_STATS] = FB(537742), [STR_UNSYNCED] = FB(537776),
    [STR_SYNCS_LABEL] = FB(537807), [STR_NONE] = FB(537816), [STR_SELECT_REGION] = FB(537826),
    [STR_AGE_LABEL] = FB(537857), [STR_DST] = FB(537879), [STR_NO_DST] = FB(537910),
};
const char *const weekdays_ps_shaped[7] = {
    FB(537956), FB(537969), FB(537982), FB(537998), FB(538014), FB(538033), FB(538046),
};
const char *const months_ps_shaped[12] = {
    FB(538059), FB(538075), FB(538094), FB(538107), FB(538123), FB(538130), FB(538140),
    FB(538153), FB(538166), FB(538188), FB(538207), FB(538223),
};
const char lang_name_ps_shaped[] = ("\xEE" "\x80" "\xB2" "\xEE" "\x80" "\x82" "\xEE" "\x82" "\xAD" "\xEE" "\x80" "\xA9");

// or: 197 shaped cluster glyphs (Oriya Sangam MN)
// shaped-source-hash or c99f812c1858939d
const display_glyph_font_t font_or = {
    .codepoints = FB16(538240),
    .glyphs_rle = fonts_blob + 538831,
    .glyphs_off = FB16(546982),
    .glyphs_2x_rle = fonts_blob + 547378,
    .glyphs_2x_off = FB16(553804),
    .widths = fonts_blob + 538634,
    .count = 197,
    .glyph_width = 16,
};
const char *const lang_or_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(554200), [STR_SETTINGS] = FB(554206), [STR_FAIL] = FB(554222),
    [STR_TIMEZONE] = FB(554235), [STR_BRIGHTNESS] = FB(554257), [STR_LED_BLINK] = FB(554279),
    [STR_ROTATE] = FB(554301), [STR_ABOUT] = FB(554332), [STR_LANGUAGE] = FB(554351),
    [STR_DONE] = FB(554364), [STR_BACK] = FB(554386), [STR_CANCEL] = FB(554399),
    [STR_DEL] = FB(554415), [STR_RUNNING] = FB(554431), [STR_ON] = FB(554450),
    [STR_OFF] = FB(554463), [STR_NTS_NO] = FB(554470), [STR_NTS_ATTEMPT] = FB(554483),
    [STR_NTS_REQUIRE] = FB(554496), [STR_WAITING_NTP] = FB(554512),
    [STR_FMT_SYNCED] = FB(554558), [STR_FMT_SYNCING] = FB(554591),
    [STR_FMT_WAITING] = FB(554627), [STR_FMT_PEERS_NOSYNC] = FB(554653),
    [STR_FMT_PEERS_AGO] = FB(554724), [STR_WIFI_SETUP] = FB(554784),
    [STR_SCANNING] = FB(554818), [STR_SCAN_FAILED] = FB(554849), [STR_TAP_RETRY] = FB(554880),
    [STR_SELECT_NETWORK] = FB(554932), [STR_NO_NETWORKS] = FB(554963),
    [STR_NETWORK_LABEL] = FB(555012), [STR_ENTER_PASSWORD] = FB(555028),
    [STR_CONNECTING] = FB(555062), [STR_CONNECTING_TO] = FB(555099),
    [STR_CONNECTED] = FB(555130), [STR_CONNECTION_FAILED] = FB(555149),
    [STR_KB_SPACE] = FB(555183), [STR_KB_GO] = FB(555196), [STR_VERSION] = FB(555199),
    [STR_STATUS] = FB(555221), [STR_READ] = FB(555234), [STR_UPDATE] = FB(555256),
    [STR_RESTARTING] = FB(555272), [STR_OTA_UPDATE] = FB(555297), [STR_NTP_SERVER] = FB(555325),
    [STR_SERVER_LABEL] = FB(555347), [STR_NTP_SETTINGS] = FB(555360),
    [STR_NTP_PRESETS] = FB(555388), [STR_PRESETS] = FB(555416), [STR_BENCHMARK] = FB(555432),
    [STR_STOPPING] = FB(555448), [STR_NTP_STATS] = FB(555467), [STR_UNSYNCED] = FB(555507),
    [STR_SYNCS_LABEL] = FB(555532), [STR_NONE] = FB(555554), [STR_SELECT_REGION] = FB(555567),
    [STR_AGE_LABEL] = FB(555595), [STR_DST] = FB(555617), [STR_NO_DST] = FB(555642),
};
const char *const weekdays_or_shaped[7] = {
    FB(555682), FB(555692), FB(555705), FB(555715), FB(555725), FB(555738), FB(555748),
};
const char *const months_or_shaped[12] = {
    FB(555758), FB(555780), FB(555802), FB(555812), FB(555825), FB(555832), FB(555842),
    FB(555858), FB(555868), FB(555890), FB(555912), FB(555928),
};
const char lang_name_or_shaped[] = ("\xEE" "\x83" "\x82" "\xEE" "\x83" "\x83" "\xEE" "\x80" "\x83" "\xEE" "\x83" "\x84");

// sd: 180 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash sd e7a33123321227fd
const display_glyph_font_t font_sd = {
    .codepoints = FB16(555948),
    .glyphs_rle = fonts_blob + 556488,
    .glyphs_off = FB16(562960),
    .glyphs_2x_rle = fonts_blob + 563322,
    .glyphs_2x_off = FB16(567910),
    .widths = fonts_blob + 556308,
    .count = 180,
    .glyph_width = 16,
};
const char *const lang_sd_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(568272), [STR_SETTINGS] = FB(568278), [STR_FAIL] = FB(568300),
    [STR_TIMEZONE] = FB(568316), [STR_BRIGHTNESS] = FB(568353), [STR_LED_BLINK] = FB(568363),
    [STR_ROTATE] = FB(568388), [STR_ABOUT] = FB(568419), [STR_LANGUAGE] = FB(568432),
    [STR_DONE] = FB(568445), [STR_BACK] = FB(568464), [STR_CANCEL] = FB(568480),
    [STR_DEL] = FB(568496), [STR_RUNNING] = FB(568512), [STR_ON] = FB(568549),
    [STR_OFF] = FB(568562), [STR_NTS_NO] = FB(568572), [STR_NTS_ATTEMPT] = FB(568579),
    [STR_NTS_REQUIRE] = FB(568592), [STR_WAITING_NTP] = FB(568605),
    [STR_FMT_SYNCED] = FB(568654), [STR_FMT_SYNCING] = FB(568681),
    [STR_FMT_WAITING] = FB(568732), [STR_FMT_PEERS_NOSYNC] = FB(568761),
    [STR_FMT_PEERS_AGO] = FB(568844), [STR_WIFI_SETUP] = FB(568901),
    [STR_SCANNING] = FB(568938), [STR_SCAN_FAILED] = FB(568975), [STR_TAP_RETRY] = FB(569003),
    [STR_SELECT_NETWORK] = FB(569049), [STR_NO_NETWORKS] = FB(569092),
    [STR_NETWORK_LABEL] = FB(569138), [STR_ENTER_PASSWORD] = FB(569163),
    [STR_CONNECTING] = FB(569215), [STR_CONNECTING_TO] = FB(569246),
    [STR_CONNECTED] = FB(569292), [STR_CONNECTION_FAILED] = FB(569323),
    [STR_KB_SPACE] = FB(569360), [STR_KB_GO] = FB(569376), [STR_VERSION] = FB(569379),
    [STR_STATUS] = FB(569395), [STR_READ] = FB(569411), [STR_UPDATE] = FB(569442),
    [STR_RESTARTING] = FB(569458), [STR_OTA_UPDATE] = FB(569507), [STR_NTP_SERVER] = FB(569535),
    [STR_SERVER_LABEL] = FB(569560), [STR_NTP_SETTINGS] = FB(569576),
    [STR_NTP_PRESETS] = FB(569610), [STR_PRESETS] = FB(569641), [STR_BENCHMARK] = FB(569660),
    [STR_STOPPING] = FB(569673), [STR_NTP_STATS] = FB(569701), [STR_UNSYNCED] = FB(569735),
    [STR_SYNCS_LABEL] = FB(569769), [STR_NONE] = FB(569778), [STR_SELECT_REGION] = FB(569806),
    [STR_AGE_LABEL] = FB(569843), [STR_DST] = FB(569865), [STR_NO_DST] = FB(569908),
};
const char *const weekdays_sd_shaped[7] = {
    FB(569957), FB(569967), FB(569980), FB(569996), FB(570009), FB(570022), FB(570035),
};
const char *const months_sd_shaped[12] = {
    FB(570048), FB(570064), FB(570086), FB(570099), FB(570115), FB(570125), FB(570135),
    FB(570148), FB(570161), FB(570183), FB(570202), FB(570218),
};
const char lang_name_sd_shaped[] = ("\xEE" "\x82" "\xA0" "\xEE" "\x82" "\xB3" "\xEE" "\x80" "\xB5" "\xEE" "\x80" "\x86");

// mai: 193 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash mai a0c2110e905fe8bf
const display_glyph_font_t font_mai = {
    .codepoints = FB16(570234),
    .glyphs_rle = fonts_blob + 570813,
    .glyphs_off = FB16(579564),
    .glyphs_2x_rle = fonts_blob + 579952,
    .glyphs_2x_off = FB16(584448),
    .widths = fonts_blob + 570620,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_mai_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(584836), [STR_SETTINGS] = FB(584842), [STR_FAIL] = FB(584855),
    [STR_TIMEZONE] = FB(584868), [STR_BRIGHTNESS] = FB(584884), [STR_LED_BLINK] = FB(584894),
    [STR_ROTATE] = FB(584916), [STR_ABOUT] = FB(584938), [STR_LANGUAGE] = FB(584951),
    [STR_DONE] = FB(584964), [STR_BACK] = FB(584977), [STR_CANCEL] = FB(584990),
    [STR_DEL] = FB(584997), [STR_RUNNING] = FB(585007), [STR_ON] = FB(585041),
    [STR_OFF] = FB(585051), [STR_NTS_NO] = FB(585058), [STR_NTS_ATTEMPT] = FB(585068),
    [STR_NTS_REQUIRE] = FB(585081), [STR_WAITING_NTP] = FB(585094),
    [STR_FMT_SYNCED] = FB(585137), [STR_FMT_SYNCING] = FB(585164),
    [STR_FMT_WAITING] = FB(585206), [STR_FMT_PEERS_NOSYNC] = FB(585232),
    [STR_FMT_PEERS_AGO] = FB(585300), [STR_WIFI_SETUP] = FB(585357),
    [STR_SCANNING] = FB(585385), [STR_SCAN_FAILED] = FB(585419), [STR_TAP_RETRY] = FB(585444),
    [STR_SELECT_NETWORK] = FB(585493), [STR_NO_NETWORKS] = FB(585512),
    [STR_NETWORK_LABEL] = FB(585546), [STR_ENTER_PASSWORD] = FB(585562),
    [STR_CONNECTING] = FB(585587), [STR_CONNECTING_TO] = FB(585606),
    [STR_CONNECTED] = FB(585631), [STR_CONNECTION_FAILED] = FB(585647),
    [STR_KB_SPACE] = FB(585675), [STR_KB_GO] = FB(585682), [STR_VERSION] = FB(585685),
    [STR_STATUS] = FB(585701), [STR_READ] = FB(585717), [STR_UPDATE] = FB(585736),
    [STR_RESTARTING] = FB(585746), [STR_OTA_UPDATE] = FB(585786), [STR_NTP_SERVER] = FB(585808),
    [STR_SERVER_LABEL] = FB(585827), [STR_NTP_SETTINGS] = FB(585837),
    [STR_NTP_PRESETS] = FB(585862), [STR_PRESETS] = FB(585887), [STR_BENCHMARK] = FB(585900),
    [STR_STOPPING] = FB(585907), [STR_NTP_STATS] = FB(585929), [STR_UNSYNCED] = FB(585957),
    [STR_SYNCS_LABEL] = FB(585982), [STR_NONE] = FB(586007), [STR_SELECT_REGION] = FB(586032),
    [STR_AGE_LABEL] = FB(586042), [STR_DST] = FB(586058), [STR_NO_DST] = FB(586080),
};
const char *const weekdays_mai_shaped[7] = {
    FB(586114), FB(586124), FB(586134), FB(586141), FB(586145), FB(586149), FB(586156),
};
const char *const months_mai_shaped[12] = {
    FB(586166), FB(586176), FB(586186), FB(586196), FB(586203), FB(586210), FB(586214),
    FB(586224), FB(586234), FB(586247), FB(586257), FB(586267),
};
const char lang_name_mai_shaped[] = ("\xEE" "\x82" "\xBE" "\xEE" "\x82" "\xBF" "\xEE" "\x83" "\x80" "\xEE" "\x81" "\x80");

