// Generated by tools/gen_fonts.swift; do not edit by hand.
// Bulk glyph and string data lives in fonts.bin (embedded into the app
// image via EMBED_FILES); everything here is offsets into that blob.
#include "fonts.h"

#ifndef FONTS_BLOB_HOST
extern const uint8_t fonts_blob[] __asm__("_binary_fonts_bin_start");
#else
extern const uint8_t fonts_blob[];  // host harness provides the blob
#endif

// Pointer-into-blob shorthands: FB is a string, FB16 a uint16 table.
#define FB(off)   ((const char *)(fonts_blob + (off)))
#define FB16(off) ((const uint16_t *)(const void *)(fonts_blob + (off)))
// hy: 57 glyphs (Noto Sans Armenian)
const display_glyph_font_t font_hy = {
    .codepoints = FB16(0),
    .glyphs_rle = fonts_blob + 114,
    .glyphs_off = FB16(2570),
    .glyphs_2x_rle = fonts_blob + 2686,
    .glyphs_2x_off = FB16(4948),
    .count = 57,
    .glyph_width = 10,
};
// ja: 112 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_ja = {
    .codepoints = FB16(5064),
    .glyphs_rle = fonts_blob + 5288,
    .glyphs_off = FB16(14654),
    .glyphs_2x_rle = fonts_blob + 14880,
    .glyphs_2x_off = FB16(16824),
    .count = 112,
    .glyph_width = 16,
};
// ka: 29 glyphs (Helvetica)
const display_glyph_font_t font_ka = {
    .codepoints = FB16(17050),
    .glyphs_rle = fonts_blob + 17108,
    .glyphs_off = FB16(18742),
    .glyphs_2x_rle = fonts_blob + 18802,
    .glyphs_2x_off = FB16(21554),
    .count = 29,
    .glyph_width = 10,
};
// ko: 104 glyphs (Apple SD Gothic Neo)
const display_glyph_font_t font_ko = {
    .codepoints = FB16(21614),
    .glyphs_rle = fonts_blob + 21822,
    .glyphs_off = FB16(29544),
    .glyphs_2x_rle = fonts_blob + 29754,
    .glyphs_2x_off = FB16(31252),
    .count = 104,
    .glyph_width = 16,
};
// zh: 114 glyphs (Hiragino Sans GB)
const display_glyph_font_t font_zh = {
    .codepoints = FB16(31462),
    .glyphs_rle = fonts_blob + 31690,
    .glyphs_off = FB16(42018),
    .glyphs_2x_rle = fonts_blob + 42248,
    .glyphs_2x_off = FB16(43908),
    .count = 114,
    .glyph_width = 16,
};
// zh_hant: 115 glyphs (PingFang TC)
const display_glyph_font_t font_zh_hant = {
    .codepoints = FB16(44138),
    .glyphs_rle = fonts_blob + 44368,
    .glyphs_off = FB16(54286),
    .glyphs_2x_rle = fonts_blob + 54518,
    .glyphs_2x_off = FB16(56124),
    .count = 115,
    .glyph_width = 16,
};
// base: ASCII plus 272 supplementary glyphs (Menlo)
const uint8_t *const font_base_ascii_rle = fonts_blob + 56356;
const uint16_t *const font_base_ascii_off = FB16(59624);
const uint8_t *const font_base_ascii_2x_rle = fonts_blob + 59816;
const uint16_t *const font_base_ascii_2x_off = FB16(65466);
const uint16_t *const font_base_ext_cp = FB16(65658);
const uint8_t *const font_base_ext_rle = fonts_blob + 66202;
const uint16_t *const font_base_ext_off = FB16(77556);
const uint8_t *const font_base_ext_2x_rle = fonts_blob + 78102;
const uint16_t *const font_base_ext_2x_off = FB16(91338);
const uint16_t font_base_ext_count = 272;
// ar: 178 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ar 3321610560661b54
const display_glyph_font_t font_ar = {
    .codepoints = FB16(91884),
    .glyphs_rle = fonts_blob + 92418,
    .glyphs_off = FB16(99110),
    .glyphs_2x_rle = fonts_blob + 99468,
    .glyphs_2x_off = FB16(103824),
    .widths = fonts_blob + 92240,
    .count = 178,
    .glyph_width = 16,
};
const char *const lang_ar_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(104182), [STR_WIFI] = FB(104207), [STR_FAIL] = FB(104213),
    [STR_TIMEZONE] = FB(104223), [STR_BRIGHTNESS] = FB(104266), [STR_LED_BLINK] = FB(104285),
    [STR_ROTATE] = FB(104310), [STR_ABOUT] = FB(104338), [STR_LANGUAGE] = FB(104348),
    [STR_DONE] = FB(104364), [STR_BACK] = FB(104371), [STR_CANCEL] = FB(104384),
    [STR_DEL] = FB(104400), [STR_RUNNING] = FB(104410), [STR_ON] = FB(104423),
    [STR_OFF] = FB(104436), [STR_NTS_NO] = FB(104449), [STR_NTS_ATTEMPT] = FB(104453),
    [STR_NTS_REQUIRE] = FB(104472), [STR_WAITING_NTP] = FB(104488),
    [STR_FMT_SYNCED] = FB(104531), [STR_FMT_SYNCING] = FB(104558),
    [STR_FMT_WAITING] = FB(104585), [STR_WIFI_SETUP] = FB(104614), [STR_SCANNING] = FB(104648),
    [STR_SCAN_FAILED] = FB(104670), [STR_TAP_RETRY] = FB(104698),
    [STR_SELECT_NETWORK] = FB(104753), [STR_NO_NETWORKS] = FB(104787),
    [STR_NETWORK_LABEL] = FB(104824), [STR_ENTER_PASSWORD] = FB(104846),
    [STR_CONNECTING] = FB(104892), [STR_CONNECTING_TO] = FB(104905),
    [STR_CONNECTED] = FB(104933), [STR_CONNECTION_FAILED] = FB(104949),
    [STR_KB_SPACE] = FB(104980), [STR_KB_GO] = FB(104996), [STR_VERSION] = FB(104999),
    [STR_STATUS] = FB(105021), [STR_READ] = FB(105043), [STR_UPDATE] = FB(105056),
    [STR_RESTARTING] = FB(105072), [STR_OTA_UPDATE] = FB(105106), [STR_NTP_SERVER] = FB(105134),
    [STR_SERVER_LABEL] = FB(105159), [STR_NTP_SETTINGS] = FB(105181),
    [STR_NTP_PRESETS] = FB(105215), [STR_PRESETS] = FB(105243), [STR_BENCHMARK] = FB(105259),
    [STR_STOPPING] = FB(105278), [STR_NTP_STATS] = FB(105294), [STR_UNSYNCED] = FB(105328),
    [STR_NONE] = FB(105359), [STR_SELECT_REGION] = FB(105375), [STR_AGE_LABEL] = FB(105409),
    [STR_SYNCS_LABEL] = FB(105437), [STR_FMT_PEERS_NOSYNC] = FB(105468),
    [STR_FMT_PEERS_AGO] = FB(105542), [STR_DST] = FB(105606), [STR_NO_DST] = FB(105637),
};
const char *const weekdays_ar_shaped[7] = {
    FB(105677), FB(105690), FB(105706), FB(105728), FB(105750), FB(105769), FB(105788),
};
const char *const months_ar_shaped[12] = {
    FB(105804), FB(105814), FB(105824), FB(105834), FB(105844), FB(105854), FB(105864),
    FB(105874), FB(105884), FB(105894), FB(105904), FB(105914),
};
const char lang_name_ar_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\xA1" "\xEE" "\x80" "\xB8" "\xEE" "\x80" "\xAB" "\xEE" "\x80" "\xAC");

// fa: 211 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash fa dbfe059c4f36839d
const display_glyph_font_t font_fa = {
    .codepoints = FB16(105924),
    .glyphs_rle = fonts_blob + 106557,
    .glyphs_off = FB16(114658),
    .glyphs_2x_rle = fonts_blob + 115082,
    .glyphs_2x_off = FB16(120616),
    .widths = fonts_blob + 106346,
    .count = 211,
    .glyph_width = 16,
};
const char *const lang_fa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(121040), [STR_WIFI] = FB(121062), [STR_FAIL] = FB(121068),
    [STR_TIMEZONE] = FB(121078), [STR_BRIGHTNESS] = FB(121112), [STR_LED_BLINK] = FB(121134),
    [STR_ROTATE] = FB(121159), [STR_ABOUT] = FB(121184), [STR_LANGUAGE] = FB(121203),
    [STR_DONE] = FB(121216), [STR_BACK] = FB(121232), [STR_CANCEL] = FB(121251),
    [STR_DEL] = FB(121261), [STR_RUNNING] = FB(121271), [STR_ON] = FB(121305),
    [STR_OFF] = FB(121318), [STR_NTS_NO] = FB(121334), [STR_NTS_ATTEMPT] = FB(121344),
    [STR_NTS_REQUIRE] = FB(121354), [STR_WAITING_NTP] = FB(121370),
    [STR_FMT_SYNCED] = FB(121419), [STR_FMT_SYNCING] = FB(121443),
    [STR_FMT_WAITING] = FB(121476), [STR_WIFI_SETUP] = FB(121505), [STR_SCANNING] = FB(121539),
    [STR_SCAN_FAILED] = FB(121564), [STR_TAP_RETRY] = FB(121601),
    [STR_SELECT_NETWORK] = FB(121665), [STR_NO_NETWORKS] = FB(121699),
    [STR_NETWORK_LABEL] = FB(121742), [STR_ENTER_PASSWORD] = FB(121758),
    [STR_CONNECTING] = FB(121819), [STR_CONNECTING_TO] = FB(121856),
    [STR_CONNECTED] = FB(121881), [STR_CONNECTION_FAILED] = FB(121906),
    [STR_KB_SPACE] = FB(121943), [STR_KB_GO] = FB(121959), [STR_VERSION] = FB(121962),
    [STR_STATUS] = FB(121978), [STR_READ] = FB(121997), [STR_UPDATE] = FB(122019),
    [STR_RESTARTING] = FB(122047), [STR_OTA_UPDATE] = FB(122087), [STR_NTP_SERVER] = FB(122127),
    [STR_SERVER_LABEL] = FB(122152), [STR_NTP_SETTINGS] = FB(122168),
    [STR_NTP_PRESETS] = FB(122202), [STR_PRESETS] = FB(122236), [STR_BENCHMARK] = FB(122261),
    [STR_STOPPING] = FB(122277), [STR_NTP_STATS] = FB(122290), [STR_UNSYNCED] = FB(122315),
    [STR_NONE] = FB(122337), [STR_SELECT_REGION] = FB(122347), [STR_AGE_LABEL] = FB(122384),
    [STR_SYNCS_LABEL] = FB(122406), [STR_FMT_PEERS_NOSYNC] = FB(122434),
    [STR_FMT_PEERS_AGO] = FB(122514), [STR_DST] = FB(122574), [STR_NO_DST] = FB(122614),
};
const char *const weekdays_fa_shaped[7] = {
    FB(122669), FB(122688), FB(122707), FB(122723), FB(122748), FB(122770), FB(122783),
};
const char *const months_fa_shaped[12] = {
    FB(122796), FB(122818), FB(122843), FB(122859), FB(122869), FB(122885), FB(122904),
    FB(122914), FB(122927), FB(122937), FB(122944), FB(122957),
};
const char lang_name_fa_shaped[] = ("\xEE" "\x80" "\x89" "\xEE" "\x83" "\x88" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\x81" "\xEE" "\x81" "\xB2");

// he: 98 shaped cluster glyphs (Arial Hebrew)
// shaped-source-hash he 04d99dae314644b5
const display_glyph_font_t font_he = {
    .codepoints = FB16(122974),
    .glyphs_rle = fonts_blob + 123268,
    .glyphs_off = FB16(126964),
    .glyphs_2x_rle = fonts_blob + 127162,
    .glyphs_2x_off = FB16(130066),
    .widths = fonts_blob + 123170,
    .count = 98,
    .glyph_width = 16,
};
const char *const lang_he_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(130264), [STR_WIFI] = FB(130283), [STR_FAIL] = FB(130289),
    [STR_TIMEZONE] = FB(130302), [STR_BRIGHTNESS] = FB(130327), [STR_LED_BLINK] = FB(130346),
    [STR_ROTATE] = FB(130374), [STR_ABOUT] = FB(130402), [STR_LANGUAGE] = FB(130418),
    [STR_DONE] = FB(130428), [STR_BACK] = FB(130441), [STR_CANCEL] = FB(130454),
    [STR_DEL] = FB(130470), [STR_RUNNING] = FB(130480), [STR_ON] = FB(130493),
    [STR_OFF] = FB(130506), [STR_NTS_NO] = FB(130519), [STR_NTS_ATTEMPT] = FB(130526),
    [STR_NTS_REQUIRE] = FB(130536), [STR_WAITING_NTP] = FB(130549),
    [STR_FMT_SYNCED] = FB(130592), [STR_FMT_SYNCING] = FB(130622),
    [STR_FMT_WAITING] = FB(130652), [STR_WIFI_SETUP] = FB(130678), [STR_SCANNING] = FB(130712),
    [STR_SCAN_FAILED] = FB(130734), [STR_TAP_RETRY] = FB(130771),
    [STR_SELECT_NETWORK] = FB(130820), [STR_NO_NETWORKS] = FB(130842),
    [STR_NETWORK_LABEL] = FB(130885), [STR_ENTER_PASSWORD] = FB(130898),
    [STR_CONNECTING] = FB(130926), [STR_CONNECTING_TO] = FB(130942),
    [STR_CONNECTED] = FB(130967), [STR_CONNECTION_FAILED] = FB(130986),
    [STR_KB_SPACE] = FB(131020), [STR_KB_GO] = FB(131033), [STR_VERSION] = FB(131036),
    [STR_STATUS] = FB(131052), [STR_READ] = FB(131065), [STR_UPDATE] = FB(131081),
    [STR_RESTARTING] = FB(131094), [STR_OTA_UPDATE] = FB(131125), [STR_NTP_SERVER] = FB(131153),
    [STR_SERVER_LABEL] = FB(131175), [STR_NTP_SETTINGS] = FB(131188),
    [STR_NTP_PRESETS] = FB(131219), [STR_PRESETS] = FB(131253), [STR_BENCHMARK] = FB(131278),
    [STR_STOPPING] = FB(131294), [STR_NTP_STATS] = FB(131307), [STR_UNSYNCED] = FB(131347),
    [STR_NONE] = FB(131378), [STR_SELECT_REGION] = FB(131388), [STR_AGE_LABEL] = FB(131413),
    [STR_SYNCS_LABEL] = FB(131435), [STR_FMT_PEERS_NOSYNC] = FB(131466),
    [STR_FMT_PEERS_AGO] = FB(131549), [STR_DST] = FB(131619), [STR_NO_DST] = FB(131644),
};
const char *const weekdays_he_shaped[7] = {
    FB(131681), FB(131700), FB(131719), FB(131738), FB(131757), FB(131776), FB(131795),
};
const char *const months_he_shaped[12] = {
    FB(131805), FB(131815), FB(131825), FB(131835), FB(131845), FB(131855), FB(131865),
    FB(131875), FB(131885), FB(131895), FB(131905), FB(131915),
};
const char lang_name_he_shaped[] = ("\xEE" "\x80" "\x80" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x82" "\xEE" "\x80" "\x98" "\xEE" "\x80" "\xA6");

// hi: 186 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash hi fb71ec9a96a8553e
const display_glyph_font_t font_hi = {
    .codepoints = FB16(131926),
    .glyphs_rle = fonts_blob + 132484,
    .glyphs_off = FB16(140846),
    .glyphs_2x_rle = fonts_blob + 141220,
    .glyphs_2x_off = FB16(145572),
    .widths = fonts_blob + 132298,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_hi_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(145946), [STR_WIFI] = FB(145959), [STR_FAIL] = FB(145965),
    [STR_TIMEZONE] = FB(145978), [STR_BRIGHTNESS] = FB(145994), [STR_LED_BLINK] = FB(146004),
    [STR_ROTATE] = FB(146029), [STR_ABOUT] = FB(146054), [STR_LANGUAGE] = FB(146076),
    [STR_DONE] = FB(146089), [STR_BACK] = FB(146108), [STR_CANCEL] = FB(146121),
    [STR_DEL] = FB(146128), [STR_RUNNING] = FB(146144), [STR_ON] = FB(146163),
    [STR_OFF] = FB(146173), [STR_NTS_NO] = FB(146177), [STR_NTS_ATTEMPT] = FB(146187),
    [STR_NTS_REQUIRE] = FB(146200), [STR_WAITING_NTP] = FB(146213),
    [STR_FMT_SYNCED] = FB(146259), [STR_FMT_SYNCING] = FB(146280),
    [STR_FMT_WAITING] = FB(146322), [STR_WIFI_SETUP] = FB(146348), [STR_SCANNING] = FB(146376),
    [STR_SCAN_FAILED] = FB(146407), [STR_TAP_RETRY] = FB(146432),
    [STR_SELECT_NETWORK] = FB(146475), [STR_NO_NETWORKS] = FB(146494),
    [STR_NETWORK_LABEL] = FB(146531), [STR_ENTER_PASSWORD] = FB(146547),
    [STR_CONNECTING] = FB(146575), [STR_CONNECTING_TO] = FB(146597),
    [STR_CONNECTED] = FB(146622), [STR_CONNECTION_FAILED] = FB(146641),
    [STR_KB_SPACE] = FB(146669), [STR_KB_GO] = FB(146676), [STR_VERSION] = FB(146679),
    [STR_STATUS] = FB(146695), [STR_READ] = FB(146711), [STR_UPDATE] = FB(146724),
    [STR_RESTARTING] = FB(146734), [STR_OTA_UPDATE] = FB(146750), [STR_NTP_SERVER] = FB(146772),
    [STR_SERVER_LABEL] = FB(146791), [STR_NTP_SETTINGS] = FB(146801),
    [STR_NTP_PRESETS] = FB(146826), [STR_PRESETS] = FB(146857), [STR_BENCHMARK] = FB(146876),
    [STR_STOPPING] = FB(146892), [STR_NTP_STATS] = FB(146911), [STR_UNSYNCED] = FB(146936),
    [STR_NONE] = FB(146961), [STR_SELECT_REGION] = FB(146983), [STR_AGE_LABEL] = FB(146993),
    [STR_SYNCS_LABEL] = FB(147009), [STR_FMT_PEERS_NOSYNC] = FB(147034),
    [STR_FMT_PEERS_AGO] = FB(147102), [STR_DST] = FB(147156), [STR_NO_DST] = FB(147178),
};
const char *const weekdays_hi_shaped[7] = {
    FB(147212), FB(147222), FB(147232), FB(147239), FB(147243), FB(147247), FB(147254),
};
const char *const months_hi_shaped[12] = {
    FB(147264), FB(147274), FB(147284), FB(147294), FB(147301), FB(147308), FB(147312),
    FB(147322), FB(147332), FB(147345), FB(147358), FB(147368),
};
const char lang_name_hi_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\xA5" "\xEE" "\x82" "\xB9" "\xEE" "\x80" "\xA1");

// bn: 169 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash bn cf309888208f71a7
const display_glyph_font_t font_bn = {
    .codepoints = FB16(147382),
    .glyphs_rle = fonts_blob + 147889,
    .glyphs_off = FB16(155072),
    .glyphs_2x_rle = fonts_blob + 155412,
    .glyphs_2x_off = FB16(160256),
    .widths = fonts_blob + 147720,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_bn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(160596), [STR_WIFI] = FB(160612), [STR_FAIL] = FB(160618),
    [STR_TIMEZONE] = FB(160628), [STR_BRIGHTNESS] = FB(160650), [STR_LED_BLINK] = FB(160666),
    [STR_ROTATE] = FB(160688), [STR_ABOUT] = FB(160719), [STR_LANGUAGE] = FB(160735),
    [STR_DONE] = FB(160748), [STR_BACK] = FB(160758), [STR_CANCEL] = FB(160774),
    [STR_DEL] = FB(160790), [STR_RUNNING] = FB(160800), [STR_ON] = FB(160813),
    [STR_OFF] = FB(160823), [STR_NTS_NO] = FB(160830), [STR_NTS_ATTEMPT] = FB(160837),
    [STR_NTS_REQUIRE] = FB(160850), [STR_WAITING_NTP] = FB(160866),
    [STR_FMT_SYNCED] = FB(160906), [STR_FMT_SYNCING] = FB(160927),
    [STR_FMT_WAITING] = FB(160960), [STR_WIFI_SETUP] = FB(160986), [STR_SCANNING] = FB(161020),
    [STR_SCAN_FAILED] = FB(161042), [STR_TAP_RETRY] = FB(161067),
    [STR_SELECT_NETWORK] = FB(161122), [STR_NO_NETWORKS] = FB(161165),
    [STR_NETWORK_LABEL] = FB(161202), [STR_ENTER_PASSWORD] = FB(161230),
    [STR_CONNECTING] = FB(161267), [STR_CONNECTING_TO] = FB(161298),
    [STR_CONNECTED] = FB(161332), [STR_CONNECTION_FAILED] = FB(161351),
    [STR_KB_SPACE] = FB(161382), [STR_KB_GO] = FB(161392), [STR_VERSION] = FB(161395),
    [STR_STATUS] = FB(161414), [STR_READ] = FB(161430), [STR_UPDATE] = FB(161443),
    [STR_RESTARTING] = FB(161459), [STR_OTA_UPDATE] = FB(161484), [STR_NTP_SERVER] = FB(161512),
    [STR_SERVER_LABEL] = FB(161543), [STR_NTP_SETTINGS] = FB(161565),
    [STR_NTP_PRESETS] = FB(161593), [STR_PRESETS] = FB(161627), [STR_BENCHMARK] = FB(161649),
    [STR_STOPPING] = FB(161665), [STR_NTP_STATS] = FB(161681), [STR_UNSYNCED] = FB(161721),
    [STR_NONE] = FB(161746), [STR_SELECT_REGION] = FB(161771), [STR_AGE_LABEL] = FB(161799),
    [STR_SYNCS_LABEL] = FB(161821), [STR_FMT_PEERS_NOSYNC] = FB(161846),
    [STR_FMT_PEERS_AGO] = FB(161926), [STR_DST] = FB(161992), [STR_NO_DST] = FB(162014),
};
const char *const weekdays_bn_shaped[7] = {
    FB(162048), FB(162058), FB(162071), FB(162081), FB(162091), FB(162101), FB(162108),
};
const char *const months_bn_shaped[12] = {
    FB(162118), FB(162128), FB(162138), FB(162151), FB(162161), FB(162168), FB(162175),
    FB(162185), FB(162192), FB(162202), FB(162215), FB(162225),
};
const char lang_name_bn_shaped[] = ("\xEE" "\x80" "\x84" "\xEE" "\x80" "\x98" "\xEE" "\x81" "\xA5" "\xEE" "\x80" "\x8C" "\xEE" "\x80" "\x98");

// th: 162 shaped cluster glyphs (Thonburi)
// shaped-source-hash th 0031e23b06de2ba5
const display_glyph_font_t font_th = {
    .codepoints = FB16(162238),
    .glyphs_rle = fonts_blob + 162724,
    .glyphs_off = FB16(168506),
    .glyphs_2x_rle = fonts_blob + 168832,
    .glyphs_2x_off = FB16(170982),
    .widths = fonts_blob + 162562,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_th_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(171308), [STR_WIFI] = FB(171330), [STR_FAIL] = FB(171336),
    [STR_TIMEZONE] = FB(171355), [STR_BRIGHTNESS] = FB(171377), [STR_LED_BLINK] = FB(171402),
    [STR_ROTATE] = FB(171430), [STR_ABOUT] = FB(171452), [STR_LANGUAGE] = FB(171471),
    [STR_DONE] = FB(171484), [STR_BACK] = FB(171497), [STR_CANCEL] = FB(171507),
    [STR_DEL] = FB(171523), [STR_RUNNING] = FB(171530), [STR_ON] = FB(171552),
    [STR_OFF] = FB(171562), [STR_NTS_NO] = FB(171569), [STR_NTS_ATTEMPT] = FB(171576),
    [STR_NTS_REQUIRE] = FB(171586), [STR_WAITING_NTP] = FB(171599),
    [STR_FMT_SYNCED] = FB(171627), [STR_FMT_SYNCING] = FB(171654),
    [STR_FMT_WAITING] = FB(171681), [STR_WIFI_SETUP] = FB(171698), [STR_SCANNING] = FB(171729),
    [STR_SCAN_FAILED] = FB(171760), [STR_TAP_RETRY] = FB(171791),
    [STR_SELECT_NETWORK] = FB(171828), [STR_NO_NETWORKS] = FB(171862),
    [STR_NETWORK_LABEL] = FB(171896), [STR_ENTER_PASSWORD] = FB(171921),
    [STR_CONNECTING] = FB(171946), [STR_CONNECTING_TO] = FB(171974),
    [STR_CONNECTED] = FB(171999), [STR_CONNECTION_FAILED] = FB(172030),
    [STR_KB_SPACE] = FB(172067), [STR_KB_GO] = FB(172089), [STR_VERSION] = FB(172092),
    [STR_STATUS] = FB(172114), [STR_READ] = FB(172133), [STR_UPDATE] = FB(172146),
    [STR_RESTARTING] = FB(172162), [STR_OTA_UPDATE] = FB(172190), [STR_NTP_SERVER] = FB(172218),
    [STR_SERVER_LABEL] = FB(172255), [STR_NTP_SETTINGS] = FB(172283),
    [STR_NTP_PRESETS] = FB(172308), [STR_PRESETS] = FB(172339), [STR_BENCHMARK] = FB(172358),
    [STR_STOPPING] = FB(172374), [STR_NTP_STATS] = FB(172393), [STR_UNSYNCED] = FB(172415),
    [STR_NONE] = FB(172431), [STR_SELECT_REGION] = FB(172441), [STR_AGE_LABEL] = FB(172469),
    [STR_SYNCS_LABEL] = FB(172491), [STR_FMT_PEERS_NOSYNC] = FB(172513),
    [STR_FMT_PEERS_AGO] = FB(172578), [STR_DST] = FB(172641), [STR_NO_DST] = FB(172672),
};
const char *const weekdays_th_shaped[7] = {
    FB(172712), FB(172722), FB(172729), FB(172736), FB(172743), FB(172753), FB(172760),
};
const char *const months_th_shaped[12] = {
    FB(172767), FB(172780), FB(172793), FB(172806), FB(172822), FB(172835), FB(172848),
    FB(172861), FB(172874), FB(172887), FB(172900), FB(172913),
};
const char lang_name_th_shaped[] = ("\xEE" "\x80" "\xB9" "\xEE" "\x82" "\xA1" "\xEE" "\x82" "\x9E");

// ur: 195 shaped cluster glyphs (Geeza Pro)
// shaped-source-hash ur e35c9ea86d6afe82
const display_glyph_font_t font_ur = {
    .codepoints = FB16(172926),
    .glyphs_rle = fonts_blob + 173511,
    .glyphs_off = FB16(180512),
    .glyphs_2x_rle = fonts_blob + 180904,
    .glyphs_2x_off = FB16(185078),
    .widths = fonts_blob + 173316,
    .count = 195,
    .glyph_width = 16,
};
const char *const lang_ur_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(185470), [STR_WIFI] = FB(185492), [STR_FAIL] = FB(185498),
    [STR_TIMEZONE] = FB(185514), [STR_BRIGHTNESS] = FB(185539), [STR_LED_BLINK] = FB(185549),
    [STR_ROTATE] = FB(185574), [STR_ABOUT] = FB(185608), [STR_LANGUAGE] = FB(185624),
    [STR_DONE] = FB(185637), [STR_BACK] = FB(185656), [STR_CANCEL] = FB(185669),
    [STR_DEL] = FB(185685), [STR_RUNNING] = FB(185704), [STR_ON] = FB(185732),
    [STR_OFF] = FB(185739), [STR_NTS_NO] = FB(185746), [STR_NTS_ATTEMPT] = FB(185759),
    [STR_NTS_REQUIRE] = FB(185772), [STR_WAITING_NTP] = FB(185785),
    [STR_FMT_SYNCED] = FB(185834), [STR_FMT_SYNCING] = FB(185864),
    [STR_FMT_WAITING] = FB(185897), [STR_WIFI_SETUP] = FB(185926), [STR_SCANNING] = FB(185963),
    [STR_SCAN_FAILED] = FB(185997), [STR_TAP_RETRY] = FB(186025),
    [STR_SELECT_NETWORK] = FB(186113), [STR_NO_NETWORKS] = FB(186150),
    [STR_NETWORK_LABEL] = FB(186202), [STR_ENTER_PASSWORD] = FB(186227),
    [STR_CONNECTING] = FB(186276), [STR_CONNECTING_TO] = FB(186322),
    [STR_CONNECTED] = FB(186371), [STR_CONNECTION_FAILED] = FB(186390),
    [STR_KB_SPACE] = FB(186424), [STR_KB_GO] = FB(186449), [STR_VERSION] = FB(186452),
    [STR_STATUS] = FB(186468), [STR_READ] = FB(186484), [STR_UPDATE] = FB(186500),
    [STR_RESTARTING] = FB(186519), [STR_OTA_UPDATE] = FB(186553), [STR_NTP_SERVER] = FB(186584),
    [STR_SERVER_LABEL] = FB(186609), [STR_NTP_SETTINGS] = FB(186625),
    [STR_NTP_PRESETS] = FB(186659), [STR_PRESETS] = FB(186693), [STR_BENCHMARK] = FB(186715),
    [STR_STOPPING] = FB(186728), [STR_NTP_STATS] = FB(186756), [STR_UNSYNCED] = FB(186805),
    [STR_NONE] = FB(186839), [STR_SELECT_REGION] = FB(186864), [STR_AGE_LABEL] = FB(186889),
    [STR_SYNCS_LABEL] = FB(186911), [STR_FMT_PEERS_NOSYNC] = FB(186933),
    [STR_FMT_PEERS_AGO] = FB(187019), [STR_DST] = FB(187082), [STR_NO_DST] = FB(187113),
};
const char *const weekdays_ur_shaped[7] = {
    FB(187159), FB(187175), FB(187185), FB(187198), FB(187208), FB(187227), FB(187240),
};
const char *const months_ur_shaped[12] = {
    FB(187253), FB(187269), FB(187285), FB(187298), FB(187314), FB(187324), FB(187334),
    FB(187350), FB(187363), FB(187379), FB(187398), FB(187414),
};
const char lang_name_ur_shaped[] = ("\xEE" "\x80" "\x8B" "\xEE" "\x83" "\x82" "\xEE" "\x81" "\x84" "\xEE" "\x81" "\x88");

// mr: 179 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash mr 0004a1284112fffe
const display_glyph_font_t font_mr = {
    .codepoints = FB16(187430),
    .glyphs_rle = fonts_blob + 187967,
    .glyphs_off = FB16(196104),
    .glyphs_2x_rle = fonts_blob + 196464,
    .glyphs_2x_off = FB16(201156),
    .widths = fonts_blob + 187788,
    .count = 179,
    .glyph_width = 16,
};
const char *const lang_mr_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(201516), [STR_WIFI] = FB(201529), [STR_FAIL] = FB(201535),
    [STR_TIMEZONE] = FB(201551), [STR_BRIGHTNESS] = FB(201561), [STR_LED_BLINK] = FB(201571),
    [STR_ROTATE] = FB(201596), [STR_ABOUT] = FB(201624), [STR_LANGUAGE] = FB(201643),
    [STR_DONE] = FB(201656), [STR_BACK] = FB(201666), [STR_CANCEL] = FB(201676),
    [STR_DEL] = FB(201683), [STR_RUNNING] = FB(201696), [STR_ON] = FB(201709),
    [STR_OFF] = FB(201719), [STR_NTS_NO] = FB(201723), [STR_NTS_ATTEMPT] = FB(201736),
    [STR_NTS_REQUIRE] = FB(201746), [STR_WAITING_NTP] = FB(201759),
    [STR_FMT_SYNCED] = FB(201805), [STR_FMT_SYNCING] = FB(201826),
    [STR_FMT_WAITING] = FB(201868), [STR_WIFI_SETUP] = FB(201894), [STR_SCANNING] = FB(201922),
    [STR_SCAN_FAILED] = FB(201953), [STR_TAP_RETRY] = FB(201981),
    [STR_SELECT_NETWORK] = FB(202039), [STR_NO_NETWORKS] = FB(202070),
    [STR_NETWORK_LABEL] = FB(202098), [STR_ENTER_PASSWORD] = FB(202114),
    [STR_CONNECTING] = FB(202142), [STR_CONNECTING_TO] = FB(202164),
    [STR_CONNECTED] = FB(202189), [STR_CONNECTION_FAILED] = FB(202202),
    [STR_KB_SPACE] = FB(202233), [STR_KB_GO] = FB(202240), [STR_VERSION] = FB(202243),
    [STR_STATUS] = FB(202256), [STR_READ] = FB(202272), [STR_UPDATE] = FB(202285),
    [STR_RESTARTING] = FB(202295), [STR_OTA_UPDATE] = FB(202308), [STR_NTP_SERVER] = FB(202330),
    [STR_SERVER_LABEL] = FB(202352), [STR_NTP_SETTINGS] = FB(202365),
    [STR_NTP_PRESETS] = FB(202390), [STR_PRESETS] = FB(202421), [STR_BENCHMARK] = FB(202440),
    [STR_STOPPING] = FB(202456), [STR_NTP_STATS] = FB(202475), [STR_UNSYNCED] = FB(202506),
    [STR_NONE] = FB(202534), [STR_SELECT_REGION] = FB(202562), [STR_AGE_LABEL] = FB(202590),
    [STR_SYNCS_LABEL] = FB(202609), [STR_FMT_PEERS_NOSYNC] = FB(202634),
    [STR_FMT_PEERS_AGO] = FB(202708), [STR_DST] = FB(202765), [STR_NO_DST] = FB(202787),
};
const char *const weekdays_mr_shaped[7] = {
    FB(202824), FB(202834), FB(202844), FB(202851), FB(202855), FB(202859), FB(202866),
};
const char *const months_mr_shaped[12] = {
    FB(202876), FB(202886), FB(202896), FB(202906), FB(202916), FB(202920), FB(202924),
    FB(202931), FB(202938), FB(202945), FB(202955), FB(202965),
};
const char lang_name_mr_shaped[] = ("\xEE" "\x80" "\x9D" "\xEE" "\x80" "\x97" "\xEE" "\x80" "\x9E" "\xEE" "\x82" "\xB2" "\xEE" "\x80" "\xB4");

// ta: 158 shaped cluster glyphs (Tamil Sangam MN)
// shaped-source-hash ta a2efda2869793b62
const display_glyph_font_t font_ta = {
    .codepoints = FB16(202976),
    .glyphs_rle = fonts_blob + 203450,
    .glyphs_off = FB16(210728),
    .glyphs_2x_rle = fonts_blob + 211046,
    .glyphs_2x_off = FB16(216338),
    .widths = fonts_blob + 203292,
    .count = 158,
    .glyph_width = 16,
};
const char *const lang_ta_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(216656), [STR_WIFI] = FB(216678), [STR_FAIL] = FB(216684),
    [STR_TIMEZONE] = FB(216700), [STR_BRIGHTNESS] = FB(216728), [STR_LED_BLINK] = FB(216741),
    [STR_ROTATE] = FB(216766), [STR_ABOUT] = FB(216791), [STR_LANGUAGE] = FB(216801),
    [STR_DONE] = FB(216814), [STR_BACK] = FB(216830), [STR_CANCEL] = FB(216837),
    [STR_DEL] = FB(216847), [STR_RUNNING] = FB(216857), [STR_ON] = FB(216879),
    [STR_OFF] = FB(216892), [STR_NTS_NO] = FB(216902), [STR_NTS_ATTEMPT] = FB(216915),
    [STR_NTS_REQUIRE] = FB(216928), [STR_WAITING_NTP] = FB(216947),
    [STR_FMT_SYNCED] = FB(216990), [STR_FMT_SYNCING] = FB(217017),
    [STR_FMT_WAITING] = FB(217050), [STR_WIFI_SETUP] = FB(217082), [STR_SCANNING] = FB(217116),
    [STR_SCAN_FAILED] = FB(217144), [STR_TAP_RETRY] = FB(217175),
    [STR_SELECT_NETWORK] = FB(217218), [STR_NO_NETWORKS] = FB(217258),
    [STR_NETWORK_LABEL] = FB(217298), [STR_ENTER_PASSWORD] = FB(217326),
    [STR_CONNECTING] = FB(217372), [STR_CONNECTING_TO] = FB(217394),
    [STR_CONNECTED] = FB(217419), [STR_CONNECTION_FAILED] = FB(217441),
    [STR_KB_SPACE] = FB(217475), [STR_KB_GO] = FB(217494), [STR_VERSION] = FB(217497),
    [STR_STATUS] = FB(217513), [STR_READ] = FB(217526), [STR_UPDATE] = FB(217545),
    [STR_RESTARTING] = FB(217558), [STR_OTA_UPDATE] = FB(217586), [STR_NTP_SERVER] = FB(217617),
    [STR_SERVER_LABEL] = FB(217651), [STR_NTP_SETTINGS] = FB(217676),
    [STR_NTP_PRESETS] = FB(217710), [STR_PRESETS] = FB(217741), [STR_BENCHMARK] = FB(217760),
    [STR_STOPPING] = FB(217779), [STR_NTP_STATS] = FB(217801), [STR_UNSYNCED] = FB(217835),
    [STR_NONE] = FB(217848), [STR_SELECT_REGION] = FB(217867), [STR_AGE_LABEL] = FB(217892),
    [STR_SYNCS_LABEL] = FB(217914), [STR_FMT_PEERS_NOSYNC] = FB(217936),
    [STR_FMT_PEERS_AGO] = FB(218010), [STR_DST] = FB(218067), [STR_NO_DST] = FB(218098),
};
const char *const weekdays_ta_shaped[7] = {
    FB(218144), FB(218157), FB(218167), FB(218180), FB(218190), FB(218203), FB(218216),
};
const char *const months_ta_shaped[12] = {
    FB(218223), FB(218233), FB(218243), FB(218256), FB(218266), FB(218273), FB(218280),
    FB(218290), FB(218300), FB(218313), FB(218323), FB(218333),
};
const char lang_name_ta_shaped[] = ("\xEE" "\x81" "\x9C" "\xEE" "\x80" "\x9B" "\xEE" "\x82" "\x9D");

// te: 217 shaped cluster glyphs (Kohinoor Telugu)
// shaped-source-hash te e2a06a76c473ea8b
const display_glyph_font_t font_te = {
    .codepoints = FB16(218344),
    .glyphs_rle = fonts_blob + 218995,
    .glyphs_off = FB16(228298),
    .glyphs_2x_rle = fonts_blob + 228734,
    .glyphs_2x_off = FB16(234332),
    .widths = fonts_blob + 218778,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_te_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(234768), [STR_WIFI] = FB(234787), [STR_FAIL] = FB(234793),
    [STR_TIMEZONE] = FB(234806), [STR_BRIGHTNESS] = FB(234834), [STR_LED_BLINK] = FB(234850),
    [STR_ROTATE] = FB(234872), [STR_ABOUT] = FB(234894), [STR_LANGUAGE] = FB(234907),
    [STR_DONE] = FB(234914), [STR_BACK] = FB(234924), [STR_CANCEL] = FB(234937),
    [STR_DEL] = FB(234947), [STR_RUNNING] = FB(234963), [STR_ON] = FB(234982),
    [STR_OFF] = FB(234989), [STR_NTS_NO] = FB(234996), [STR_NTS_ATTEMPT] = FB(235003),
    [STR_NTS_REQUIRE] = FB(235022), [STR_WAITING_NTP] = FB(235041),
    [STR_FMT_SYNCED] = FB(235081), [STR_FMT_SYNCING] = FB(235099),
    [STR_FMT_WAITING] = FB(235135), [STR_WIFI_SETUP] = FB(235152), [STR_SCANNING] = FB(235180),
    [STR_SCAN_FAILED] = FB(235208), [STR_TAP_RETRY] = FB(235233),
    [STR_SELECT_NETWORK] = FB(235285), [STR_NO_NETWORKS] = FB(235319),
    [STR_NETWORK_LABEL] = FB(235341), [STR_ENTER_PASSWORD] = FB(235357),
    [STR_CONNECTING] = FB(235382), [STR_CONNECTING_TO] = FB(235413),
    [STR_CONNECTED] = FB(235447), [STR_CONNECTION_FAILED] = FB(235478),
    [STR_KB_SPACE] = FB(235509), [STR_KB_GO] = FB(235516), [STR_VERSION] = FB(235519),
    [STR_STATUS] = FB(235535), [STR_READ] = FB(235548), [STR_UPDATE] = FB(235567),
    [STR_RESTARTING] = FB(235583), [STR_OTA_UPDATE] = FB(235611), [STR_NTP_SERVER] = FB(235639),
    [STR_SERVER_LABEL] = FB(235664), [STR_NTP_SETTINGS] = FB(235680),
    [STR_NTP_PRESETS] = FB(235711), [STR_PRESETS] = FB(235739), [STR_BENCHMARK] = FB(235755),
    [STR_STOPPING] = FB(235768), [STR_NTP_STATS] = FB(235784), [STR_UNSYNCED] = FB(235812),
    [STR_NONE] = FB(235831), [STR_SELECT_REGION] = FB(235847), [STR_AGE_LABEL] = FB(235884),
    [STR_SYNCS_LABEL] = FB(235906), [STR_FMT_PEERS_NOSYNC] = FB(235928),
    [STR_FMT_PEERS_AGO] = FB(235996), [STR_DST] = FB(236059), [STR_NO_DST] = FB(236084),
};
const char *const weekdays_te_shaped[7] = {
    FB(236118), FB(236125), FB(236132), FB(236145), FB(236152), FB(236159), FB(236169),
};
const char *const months_te_shaped[12] = {
    FB(236176), FB(236183), FB(236193), FB(236203), FB(236213), FB(236217), FB(236224),
    FB(236231), FB(236238), FB(236251), FB(236261), FB(236271),
};
const char lang_name_te_shaped[] = ("\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98" "\xEE" "\x80" "\x9F");

// pa: 166 shaped cluster glyphs (Gurmukhi Sangam MN)
// shaped-source-hash pa 2d3a9b02f345682a
const display_glyph_font_t font_pa = {
    .codepoints = FB16(236282),
    .glyphs_rle = fonts_blob + 236780,
    .glyphs_off = FB16(245222),
    .glyphs_2x_rle = fonts_blob + 245556,
    .glyphs_2x_off = FB16(249994),
    .widths = fonts_blob + 236614,
    .count = 166,
    .glyph_width = 16,
};
const char *const lang_pa_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(250328), [STR_WIFI] = FB(250338), [STR_FAIL] = FB(250344),
    [STR_TIMEZONE] = FB(250357), [STR_BRIGHTNESS] = FB(250376), [STR_LED_BLINK] = FB(250386),
    [STR_ROTATE] = FB(250408), [STR_ABOUT] = FB(250430), [STR_LANGUAGE] = FB(250440),
    [STR_DONE] = FB(250453), [STR_BACK] = FB(250466), [STR_CANCEL] = FB(250473),
    [STR_DEL] = FB(250477), [STR_RUNNING] = FB(250493), [STR_ON] = FB(250512),
    [STR_OFF] = FB(250522), [STR_NTS_NO] = FB(250526), [STR_NTS_ATTEMPT] = FB(250536),
    [STR_NTS_REQUIRE] = FB(250546), [STR_WAITING_NTP] = FB(250562),
    [STR_FMT_SYNCED] = FB(250593), [STR_FMT_SYNCING] = FB(250608),
    [STR_FMT_WAITING] = FB(250641), [STR_WIFI_SETUP] = FB(250664), [STR_SCANNING] = FB(250689),
    [STR_SCAN_FAILED] = FB(250717), [STR_TAP_RETRY] = FB(250736),
    [STR_SELECT_NETWORK] = FB(250785), [STR_NO_NETWORKS] = FB(250807),
    [STR_NETWORK_LABEL] = FB(250844), [STR_ENTER_PASSWORD] = FB(250863),
    [STR_CONNECTING] = FB(250891), [STR_CONNECTING_TO] = FB(250910),
    [STR_CONNECTED] = FB(250932), [STR_CONNECTION_FAILED] = FB(250951),
    [STR_KB_SPACE] = FB(250979), [STR_KB_GO] = FB(250986), [STR_VERSION] = FB(250989),
    [STR_STATUS] = FB(251005), [STR_READ] = FB(251024), [STR_UPDATE] = FB(251040),
    [STR_RESTARTING] = FB(251047), [STR_OTA_UPDATE] = FB(251057), [STR_NTP_SERVER] = FB(251076),
    [STR_SERVER_LABEL] = FB(251101), [STR_NTP_SETTINGS] = FB(251117),
    [STR_NTP_PRESETS] = FB(251136), [STR_PRESETS] = FB(251158), [STR_BENCHMARK] = FB(251171),
    [STR_STOPPING] = FB(251181), [STR_NTP_STATS] = FB(251200), [STR_UNSYNCED] = FB(251219),
    [STR_NONE] = FB(251238), [STR_SELECT_REGION] = FB(251254), [STR_AGE_LABEL] = FB(251267),
    [STR_SYNCS_LABEL] = FB(251289), [STR_FMT_PEERS_NOSYNC] = FB(251308),
    [STR_FMT_PEERS_AGO] = FB(251376), [STR_DST] = FB(251442), [STR_NO_DST] = FB(251467),
};
const char *const weekdays_pa_shaped[7] = {
    FB(251504), FB(251511), FB(251515), FB(251522), FB(251526), FB(251536), FB(251543),
};
const char *const months_pa_shaped[12] = {
    FB(251553), FB(251560), FB(251567), FB(251580), FB(251587), FB(251594), FB(251598),
    FB(251605), FB(251612), FB(251619), FB(251629), FB(251636),
};
const char lang_name_pa_shaped[] = ("\xEE" "\x82" "\xA3" "\xEE" "\x80" "\x94" "\xEE" "\x82" "\xA4" "\xEE" "\x82" "\xA5");

// gu: 186 shaped cluster glyphs (Kohinoor Gujarati)
// shaped-source-hash gu fbd4bb74daaf15bf
const display_glyph_font_t font_gu = {
    .codepoints = FB16(251644),
    .glyphs_rle = fonts_blob + 252202,
    .glyphs_off = FB16(260548),
    .glyphs_2x_rle = fonts_blob + 260922,
    .glyphs_2x_off = FB16(265906),
    .widths = fonts_blob + 252016,
    .count = 186,
    .glyph_width = 16,
};
const char *const lang_gu_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(266280), [STR_WIFI] = FB(266296), [STR_FAIL] = FB(266302),
    [STR_TIMEZONE] = FB(266315), [STR_BRIGHTNESS] = FB(266334), [STR_LED_BLINK] = FB(266338),
    [STR_ROTATE] = FB(266369), [STR_ABOUT] = FB(266394), [STR_LANGUAGE] = FB(266404),
    [STR_DONE] = FB(266417), [STR_BACK] = FB(266433), [STR_CANCEL] = FB(266446),
    [STR_DEL] = FB(266453), [STR_RUNNING] = FB(266466), [STR_ON] = FB(266488),
    [STR_OFF] = FB(266498), [STR_NTS_NO] = FB(266505), [STR_NTS_ATTEMPT] = FB(266512),
    [STR_NTS_REQUIRE] = FB(266525), [STR_WAITING_NTP] = FB(266547),
    [STR_FMT_SYNCED] = FB(266587), [STR_FMT_SYNCING] = FB(266608),
    [STR_FMT_WAITING] = FB(266644), [STR_WIFI_SETUP] = FB(266664), [STR_SCANNING] = FB(266692),
    [STR_SCAN_FAILED] = FB(266717), [STR_TAP_RETRY] = FB(266739),
    [STR_SELECT_NETWORK] = FB(266803), [STR_NO_NETWORKS] = FB(266837),
    [STR_NETWORK_LABEL] = FB(266871), [STR_ENTER_PASSWORD] = FB(266887),
    [STR_CONNECTING] = FB(266933), [STR_CONNECTING_TO] = FB(266952),
    [STR_CONNECTED] = FB(266971), [STR_CONNECTION_FAILED] = FB(266981),
    [STR_KB_SPACE] = FB(267006), [STR_KB_GO] = FB(267013), [STR_VERSION] = FB(267016),
    [STR_STATUS] = FB(267029), [STR_READ] = FB(267045), [STR_UPDATE] = FB(267055),
    [STR_RESTARTING] = FB(267071), [STR_OTA_UPDATE] = FB(267090), [STR_NTP_SERVER] = FB(267118),
    [STR_SERVER_LABEL] = FB(267137), [STR_NTP_SETTINGS] = FB(267147),
    [STR_NTP_PRESETS] = FB(267175), [STR_PRESETS] = FB(267203), [STR_BENCHMARK] = FB(267219),
    [STR_STOPPING] = FB(267235), [STR_NTP_STATS] = FB(267257), [STR_UNSYNCED] = FB(267282),
    [STR_NONE] = FB(267307), [STR_SELECT_REGION] = FB(267329), [STR_AGE_LABEL] = FB(267363),
    [STR_SYNCS_LABEL] = FB(267388), [STR_FMT_PEERS_NOSYNC] = FB(267413),
    [STR_FMT_PEERS_AGO] = FB(267481), [STR_DST] = FB(267541), [STR_NO_DST] = FB(267563),
};
const char *const weekdays_gu_shaped[7] = {
    FB(267597), FB(267607), FB(267614), FB(267621), FB(267628), FB(267632), FB(267636),
};
const char *const months_gu_shaped[12] = {
    FB(267646), FB(267653), FB(267663), FB(267673), FB(267683), FB(267687), FB(267697),
    FB(267713), FB(267723), FB(267733), FB(267743), FB(267750),
};
const char lang_name_gu_shaped[] = ("\xEE" "\x82" "\xB9" "\xEE" "\x80" "\x95" "\xEE" "\x80" "\x94" "\xEE" "\x80" "\xBE" "\xEE" "\x82" "\x95");

// kn: 217 shaped cluster glyphs (Kannada Sangam MN)
// shaped-source-hash kn 31b46ecce4f64786
const display_glyph_font_t font_kn = {
    .codepoints = FB16(267760),
    .glyphs_rle = fonts_blob + 268411,
    .glyphs_off = FB16(280176),
    .glyphs_2x_rle = fonts_blob + 280612,
    .glyphs_2x_off = FB16(287606),
    .widths = fonts_blob + 268194,
    .count = 217,
    .glyph_width = 16,
};
const char *const lang_kn_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(288042), [STR_WIFI] = FB(288064), [STR_FAIL] = FB(288070),
    [STR_TIMEZONE] = FB(288080), [STR_BRIGHTNESS] = FB(288102), [STR_LED_BLINK] = FB(288118),
    [STR_ROTATE] = FB(288146), [STR_ABOUT] = FB(288171), [STR_LANGUAGE] = FB(288187),
    [STR_DONE] = FB(288197), [STR_BACK] = FB(288210), [STR_CANCEL] = FB(288220),
    [STR_DEL] = FB(288230), [STR_RUNNING] = FB(288240), [STR_ON] = FB(288253),
    [STR_OFF] = FB(288260), [STR_NTS_NO] = FB(288267), [STR_NTS_ATTEMPT] = FB(288274),
    [STR_NTS_REQUIRE] = FB(288287), [STR_WAITING_NTP] = FB(288300),
    [STR_FMT_SYNCED] = FB(288346), [STR_FMT_SYNCING] = FB(288364),
    [STR_FMT_WAITING] = FB(288397), [STR_WIFI_SETUP] = FB(288423), [STR_SCANNING] = FB(288451),
    [STR_SCAN_FAILED] = FB(288482), [STR_TAP_RETRY] = FB(288516),
    [STR_SELECT_NETWORK] = FB(288550), [STR_NO_NETWORKS] = FB(288575),
    [STR_NETWORK_LABEL] = FB(288600), [STR_ENTER_PASSWORD] = FB(288619),
    [STR_CONNECTING] = FB(288656), [STR_CONNECTING_TO] = FB(288681),
    [STR_CONNECTED] = FB(288706), [STR_CONNECTION_FAILED] = FB(288734),
    [STR_KB_SPACE] = FB(288762), [STR_KB_GO] = FB(288772), [STR_VERSION] = FB(288775),
    [STR_STATUS] = FB(288788), [STR_READ] = FB(288795), [STR_UPDATE] = FB(288808),
    [STR_RESTARTING] = FB(288824), [STR_OTA_UPDATE] = FB(288852), [STR_NTP_SERVER] = FB(288880),
    [STR_SERVER_LABEL] = FB(288905), [STR_NTP_SETTINGS] = FB(288921),
    [STR_NTP_PRESETS] = FB(288955), [STR_PRESETS] = FB(288980), [STR_BENCHMARK] = FB(288993),
    [STR_STOPPING] = FB(289003), [STR_NTP_STATS] = FB(289016), [STR_UNSYNCED] = FB(289047),
    [STR_NONE] = FB(289066), [STR_SELECT_REGION] = FB(289085), [STR_AGE_LABEL] = FB(289107),
    [STR_SYNCS_LABEL] = FB(289135), [STR_FMT_PEERS_NOSYNC] = FB(289154),
    [STR_FMT_PEERS_AGO] = FB(289219), [STR_DST] = FB(289279), [STR_NO_DST] = FB(289298),
};
const char *const weekdays_kn_shaped[7] = {
    FB(289326), FB(289339), FB(289349), FB(289362), FB(289372), FB(289385), FB(289398),
};
const char *const months_kn_shaped[12] = {
    FB(289405), FB(289412), FB(289422), FB(289435), FB(289442), FB(289449), FB(289459),
    FB(289469), FB(289476), FB(289486), FB(289499), FB(289509),
};
const char lang_name_kn_shaped[] = ("\xEE" "\x80" "\xA1" "\xEE" "\x83" "\x97" "\xEE" "\x83" "\x98");

// ml: 190 shaped cluster glyphs (Malayalam Sangam MN)
// shaped-source-hash ml 84ed9b8b37b36c9e
const display_glyph_font_t font_ml = {
    .codepoints = FB16(289516),
    .glyphs_rle = fonts_blob + 290086,
    .glyphs_off = FB16(299088),
    .glyphs_2x_rle = fonts_blob + 299470,
    .glyphs_2x_off = FB16(306858),
    .widths = fonts_blob + 289896,
    .count = 190,
    .glyph_width = 16,
};
const char *const lang_ml_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(307240), [STR_WIFI] = FB(307268), [STR_FAIL] = FB(307274),
    [STR_TIMEZONE] = FB(307293), [STR_BRIGHTNESS] = FB(307318), [STR_LED_BLINK] = FB(307337),
    [STR_ROTATE] = FB(307362), [STR_ABOUT] = FB(307396), [STR_LANGUAGE] = FB(307412),
    [STR_DONE] = FB(307422), [STR_BACK] = FB(307441), [STR_CANCEL] = FB(307460),
    [STR_DEL] = FB(307467), [STR_RUNNING] = FB(307483), [STR_ON] = FB(307517),
    [STR_OFF] = FB(307524), [STR_NTS_NO] = FB(307531), [STR_NTS_ATTEMPT] = FB(307538),
    [STR_NTS_REQUIRE] = FB(307551), [STR_WAITING_NTP] = FB(307573),
    [STR_FMT_SYNCED] = FB(307616), [STR_FMT_SYNCING] = FB(307631),
    [STR_FMT_WAITING] = FB(307667), [STR_WIFI_SETUP] = FB(307699), [STR_SCANNING] = FB(307742),
    [STR_SCAN_FAILED] = FB(307773), [STR_TAP_RETRY] = FB(307813),
    [STR_SELECT_NETWORK] = FB(307874), [STR_NO_NETWORKS] = FB(307911),
    [STR_NETWORK_LABEL] = FB(307936), [STR_ENTER_PASSWORD] = FB(307955),
    [STR_CONNECTING] = FB(307989), [STR_CONNECTING_TO] = FB(308017),
    [STR_CONNECTED] = FB(308048), [STR_CONNECTION_FAILED] = FB(308073),
    [STR_KB_SPACE] = FB(308107), [STR_KB_GO] = FB(308120), [STR_VERSION] = FB(308123),
    [STR_STATUS] = FB(308136), [STR_READ] = FB(308149), [STR_UPDATE] = FB(308171),
    [STR_RESTARTING] = FB(308184), [STR_OTA_UPDATE] = FB(308212), [STR_NTP_SERVER] = FB(308237),
    [STR_SERVER_LABEL] = FB(308265), [STR_NTP_SETTINGS] = FB(308284),
    [STR_NTP_PRESETS] = FB(308321), [STR_PRESETS] = FB(308355), [STR_BENCHMARK] = FB(308377),
    [STR_STOPPING] = FB(308393), [STR_NTP_STATS] = FB(308415), [STR_UNSYNCED] = FB(308458),
    [STR_NONE] = FB(308474), [STR_SELECT_REGION] = FB(308493), [STR_AGE_LABEL] = FB(308533),
    [STR_SYNCS_LABEL] = FB(308561), [STR_FMT_PEERS_NOSYNC] = FB(308580),
    [STR_FMT_PEERS_AGO] = FB(308648), [STR_DST] = FB(308711), [STR_NO_DST] = FB(308739),
};
const char *const weekdays_ml_shaped[7] = {
    FB(308776), FB(308789), FB(308802), FB(308815), FB(308828), FB(308844), FB(308857),
};
const char *const months_ml_shaped[12] = {
    FB(308867), FB(308877), FB(308893), FB(308903), FB(308916), FB(308926), FB(308936),
    FB(308949), FB(308956), FB(308969), FB(308982), FB(308992),
};
const char lang_name_ml_shaped[] = ("\xEE" "\x80" "\x82" "\xEE" "\x82" "\xBC" "\xEE" "\x80" "\x90" "\xEE" "\x80" "\x8B" "\xEE" "\x82" "\xBD" "\xEE" "\x81" "\x8B");

// ne: 198 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash ne d85c20cd0e9960a9
const display_glyph_font_t font_ne = {
    .codepoints = FB16(309006),
    .glyphs_rle = fonts_blob + 309600,
    .glyphs_off = FB16(318462),
    .glyphs_2x_rle = fonts_blob + 318860,
    .glyphs_2x_off = FB16(324626),
    .widths = fonts_blob + 309402,
    .count = 198,
    .glyph_width = 16,
};
const char *const lang_ne_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(325024), [STR_WIFI] = FB(325040), [STR_FAIL] = FB(325046),
    [STR_TIMEZONE] = FB(325059), [STR_BRIGHTNESS] = FB(325075), [STR_LED_BLINK] = FB(325085),
    [STR_ROTATE] = FB(325116), [STR_ABOUT] = FB(325138), [STR_LANGUAGE] = FB(325154),
    [STR_DONE] = FB(325167), [STR_BACK] = FB(325177), [STR_CANCEL] = FB(325193),
    [STR_DEL] = FB(325200), [STR_RUNNING] = FB(325210), [STR_ON] = FB(325232),
    [STR_OFF] = FB(325239), [STR_NTS_NO] = FB(325246), [STR_NTS_ATTEMPT] = FB(325259),
    [STR_NTS_REQUIRE] = FB(325272), [STR_WAITING_NTP] = FB(325291),
    [STR_FMT_SYNCED] = FB(325319), [STR_FMT_SYNCING] = FB(325340),
    [STR_FMT_WAITING] = FB(325373), [STR_WIFI_SETUP] = FB(325393), [STR_SCANNING] = FB(325421),
    [STR_SCAN_FAILED] = FB(325440), [STR_TAP_RETRY] = FB(325468),
    [STR_SELECT_NETWORK] = FB(325529), [STR_NO_NETWORKS] = FB(325560),
    [STR_NETWORK_LABEL] = FB(325585), [STR_ENTER_PASSWORD] = FB(325601),
    [STR_CONNECTING] = FB(325635), [STR_CONNECTING_TO] = FB(325660),
    [STR_CONNECTED] = FB(325688), [STR_CONNECTION_FAILED] = FB(325716),
    [STR_KB_SPACE] = FB(325744), [STR_KB_GO] = FB(325751), [STR_VERSION] = FB(325754),
    [STR_STATUS] = FB(325770), [STR_READ] = FB(325786), [STR_UPDATE] = FB(325805),
    [STR_RESTARTING] = FB(325815), [STR_OTA_UPDATE] = FB(325828), [STR_NTP_SERVER] = FB(325850),
    [STR_SERVER_LABEL] = FB(325869), [STR_NTP_SETTINGS] = FB(325879),
    [STR_NTP_PRESETS] = FB(325901), [STR_PRESETS] = FB(325932), [STR_BENCHMARK] = FB(325951),
    [STR_STOPPING] = FB(325967), [STR_NTP_STATS] = FB(325986), [STR_UNSYNCED] = FB(326017),
    [STR_NONE] = FB(326042), [STR_SELECT_REGION] = FB(326067), [STR_AGE_LABEL] = FB(326089),
    [STR_SYNCS_LABEL] = FB(326108), [STR_FMT_PEERS_NOSYNC] = FB(326133),
    [STR_FMT_PEERS_AGO] = FB(326201), [STR_DST] = FB(326255), [STR_NO_DST] = FB(326277),
};
const char *const weekdays_ne_shaped[7] = {
    FB(326311), FB(326321), FB(326331), FB(326347), FB(326351), FB(326364), FB(326371),
};
const char *const months_ne_shaped[12] = {
    FB(326381), FB(326397), FB(326413), FB(326423), FB(326436), FB(326440), FB(326444),
    FB(326457), FB(326467), FB(326477), FB(326493), FB(326509),
};
const char lang_name_ne_shaped[] = ("\xEE" "\x83" "\x85" "\xEE" "\x80" "\x9C" "\xEE" "\x80" "\x88" "\xEE" "\x81" "\x9B");

// si: 162 shaped cluster glyphs (Sinhala Sangam MN)
// shaped-source-hash si a30676e11139b215
const display_glyph_font_t font_si = {
    .codepoints = FB16(326526),
    .glyphs_rle = fonts_blob + 327012,
    .glyphs_off = FB16(334826),
    .glyphs_2x_rle = fonts_blob + 335152,
    .glyphs_2x_off = FB16(342304),
    .widths = fonts_blob + 326850,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_si_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(342630), [STR_WIFI] = FB(342643), [STR_FAIL] = FB(342649),
    [STR_TIMEZONE] = FB(342671), [STR_BRIGHTNESS] = FB(342702), [STR_LED_BLINK] = FB(342715),
    [STR_ROTATE] = FB(342740), [STR_ABOUT] = FB(342771), [STR_LANGUAGE] = FB(342784),
    [STR_DONE] = FB(342800), [STR_BACK] = FB(342813), [STR_CANCEL] = FB(342823),
    [STR_DEL] = FB(342839), [STR_RUNNING] = FB(342852), [STR_ON] = FB(342877),
    [STR_OFF] = FB(342887), [STR_NTS_NO] = FB(342897), [STR_NTS_ATTEMPT] = FB(342907),
    [STR_NTS_REQUIRE] = FB(342926), [STR_WAITING_NTP] = FB(342945),
    [STR_FMT_SYNCED] = FB(343009), [STR_FMT_SYNCING] = FB(343033),
    [STR_FMT_WAITING] = FB(343072), [STR_WIFI_SETUP] = FB(343092), [STR_SCANNING] = FB(343123),
    [STR_SCAN_FAILED] = FB(343151), [STR_TAP_RETRY] = FB(343188),
    [STR_SELECT_NETWORK] = FB(343249), [STR_NO_NETWORKS] = FB(343283),
    [STR_NETWORK_LABEL] = FB(343314), [STR_ENTER_PASSWORD] = FB(343330),
    [STR_CONNECTING] = FB(343370), [STR_CONNECTING_TO] = FB(343401),
    [STR_CONNECTED] = FB(343435), [STR_CONNECTION_FAILED] = FB(343457),
    [STR_KB_SPACE] = FB(343506), [STR_KB_GO] = FB(343513), [STR_VERSION] = FB(343516),
    [STR_STATUS] = FB(343535), [STR_READ] = FB(343554), [STR_UPDATE] = FB(343564),
    [STR_RESTARTING] = FB(343577), [STR_OTA_UPDATE] = FB(343608), [STR_NTP_SERVER] = FB(343645),
    [STR_SERVER_LABEL] = FB(343685), [STR_NTP_SETTINGS] = FB(343716),
    [STR_NTP_PRESETS] = FB(343741), [STR_PRESETS] = FB(343769), [STR_BENCHMARK] = FB(343785),
    [STR_STOPPING] = FB(343804), [STR_NTP_STATS] = FB(343820), [STR_UNSYNCED] = FB(343860),
    [STR_NONE] = FB(343888), [STR_SELECT_REGION] = FB(343913), [STR_AGE_LABEL] = FB(343950),
    [STR_SYNCS_LABEL] = FB(343972), [STR_FMT_PEERS_NOSYNC] = FB(343994),
    [STR_FMT_PEERS_AGO] = FB(344065), [STR_DST] = FB(344125), [STR_NO_DST] = FB(344159),
};
const char *const weekdays_si_shaped[7] = {
    FB(344205), FB(344218), FB(344231), FB(344241), FB(344257), FB(344267), FB(344274),
};
const char *const months_si_shaped[12] = {
    FB(344284), FB(344294), FB(344304), FB(344317), FB(344324), FB(344337), FB(344359),
    FB(344369), FB(344379), FB(344389), FB(344396), FB(344403),
};
const char lang_name_si_shaped[] = ("\xEE" "\x82" "\x8A" "\xEE" "\x80" "\xAF" "\xEE" "\x80" "\xBA" "\xEE" "\x80" "\x8F");

// km: 193 shaped cluster glyphs (Khmer Sangam MN)
// shaped-source-hash km 001d4323092b620d
const display_glyph_font_t font_km = {
    .codepoints = FB16(344416),
    .glyphs_rle = fonts_blob + 344995,
    .glyphs_off = FB16(354436),
    .glyphs_2x_rle = fonts_blob + 354824,
    .glyphs_2x_off = FB16(359746),
    .widths = fonts_blob + 344802,
    .count = 193,
    .glyph_width = 16,
};
const char *const lang_km_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(360134), [STR_WIFI] = FB(360150), [STR_FAIL] = FB(360156),
    [STR_TIMEZONE] = FB(360166), [STR_BRIGHTNESS] = FB(360179), [STR_LED_BLINK] = FB(360186),
    [STR_ROTATE] = FB(360208), [STR_ABOUT] = FB(360227), [STR_LANGUAGE] = FB(360231),
    [STR_DONE] = FB(360238), [STR_BACK] = FB(360248), [STR_CANCEL] = FB(360267),
    [STR_DEL] = FB(360283), [STR_RUNNING] = FB(360287), [STR_ON] = FB(360306),
    [STR_OFF] = FB(360313), [STR_NTS_NO] = FB(360317), [STR_NTS_ATTEMPT] = FB(360324),
    [STR_NTS_REQUIRE] = FB(360337), [STR_WAITING_NTP] = FB(360347),
    [STR_FMT_SYNCED] = FB(360375), [STR_FMT_SYNCING] = FB(360396),
    [STR_FMT_WAITING] = FB(360423), [STR_WIFI_SETUP] = FB(360440), [STR_SCANNING] = FB(360471),
    [STR_SCAN_FAILED] = FB(360499), [STR_TAP_RETRY] = FB(360521),
    [STR_SELECT_NETWORK] = FB(360558), [STR_NO_NETWORKS] = FB(360583),
    [STR_NETWORK_LABEL] = FB(360596), [STR_ENTER_PASSWORD] = FB(360609),
    [STR_CONNECTING] = FB(360634), [STR_CONNECTING_TO] = FB(360644),
    [STR_CONNECTED] = FB(360657), [STR_CONNECTION_FAILED] = FB(360667),
    [STR_KB_SPACE] = FB(360686), [STR_KB_GO] = FB(360696), [STR_VERSION] = FB(360699),
    [STR_STATUS] = FB(360709), [STR_READ] = FB(360725), [STR_UPDATE] = FB(360741),
    [STR_RESTARTING] = FB(360757), [STR_OTA_UPDATE] = FB(360776), [STR_NTP_SERVER] = FB(360804),
    [STR_SERVER_LABEL] = FB(360829), [STR_NTP_SETTINGS] = FB(360845),
    [STR_NTP_PRESETS] = FB(360870), [STR_PRESETS] = FB(360892), [STR_BENCHMARK] = FB(360905),
    [STR_STOPPING] = FB(360921), [STR_NTP_STATS] = FB(360934), [STR_UNSYNCED] = FB(360950),
    [STR_NONE] = FB(360966), [STR_SELECT_REGION] = FB(360970), [STR_AGE_LABEL] = FB(360992),
    [STR_SYNCS_LABEL] = FB(361008), [STR_FMT_PEERS_NOSYNC] = FB(361024),
    [STR_FMT_PEERS_AGO] = FB(361071), [STR_DST] = FB(361116), [STR_NO_DST] = FB(361135),
};
const char *const weekdays_km_shaped[7] = {
    FB(361157), FB(361167), FB(361174), FB(361181), FB(361185), FB(361195), FB(361202),
};
const char *const months_km_shaped[12] = {
    FB(361212), FB(361222), FB(361226), FB(361230), FB(361240), FB(361250), FB(361257),
    FB(361264), FB(361271), FB(361278), FB(361285), FB(361292),
};
const char lang_name_km_shaped[] = ("\xEE" "\x80" "\x88" "\xEE" "\x83" "\x80");

// lo: 169 shaped cluster glyphs (Lao Sangam MN)
// shaped-source-hash lo 3d0778a6b7811038
const display_glyph_font_t font_lo = {
    .codepoints = FB16(361296),
    .glyphs_rle = fonts_blob + 361803,
    .glyphs_off = FB16(370660),
    .glyphs_2x_rle = fonts_blob + 371000,
    .glyphs_2x_off = FB16(375664),
    .widths = fonts_blob + 361634,
    .count = 169,
    .glyph_width = 16,
};
const char *const lang_lo_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(376004), [STR_WIFI] = FB(376020), [STR_FAIL] = FB(376026),
    [STR_TIMEZONE] = FB(376039), [STR_BRIGHTNESS] = FB(376061), [STR_LED_BLINK] = FB(376080),
    [STR_ROTATE] = FB(376102), [STR_ABOUT] = FB(376121), [STR_LANGUAGE] = FB(376131),
    [STR_DONE] = FB(376144), [STR_BACK] = FB(376151), [STR_CANCEL] = FB(376158),
    [STR_DEL] = FB(376168), [STR_RUNNING] = FB(376172), [STR_ON] = FB(376194),
    [STR_OFF] = FB(376201), [STR_NTS_NO] = FB(376205), [STR_NTS_ATTEMPT] = FB(376209),
    [STR_NTS_REQUIRE] = FB(376219), [STR_WAITING_NTP] = FB(376226),
    [STR_FMT_SYNCED] = FB(376254), [STR_FMT_SYNCING] = FB(376272),
    [STR_FMT_WAITING] = FB(376290), [STR_WIFI_SETUP] = FB(376307), [STR_SCANNING] = FB(376332),
    [STR_SCAN_FAILED] = FB(376357), [STR_TAP_RETRY] = FB(376385),
    [STR_SELECT_NETWORK] = FB(376416), [STR_NO_NETWORKS] = FB(376438),
    [STR_NETWORK_LABEL] = FB(376457), [STR_ENTER_PASSWORD] = FB(376473),
    [STR_CONNECTING] = FB(376492), [STR_CONNECTING_TO] = FB(376511),
    [STR_CONNECTED] = FB(376527), [STR_CONNECTION_FAILED] = FB(376546),
    [STR_KB_SPACE] = FB(376571), [STR_KB_GO] = FB(376578), [STR_VERSION] = FB(376581),
    [STR_STATUS] = FB(376594), [STR_READ] = FB(376616), [STR_UPDATE] = FB(376626),
    [STR_RESTARTING] = FB(376639), [STR_OTA_UPDATE] = FB(376658), [STR_NTP_SERVER] = FB(376683),
    [STR_SERVER_LABEL] = FB(376705), [STR_NTP_SETTINGS] = FB(376718),
    [STR_NTP_PRESETS] = FB(376737), [STR_PRESETS] = FB(376771), [STR_BENCHMARK] = FB(376793),
    [STR_STOPPING] = FB(376806), [STR_NTP_STATS] = FB(376816), [STR_UNSYNCED] = FB(376838),
    [STR_NONE] = FB(376845), [STR_SELECT_REGION] = FB(376849), [STR_AGE_LABEL] = FB(376868),
    [STR_SYNCS_LABEL] = FB(376887), [STR_FMT_PEERS_NOSYNC] = FB(376903),
    [STR_FMT_PEERS_AGO] = FB(376956), [STR_DST] = FB(377010), [STR_NO_DST] = FB(377038),
};
const char *const weekdays_lo_shaped[7] = {
    FB(377069), FB(377079), FB(377083), FB(377096), FB(377100), FB(377110), FB(377114),
};
const char *const months_lo_shaped[12] = {
    FB(377121), FB(377134), FB(377147), FB(377160), FB(377173), FB(377186), FB(377196),
    FB(377209), FB(377222), FB(377235), FB(377248), FB(377261),
};
const char lang_name_lo_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x80" "\x8E" "\xEE" "\x80" "\x8C");

// my: 188 shaped cluster glyphs (Myanmar Sangam MN)
// shaped-source-hash my 56bd2343a1a303fd
const display_glyph_font_t font_my = {
    .codepoints = FB16(377274),
    .glyphs_rle = fonts_blob + 377838,
    .glyphs_off = FB16(386778),
    .glyphs_2x_rle = fonts_blob + 387156,
    .glyphs_2x_off = FB16(392384),
    .widths = fonts_blob + 377650,
    .count = 188,
    .glyph_width = 16,
};
const char *const lang_my_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(392762), [STR_WIFI] = FB(392784), [STR_FAIL] = FB(392790),
    [STR_TIMEZONE] = FB(392812), [STR_BRIGHTNESS] = FB(392825), [STR_LED_BLINK] = FB(392844),
    [STR_ROTATE] = FB(392866), [STR_ABOUT] = FB(392882), [STR_LANGUAGE] = FB(392901),
    [STR_DONE] = FB(392914), [STR_BACK] = FB(392927), [STR_CANCEL] = FB(392943),
    [STR_DEL] = FB(392959), [STR_RUNNING] = FB(392969), [STR_ON] = FB(392988),
    [STR_OFF] = FB(392992), [STR_NTS_NO] = FB(392999), [STR_NTS_ATTEMPT] = FB(393009),
    [STR_NTS_REQUIRE] = FB(393028), [STR_WAITING_NTP] = FB(393038),
    [STR_FMT_SYNCED] = FB(393075), [STR_FMT_SYNCING] = FB(393090),
    [STR_FMT_WAITING] = FB(393114), [STR_WIFI_SETUP] = FB(393134), [STR_SCANNING] = FB(393165),
    [STR_SCAN_FAILED] = FB(393190), [STR_TAP_RETRY] = FB(393206),
    [STR_SELECT_NETWORK] = FB(393231), [STR_NO_NETWORKS] = FB(393253),
    [STR_NETWORK_LABEL] = FB(393269), [STR_ENTER_PASSWORD] = FB(393279),
    [STR_CONNECTING] = FB(393307), [STR_CONNECTING_TO] = FB(393326),
    [STR_CONNECTED] = FB(393348), [STR_CONNECTION_FAILED] = FB(393367),
    [STR_KB_SPACE] = FB(393404), [STR_KB_GO] = FB(393423), [STR_VERSION] = FB(393426),
    [STR_STATUS] = FB(393445), [STR_READ] = FB(393470), [STR_UPDATE] = FB(393483),
    [STR_RESTARTING] = FB(393493), [STR_OTA_UPDATE] = FB(393509), [STR_NTP_SERVER] = FB(393531),
    [STR_SERVER_LABEL] = FB(393556), [STR_NTP_SETTINGS] = FB(393572),
    [STR_NTP_PRESETS] = FB(393597), [STR_PRESETS] = FB(393619), [STR_BENCHMARK] = FB(393629),
    [STR_STOPPING] = FB(393642), [STR_NTP_STATS] = FB(393658), [STR_UNSYNCED] = FB(393683),
    [STR_NONE] = FB(393696), [STR_SELECT_REGION] = FB(393703), [STR_AGE_LABEL] = FB(393725),
    [STR_SYNCS_LABEL] = FB(393750), [STR_FMT_PEERS_NOSYNC] = FB(393766),
    [STR_FMT_PEERS_AGO] = FB(393834), [STR_DST] = FB(393897), [STR_NO_DST] = FB(393919),
};
const char *const weekdays_my_shaped[7] = {
    FB(393944), FB(393957), FB(393967), FB(393974), FB(393981), FB(394006), FB(394025),
};
const char *const months_my_shaped[12] = {
    FB(394035), FB(394042), FB(394049), FB(394056), FB(394060), FB(394067), FB(394071),
    FB(394075), FB(394079), FB(394086), FB(394099), FB(394103),
};
const char lang_name_my_shaped[] = ("\xEE" "\x80" "\xA6" "\xEE" "\x80" "\x8C" "\xEE" "\x82" "\xBB" "\xEE" "\x80" "\x8A");

// am: 176 shaped cluster glyphs (Kefa)
// shaped-source-hash am 1a59f6efe1a107eb
const display_glyph_font_t font_am = {
    .codepoints = FB16(394108),
    .glyphs_rle = fonts_blob + 394636,
    .glyphs_off = FB16(403496),
    .glyphs_2x_rle = fonts_blob + 403850,
    .glyphs_2x_off = FB16(411134),
    .widths = fonts_blob + 394460,
    .count = 176,
    .glyph_width = 16,
};
const char *const lang_am_shaped[STR_COUNT] = {
    [STR_SETTINGS] = FB(411488), [STR_WIFI] = FB(411504), [STR_FAIL] = FB(411510),
    [STR_TIMEZONE] = FB(411529), [STR_BRIGHTNESS] = FB(411551), [STR_LED_BLINK] = FB(411567),
    [STR_ROTATE] = FB(411592), [STR_ABOUT] = FB(411614), [STR_LANGUAGE] = FB(411621),
    [STR_DONE] = FB(411631), [STR_BACK] = FB(411647), [STR_CANCEL] = FB(411660),
    [STR_DEL] = FB(411670), [STR_RUNNING] = FB(411680), [STR_ON] = FB(411702),
    [STR_OFF] = FB(411715), [STR_NTS_NO] = FB(411728), [STR_NTS_ATTEMPT] = FB(411735),
    [STR_NTS_REQUIRE] = FB(411745), [STR_WAITING_NTP] = FB(411755),
    [STR_FMT_SYNCED] = FB(411792), [STR_FMT_SYNCING] = FB(411819),
    [STR_FMT_WAITING] = FB(411846), [STR_WIFI_SETUP] = FB(411869), [STR_SCANNING] = FB(411900),
    [STR_SCAN_FAILED] = FB(411925), [STR_TAP_RETRY] = FB(411956),
    [STR_SELECT_NETWORK] = FB(411999), [STR_NO_NETWORKS] = FB(412036),
    [STR_NETWORK_LABEL] = FB(412073), [STR_ENTER_PASSWORD] = FB(412089),
    [STR_CONNECTING] = FB(412126), [STR_CONNECTING_TO] = FB(412145),
    [STR_CONNECTED] = FB(412167), [STR_CONNECTION_FAILED] = FB(412189),
    [STR_KB_SPACE] = FB(412226), [STR_KB_GO] = FB(412239), [STR_VERSION] = FB(412242),
    [STR_STATUS] = FB(412255), [STR_READ] = FB(412268), [STR_UPDATE] = FB(412287),
    [STR_RESTARTING] = FB(412300), [STR_OTA_UPDATE] = FB(412334), [STR_NTP_SERVER] = FB(412359),
    [STR_SERVER_LABEL] = FB(412387), [STR_NTP_SETTINGS] = FB(412406),
    [STR_NTP_PRESETS] = FB(412434), [STR_PRESETS] = FB(412459), [STR_BENCHMARK] = FB(412472),
    [STR_STOPPING] = FB(412482), [STR_NTP_STATS] = FB(412495), [STR_UNSYNCED] = FB(412529),
    [STR_NONE] = FB(412551), [STR_SELECT_REGION] = FB(412561), [STR_AGE_LABEL] = FB(412583),
    [STR_SYNCS_LABEL] = FB(412605), [STR_FMT_PEERS_NOSYNC] = FB(412627),
    [STR_FMT_PEERS_AGO] = FB(412701), [STR_DST] = FB(412771), [STR_NO_DST] = FB(412793),
};
const char *const weekdays_am_shaped[7] = {
    FB(412827), FB(412837), FB(412844), FB(412854), FB(412864), FB(412874), FB(412884),
};
const char *const months_am_shaped[12] = {
    FB(412894), FB(412901), FB(412908), FB(412918), FB(412928), FB(412935), FB(412942),
    FB(412952), FB(412962), FB(412972), FB(412982), FB(412992),
};
const char lang_name_am_shaped[] = ("\xEE" "\x80" "\x85" "\xEE" "\x81" "\xBF" "\xEE" "\x80" "\xAE" "\xEE" "\x82" "\xAF");

// kok: 172 shaped cluster glyphs (Kohinoor Devanagari)
// shaped-source-hash kok 50a4435835e87a65
const display_glyph_font_t font_kok = {
    .codepoints = FB16(413002),
    .glyphs_rle = fonts_blob + 413518,
    .glyphs_off = FB16(421426),
    .glyphs_2x_rle = fonts_blob + 421772,
    .glyphs_2x_off = FB16(426446),
    .widths = fonts_blob + 413346,
    .count = 172,
    .glyph_width = 16,
};
const char *const lang_kok_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(426792), [STR_SETTINGS] = FB(426798), [STR_FAIL] = FB(426811),
    [STR_TIMEZONE] = FB(426818), [STR_BRIGHTNESS] = FB(426840), [STR_LED_BLINK] = FB(426856),
    [STR_ROTATE] = FB(426881), [STR_ABOUT] = FB(426906), [STR_LANGUAGE] = FB(426919),
    [STR_DONE] = FB(426929), [STR_BACK] = FB(426939), [STR_CANCEL] = FB(426952),
    [STR_DEL] = FB(426959), [STR_RUNNING] = FB(426969), [STR_ON] = FB(426988),
    [STR_OFF] = FB(426998), [STR_NTS_NO] = FB(427002), [STR_NTS_ATTEMPT] = FB(427009),
    [STR_NTS_REQUIRE] = FB(427016), [STR_WAITING_NTP] = FB(427026),
    [STR_FMT_SYNCED] = FB(427081), [STR_FMT_SYNCING] = FB(427111),
    [STR_FMT_WAITING] = FB(427147), [STR_FMT_PEERS_NOSYNC] = FB(427173),
    [STR_FMT_PEERS_AGO] = FB(427238), [STR_WIFI_SETUP] = FB(427292),
    [STR_SCANNING] = FB(427326), [STR_SCAN_FAILED] = FB(427351), [STR_TAP_RETRY] = FB(427370),
    [STR_SELECT_NETWORK] = FB(427425), [STR_NO_NETWORKS] = FB(427450),
    [STR_NETWORK_LABEL] = FB(427481), [STR_ENTER_PASSWORD] = FB(427497),
    [STR_CONNECTING] = FB(427528), [STR_CONNECTING_TO] = FB(427544),
    [STR_CONNECTED] = FB(427563), [STR_CONNECTION_FAILED] = FB(427576),
    [STR_KB_SPACE] = FB(427601), [STR_KB_GO] = FB(427614), [STR_VERSION] = FB(427617),
    [STR_STATUS] = FB(427630), [STR_READ] = FB(427646), [STR_UPDATE] = FB(427659),
    [STR_RESTARTING] = FB(427669), [STR_OTA_UPDATE] = FB(427700), [STR_NTP_SERVER] = FB(427722),
    [STR_SERVER_LABEL] = FB(427741), [STR_NTP_SETTINGS] = FB(427751),
    [STR_NTP_PRESETS] = FB(427776), [STR_PRESETS] = FB(427801), [STR_BENCHMARK] = FB(427814),
    [STR_STOPPING] = FB(427827), [STR_NTP_STATS] = FB(427840), [STR_UNSYNCED] = FB(427865),
    [STR_SYNCS_LABEL] = FB(427887), [STR_NONE] = FB(427912), [STR_SELECT_REGION] = FB(427919),
    [STR_AGE_LABEL] = FB(427941), [STR_DST] = FB(427969), [STR_NO_DST] = FB(427994),
};
const char *const weekdays_kok_shaped[7] = {
    FB(428028), FB(428038), FB(428048), FB(428055), FB(428059), FB(428069), FB(428076),
};
const char *const months_kok_shaped[12] = {
    FB(428080), FB(428090), FB(428100), FB(428110), FB(428120), FB(428124), FB(428128),
    FB(428135), FB(428142), FB(428149), FB(428159), FB(428169),
};
const char lang_name_kok_shaped[] = ("\xEE" "\x80" "\xAA" "\xEE" "\x82" "\xAB" "\xEE" "\x82" "\x84" "\xEE" "\x81" "\xAB" "\xEE" "\x80" "\xBD");

// as: 162 shaped cluster glyphs (Kohinoor Bangla)
// shaped-source-hash as 49869d97afa2e3e1
const display_glyph_font_t font_as = {
    .codepoints = FB16(428180),
    .glyphs_rle = fonts_blob + 428666,
    .glyphs_off = FB16(435262),
    .glyphs_2x_rle = fonts_blob + 435588,
    .glyphs_2x_off = FB16(440944),
    .widths = fonts_blob + 428504,
    .count = 162,
    .glyph_width = 16,
};
const char *const lang_as_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(441270), [STR_SETTINGS] = FB(441276), [STR_FAIL] = FB(441292),
    [STR_TIMEZONE] = FB(441305), [STR_BRIGHTNESS] = FB(441327), [STR_LED_BLINK] = FB(441343),
    [STR_ROTATE] = FB(441377), [STR_ABOUT] = FB(441408), [STR_LANGUAGE] = FB(441424),
    [STR_DONE] = FB(441437), [STR_BACK] = FB(441447), [STR_CANCEL] = FB(441460),
    [STR_DEL] = FB(441476), [STR_RUNNING] = FB(441486), [STR_ON] = FB(441508),
    [STR_OFF] = FB(441515), [STR_NTS_NO] = FB(441522), [STR_NTS_ATTEMPT] = FB(441532),
    [STR_NTS_REQUIRE] = FB(441545), [STR_WAITING_NTP] = FB(441561),
    [STR_FMT_SYNCED] = FB(441607), [STR_FMT_SYNCING] = FB(441640),
    [STR_FMT_WAITING] = FB(441682), [STR_FMT_PEERS_NOSYNC] = FB(441708),
    [STR_FMT_PEERS_AGO] = FB(441788), [STR_WIFI_SETUP] = FB(441854),
    [STR_SCANNING] = FB(441888), [STR_SCAN_FAILED] = FB(441928), [STR_TAP_RETRY] = FB(441953),
    [STR_SELECT_NETWORK] = FB(442011), [STR_NO_NETWORKS] = FB(442045),
    [STR_NETWORK_LABEL] = FB(442097), [STR_ENTER_PASSWORD] = FB(442119),
    [STR_CONNECTING] = FB(442153), [STR_CONNECTING_TO] = FB(442187),
    [STR_CONNECTED] = FB(442209), [STR_CONNECTION_FAILED] = FB(442228),
    [STR_KB_SPACE] = FB(442262), [STR_KB_GO] = FB(442275), [STR_VERSION] = FB(442278),
    [STR_STATUS] = FB(442297), [STR_READ] = FB(442313), [STR_UPDATE] = FB(442338),
    [STR_RESTARTING] = FB(442354), [STR_OTA_UPDATE] = FB(442373), [STR_NTP_SERVER] = FB(442401),
    [STR_SERVER_LABEL] = FB(442432), [STR_NTP_SETTINGS] = FB(442454),
    [STR_NTP_PRESETS] = FB(442482), [STR_PRESETS] = FB(442507), [STR_BENCHMARK] = FB(442520),
    [STR_STOPPING] = FB(442536), [STR_NTP_STATS] = FB(442555), [STR_UNSYNCED] = FB(442592),
    [STR_SYNCS_LABEL] = FB(442617), [STR_NONE] = FB(442642), [STR_SELECT_REGION] = FB(442652),
    [STR_AGE_LABEL] = FB(442677), [STR_DST] = FB(442699), [STR_NO_DST] = FB(442721),
};
const char *const weekdays_as_shaped[7] = {
    FB(442755), FB(442765), FB(442778), FB(442788), FB(442798), FB(442808), FB(442815),
};
const char *const months_as_shaped[12] = {
    FB(442825), FB(442835), FB(442848), FB(442861), FB(442874), FB(442884), FB(442891),
    FB(442904), FB(442911), FB(442924), FB(442937), FB(442947),
};
const char lang_name_as_shaped[] = ("\xEE" "\x80" "\x8D" "\xEE" "\x82" "\xA1" "\xEE" "\x80" "\x8A" "\xEE" "\x82" "\x88" "\xEE" "\x80" "\x8B" "\xEE" "\x80" "\xA8");

// ti: 177 shaped cluster glyphs (Kefa)
// shaped-source-hash ti 072e1eae69078ac8
const display_glyph_font_t font_ti = {
    .codepoints = FB16(442960),
    .glyphs_rle = fonts_blob + 443491,
    .glyphs_off = FB16(452402),
    .glyphs_2x_rle = fonts_blob + 452758,
    .glyphs_2x_off = FB16(457280),
    .widths = fonts_blob + 443314,
    .count = 177,
    .glyph_width = 16,
};
const char *const lang_ti_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(457636), [STR_SETTINGS] = FB(457642), [STR_FAIL] = FB(457658),
    [STR_TIMEZONE] = FB(457668), [STR_BRIGHTNESS] = FB(457687), [STR_LED_BLINK] = FB(457700),
    [STR_ROTATE] = FB(457725), [STR_ABOUT] = FB(457747), [STR_LANGUAGE] = FB(457760),
    [STR_DONE] = FB(457770), [STR_BACK] = FB(457783), [STR_CANCEL] = FB(457796),
    [STR_DEL] = FB(457806), [STR_RUNNING] = FB(457819), [STR_ON] = FB(457832),
    [STR_OFF] = FB(457842), [STR_NTS_NO] = FB(457852), [STR_NTS_ATTEMPT] = FB(457865),
    [STR_NTS_REQUIRE] = FB(457875), [STR_WAITING_NTP] = FB(457885),
    [STR_FMT_SYNCED] = FB(457916), [STR_FMT_SYNCING] = FB(457940),
    [STR_FMT_WAITING] = FB(457964), [STR_FMT_PEERS_NOSYNC] = FB(457984),
    [STR_FMT_PEERS_AGO] = FB(458055), [STR_WIFI_SETUP] = FB(458119),
    [STR_SCANNING] = FB(458150), [STR_SCAN_FAILED] = FB(458169), [STR_TAP_RETRY] = FB(458194),
    [STR_SELECT_NETWORK] = FB(458240), [STR_NO_NETWORKS] = FB(458265),
    [STR_NETWORK_LABEL] = FB(458302), [STR_ENTER_PASSWORD] = FB(458318),
    [STR_CONNECTING] = FB(458352), [STR_CONNECTING_TO] = FB(458365),
    [STR_CONNECTED] = FB(458387), [STR_CONNECTION_FAILED] = FB(458403),
    [STR_KB_SPACE] = FB(458425), [STR_KB_GO] = FB(458438), [STR_VERSION] = FB(458441),
    [STR_STATUS] = FB(458454), [STR_READ] = FB(458470), [STR_UPDATE] = FB(458486),
    [STR_RESTARTING] = FB(458499), [STR_OTA_UPDATE] = FB(458530), [STR_NTP_SERVER] = FB(458555),
    [STR_SERVER_LABEL] = FB(458580), [STR_NTP_SETTINGS] = FB(458596),
    [STR_NTP_PRESETS] = FB(458624), [STR_PRESETS] = FB(458655), [STR_BENCHMARK] = FB(458665),
    [STR_STOPPING] = FB(458675), [STR_NTP_STATS] = FB(458685), [STR_UNSYNCED] = FB(458716),
    [STR_SYNCS_LABEL] = FB(458738), [STR_NONE] = FB(458760), [STR_SELECT_REGION] = FB(458770),
    [STR_AGE_LABEL] = FB(458789), [STR_DST] = FB(458811), [STR_NO_DST] = FB(458842),
};
const char *const weekdays_ti_shaped[7] = {
    FB(458885), FB(458892), FB(458899), FB(458906), FB(458913), FB(458920), FB(458927),
};
const char *const months_ti_shaped[12] = {
    FB(458934), FB(458941), FB(458948), FB(458955), FB(458962), FB(458969), FB(458976),
    FB(458983), FB(458990), FB(458997), FB(459004), FB(459011),
};
const char lang_name_ti_shaped[] = ("\xEE" "\x82" "\xAF" "\xEE" "\x80" "\xBC" "\xEE" "\x80" "\x9D" "\xEE" "\x82" "\xB0");

// yo: 160 shaped cluster glyphs (Menlo)
// shaped-source-hash yo ae6afc109bb3d82d
const display_glyph_font_t font_yo = {
    .codepoints = FB16(459018),
    .glyphs_rle = fonts_blob + 459498,
    .glyphs_off = FB16(466330),
    .glyphs_2x_rle = fonts_blob + 466652,
    .glyphs_2x_off = FB16(472804),
    .widths = fonts_blob + 459338,
    .count = 160,
    .glyph_width = 16,
};
const char *const lang_yo_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(473126), [STR_SETTINGS] = FB(473132), [STR_FAIL] = FB(473142),
    [STR_TIMEZONE] = FB(473155), [STR_BRIGHTNESS] = FB(473195), [STR_LED_BLINK] = FB(473211),
    [STR_ROTATE] = FB(473245), [STR_ABOUT] = FB(473264), [STR_LANGUAGE] = FB(473277),
    [STR_DONE] = FB(473287), [STR_BACK] = FB(473300), [STR_CANCEL] = FB(473313),
    [STR_DEL] = FB(473332), [STR_RUNNING] = FB(473345), [STR_ON] = FB(473361),
    [STR_OFF] = FB(473371), [STR_NTS_NO] = FB(473374), [STR_NTS_ATTEMPT] = FB(473387),
    [STR_NTS_REQUIRE] = FB(473412), [STR_WAITING_NTP] = FB(473419),
    [STR_FMT_SYNCED] = FB(473468), [STR_FMT_SYNCING] = FB(473480),
    [STR_FMT_WAITING] = FB(473522), [STR_FMT_PEERS_NOSYNC] = FB(473551),
    [STR_FMT_PEERS_AGO] = FB(473631), [STR_WIFI_SETUP] = FB(473694),
    [STR_SCANNING] = FB(473725), [STR_SCAN_FAILED] = FB(473747), [STR_TAP_RETRY] = FB(473781),
    [STR_SELECT_NETWORK] = FB(473842), [STR_NO_NETWORKS] = FB(473879),
    [STR_NETWORK_LABEL] = FB(473922), [STR_ENTER_PASSWORD] = FB(473950),
    [STR_CONNECTING] = FB(473993), [STR_CONNECTING_TO] = FB(474018),
    [STR_CONNECTED] = FB(474049), [STR_CONNECTION_FAILED] = FB(474077),
    [STR_KB_SPACE] = FB(474111), [STR_KB_GO] = FB(474121), [STR_VERSION] = FB(474124),
    [STR_STATUS] = FB(474140), [STR_READ] = FB(474153), [STR_UPDATE] = FB(474172),
    [STR_RESTARTING] = FB(474191), [STR_OTA_UPDATE] = FB(474228), [STR_NTP_SERVER] = FB(474259),
    [STR_SERVER_LABEL] = FB(474284), [STR_NTP_SETTINGS] = FB(474300),
    [STR_NTP_PRESETS] = FB(474322), [STR_PRESETS] = FB(474353), [STR_BENCHMARK] = FB(474372),
    [STR_STOPPING] = FB(474391), [STR_NTP_STATS] = FB(474410), [STR_UNSYNCED] = FB(474438),
    [STR_SYNCS_LABEL] = FB(474469), [STR_NONE] = FB(474478), [STR_SELECT_REGION] = FB(474494),
    [STR_AGE_LABEL] = FB(474528), [STR_DST] = FB(474559), [STR_NO_DST] = FB(474563),
};
const char *const weekdays_yo_shaped[7] = {
    FB(474591), FB(474604), FB(474614), FB(474630), FB(474643), FB(474656), FB(474666),
};
const char *const months_yo_shaped[12] = {
    FB(474685), FB(474692), FB(474708), FB(474727), FB(474740), FB(474759), FB(474775),
    FB(474791), FB(474804), FB(474810), FB(474829), FB(474842),
};
const char lang_name_yo_shaped[] = ("\xEE" "\x80" "\xA0" "\xEE" "\x82" "\x9F" "\xEE" "\x80" "\xAC" "\xEE" "\x81" "\xA7" "\xEE" "\x81" "\xAB" "\xEE" "\x80" "\x9E");

// pcm: 73 shaped cluster glyphs (Menlo)
// shaped-source-hash pcm 4219c090bd10a9f9
const display_glyph_font_t font_pcm = {
    .codepoints = FB16(474858),
    .glyphs_rle = fonts_blob + 475077,
    .glyphs_off = FB16(478378),
    .glyphs_2x_rle = fonts_blob + 478526,
    .glyphs_2x_off = FB16(482056),
    .widths = fonts_blob + 475004,
    .count = 73,
    .glyph_width = 16,
};
const char *const lang_pcm_shaped[STR_COUNT] = {
    [STR_WIFI] = FB(482204), [STR_SETTINGS] = FB(482210), [STR_FAIL] = FB(482229),
    [STR_TIMEZONE] = FB(482233), [STR_BRIGHTNESS] = FB(482242), [STR_LED_BLINK] = FB(482267),
    [STR_ROTATE] = FB(482277), [STR_ABOUT] = FB(482286), [STR_LANGUAGE] = FB(482292),
    [STR_DONE] = FB(482300), [STR_BACK] = FB(482304), [STR_CANCEL] = FB(482308),
    [STR_DEL] = FB(482327), [STR_RUNNING] = FB(482332), [STR_ON] = FB(482339),
    [STR_OFF] = FB(482342), [STR_NTS_NO] = FB(482345), [STR_NTS_ATTEMPT] = FB(482348),
    [STR_NTS_REQUIRE] = FB(482353), [STR_WAITING_NTP] = FB(482358),
    [STR_FMT_SYNCED] = FB(482376), [STR_FMT_SYNCING] = FB(482389),
    [STR_FMT_WAITING] = FB(482401), [STR_FMT_PEERS_NOSYNC] = FB(482414),
    [STR_FMT_PEERS_AGO] = FB(482443), [STR_WIFI_SETUP] = FB(482475),
    [STR_SCANNING] = FB(482485), [STR_SCAN_FAILED] = FB(482496), [STR_TAP_RETRY] = FB(482509),
    [STR_SELECT_NETWORK] = FB(482531), [STR_NO_NETWORKS] = FB(482559),
    [STR_NETWORK_LABEL] = FB(482596), [STR_ENTER_PASSWORD] = FB(482615),
    [STR_CONNECTING] = FB(482646), [STR_CONNECTING_TO] = FB(482655),
    [STR_CONNECTED] = FB(482667), [STR_CONNECTION_FAILED] = FB(482678),
    [STR_KB_SPACE] = FB(482692), [STR_KB_GO] = FB(482697), [STR_VERSION] = FB(482700),
    [STR_STATUS] = FB(482719), [STR_READ] = FB(482730), [STR_UPDATE] = FB(482739),
    [STR_RESTARTING] = FB(482746), [STR_OTA_UPDATE] = FB(482760), [STR_NTP_SERVER] = FB(482771),
    [STR_SERVER_LABEL] = FB(482780), [STR_NTP_SETTINGS] = FB(482786),
    [STR_NTP_PRESETS] = FB(482817), [STR_PRESETS] = FB(482827), [STR_BENCHMARK] = FB(482833),
    [STR_STOPPING] = FB(482846), [STR_NTP_STATS] = FB(482854), [STR_UNSYNCED] = FB(482864),
    [STR_SYNCS_LABEL] = FB(482872), [STR_NONE] = FB(482881), [STR_SELECT_REGION] = FB(482897),
    [STR_AGE_LABEL] = FB(482925), [STR_DST] = FB(482932), [STR_NO_DST] = FB(482936),
};
const char *const weekdays_pcm_shaped[7] = {
    FB(482943), FB(482950), FB(482957), FB(482967), FB(482974), FB(482981), FB(482994),
};
const char *const months_pcm_shaped[12] = {
    FB(483004), FB(483014), FB(483021), FB(483026), FB(483036), FB(483040), FB(483044),
    FB(483048), FB(483058), FB(483068), FB(483078), FB(483088),
};
const char lang_name_pcm_shaped[] = ("\xEE" "\x80" "\x9B" "\xEE" "\x80" "\x8F" "\xEE" "\x81" "\x86" "\xEE" "\x81" "\x87" "\xEE" "\x81" "\x88");

